local hadesHelpTextFile = rom.path.combine(mod.hadesGameFolder, "Content\\Game\\Text\\es\\HelpText.es.sjson")
local hadesHelpTextTable = mod.DecodeSjsonFile(hadesHelpTextFile)

local hadesTwoHelpTextFile = rom.path.combine(rom.paths.Content(), "Game/Text/es/HelpText.es.sjson")

local order = {
	"Id",
	"InheritFrom",
	"DisplayName",
	"Description",
	"OverwriteLocalization",
}

local newData = {
	-- #region Button/Use Prompts
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_HadesRunStartDoorUseText",
	-- 	DisplayName = "{I} {#UseTextPreReqFormat}Descend into Nightmare",
	-- },
	-- #endregion

	-- #region UI
	{
		Id = "Objective_SurvivalTimer",
		DisplayName = "Sobrevive durante: {$RemainingSeconds} s",
	},
	-- {
	-- 	Id = "ModsNikkelMHadesBiomesPoisonedNoCureHint",
	-- 	DisplayName = "Poison will disappear automatically!",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomesStyxFountainForcedThroughConfig",
	-- 	DisplayName = "Fountain room forced by mod config",
	-- },
	-- #endregion

	-- #region Save File Location Indicators
	{
		Id = "ModsNikkelMHadesBiomesLocation_Hades_Tartarus",
		DisplayName = "TÁRTARO (Pesadilla)",
	},
	{
		Id = "ModsNikkelMHadesBiomesLocation_Hades_Tartarus_Short",
		DisplayName = "Tártaro",
	},
	{
		Id = "ModsNikkelMHadesBiomesLocation_Hades_Asphodel",
		DisplayName = "ASFÓDELOS (Pesadilla)",
	},
	{
		Id = "ModsNikkelMHadesBiomesLocation_Hades_Asphodel_Short",
		DisplayName = "Asfódelos",
	},
	{
		Id = "ModsNikkelMHadesBiomesLocation_Hades_Elysium",
		DisplayName = "ELÍSEO (Pesadilla)",
	},
	{
		Id = "ModsNikkelMHadesBiomesLocation_Hades_Elysium_Short",
		DisplayName = "Elíseo",
	},
	{
		Id = "ModsNikkelMHadesBiomesLocation_Hades_Styx",
		DisplayName = "ESTIGIA (Pesadilla)",
	},
	{
		Id = "ModsNikkelMHadesBiomesLocation_Hades_Styx_Short",
		DisplayName = "Estigia",
	},
	{
		Id = "ModsNikkelMHadesBiomesLocation_Hades_Surface",
		DisplayName = "GRECIA (Pesadilla)",
	},
	{
		Id = "ModsNikkelMHadesBiomesLocation_Hades_Surface_Short",
		DisplayName = "Grecia",
	},
	{
		Id = "ModsNikkelMHadesBiomesLocation_Hades_Challenge",
		DisplayName = "ÉREBO (Pesadilla)",
	},
	{
		Id = "ModsNikkelMHadesBiomesLocation_Hades_Challenge_Short",
		DisplayName = "Érebo",
	},
	-- #endregion

	-- #region NPC/Unit Names
	{
		Id = "ModsNikkelMHadesBiomes_NPC_Bouldy_01",
		DisplayName = "Roquita",
		Description = "",
	},
	-- {
	-- 	Id = "HarpySupportUnit",
	-- 	DisplayName = "The other Furies",
	-- 	Description = "",
	-- },
	-- #endregion

	-- #region Credits
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_InGameCredits_Craft_NikkelM",
	-- 	DisplayName = "a mod by",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_InGameCredits_Name_NikkelM",
	-- 	DisplayName = "NikkelM",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_InGameCredits_Info_Special_Shoutouts",
	-- 	DisplayName = "modding community contributors",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_InGameCredits_Craft_iDeath",
	-- 	DisplayName = "hell2modding",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_InGameCredits_Name_iDeath",
	-- 	DisplayName = "iDeathHD",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_InGameCredits_Craft_burn",
	-- 	DisplayName = "artwork",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_InGameCredits_Name_burn",
	-- 	DisplayName = "burn",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_InGameCredits_Craft_Magic",
	-- 	DisplayName = "modutil",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_InGameCredits_Name_Magic",
	-- 	DisplayName = "Magic_Gonads",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_InGameCredits_Info_Community",
	-- 	DisplayName =
	-- 	"Special thanks to all members of the Hades modding community \n that helped with testing and provided feedback!",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_InGameCredits_Info_SGG_Thanks",
	-- 	DisplayName =
	-- 	"Thank you Supergiant Games for creating Hades and Hades II. \n What follows are the original games' credits.",
	-- },
	-- #endregion

	-- #region Inventory/Resources
	-- #region Fish
	-- #region Tartarus
	-- -- Taken from the Hades HelpText Fish_Tartarus_Common_01
	-- {
	-- _Short variants are limited to 10 characters
	-- 	Id = "Fish_Tartarus_Common_01_Short",
	-- 	DisplayName = "Hellfish",
	-- },
	-- {
	-- 	Id = "Fish_Tartarus_Common_01",
	-- 	DisplayName = "Hellfish",
	-- 	Description = "Common denizen of the River Styx.",
	-- },
	-- {
	-- 	Id = "Fish_Tartarus_Common_01_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolRodIcon} {$WeaponShopItemData.ToolFishingRod.Name} at {$Keywords.FishingPointPlural} in {#BoldFormat}Tartarus (Nightmare){#Prev}"
	-- },
	-- -- Adapted from the Hades CodexText CodexData_FishTartarusCommon01_01
	-- -- Character limit for descriptions is ~210
	-- {
	-- 	Id = "Fish_Tartarus_Common_01_Flavor",
	-- 	DisplayName = "",
	-- 	Description =
	-- 	"From the looks of them, they must have once been stowaways on the outer hull of Charon's boat, securing passage from the surface down into the depths via the River Styx.",
	-- },

	-- {
	-- 	Id = "Fish_Tartarus_Rare_01_Short",
	-- 	DisplayName = "Knuck·head",
	-- },
	-- {
	-- 	Id = "Fish_Tartarus_Rare_01",
	-- 	DisplayName = "Knucklehead",
	-- 	Description = "Uncommon denizen of the River Styx.",
	-- },
	-- {
	-- 	Id = "Fish_Tartarus_Rare_01_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolRodIcon} {$WeaponShopItemData.ToolFishingRod.Name} at {$Keywords.FishingPointPlural} in {#BoldFormat}Tartarus (Nightmare){#Prev}"
	-- },
	-- {
	-- 	Id = "Fish_Tartarus_Rare_01_Flavor",
	-- 	DisplayName = "",
	-- 	Description =
	-- 	"It is believed they once were living sea-creatures themselves, their faint spirits having washed down all the way down via the river Styx, to take on a form of un-life.",
	-- },

	-- {
	-- 	Id = "Fish_Tartarus_Legendary_01_Short",
	-- 	DisplayName = "Scy·scion",
	-- },
	-- {
	-- 	Id = "Fish_Tartarus_Legendary_01",
	-- 	DisplayName = "Scyllascion",
	-- 	Description = "Elusive denizen of the River Styx.",
	-- },
	-- {
	-- 	Id = "Fish_Tartarus_Legendary_01_Details",
	-- 	Description =
	-- 	"· Found infrequently using the {!Icons.ToolRodIcon} {$WeaponShopItemData.ToolFishingRod.Name} at {$Keywords.FishingPointPlural} in {#BoldFormat}Tartarus (Nightmare){#Prev}"
	-- },
	-- {
	-- 	Id = "Fish_Tartarus_Legendary_01_Flavor",
	-- 	DisplayName = "",
	-- 	Description =
	-- 	"Whether or not these creatures are related to Scylla, or merely appear to be, is a matter that is still contested, as no one has yet bothered asking Scylla herself.",
	-- },

	-- #endregion
	-- #region Asphodel
	-- -- Taken from the Hades HelpText Fish_Asphodel_Common_01
	-- {
	-- 	Id = "Fish_Asphodel_Common_01_Short",
	-- 	DisplayName = "Slavug",
	-- },
	-- {
	-- 	Id = "Fish_Asphodel_Common_01",
	-- 	DisplayName = "Slavug",
	-- 	Description = "Common denizen of the River Phlegethon.",
	-- },
	-- {
	-- 	Id = "Fish_Asphodel_Common_01_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolRodIcon} {$WeaponShopItemData.ToolFishingRod.Name} at {$Keywords.FishingPointPlural} in {#BoldFormat}Asphodel (Nightmare){#Prev}"
	-- },
	-- -- Adapted from the Hades CodexText CodexData_FishAsphodelCommon01_01
	-- {
	-- 	Id = "Fish_Asphodel_Common_01_Flavor",
	-- 	DisplayName = "",
	-- 	Description =
	-- 	"It is almost impossible to spot with the naked eye, blending in with the boiling magma, feasting off of bits of molten minerals, who knows what else.",
	-- },

	-- {
	-- 	Id = "Fish_Asphodel_Rare_01_Short",
	-- 	DisplayName = "C·tacean",
	-- },
	-- {
	-- 	Id = "Fish_Asphodel_Rare_01",
	-- 	DisplayName = "Chrustacean",
	-- 	Description = "Uncommon denizen of the River Phlegethon.",
	-- },
	-- {
	-- 	Id = "Fish_Asphodel_Rare_01_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolRodIcon} {$WeaponShopItemData.ToolFishingRod.Name} at {$Keywords.FishingPointPlural} in {#BoldFormat}Asphodel (Nightmare){#Prev}"
	-- },
	-- {
	-- 	Id = "Fish_Asphodel_Rare_01_Flavor",
	-- 	DisplayName = "",
	-- 	Description =
	-- 	"In ocean waters, similar creatures serve as easy prey -- but not this magma-loving variety, which tends to be left alone. Though, some do swim up from the riverbed in search of companionship.",
	-- },

	-- {
	-- 	Id = "Fish_Asphodel_Legendary_01_Short",
	-- 	DisplayName = "Flameater",
	-- },
	-- {
	-- 	Id = "Fish_Asphodel_Legendary_01",
	-- 	DisplayName = "Flameater",
	-- 	Description = "Elusive denizen of the River Phlegethon.",
	-- },
	-- {
	-- 	Id = "Fish_Asphodel_Legendary_01_Details",
	-- 	Description =
	-- 	"· Found infrequently using the {!Icons.ToolRodIcon} {$WeaponShopItemData.ToolFishingRod.Name} at {$Keywords.FishingPointPlural} in {#BoldFormat}Asphodel (Nightmare){#Prev}"
	-- },
	-- {
	-- 	Id = "Fish_Asphodel_Legendary_01_Flavor",
	-- 	DisplayName = "",
	-- 	Description =
	-- 	"Its winding tentacles and scaled body are reminiscent of the serpent Ladon, though whether Ladon or some other monster gave birth to it is, as yet, unknown.",
	-- },

	-- #endregion
	-- #region Elysium
	-- -- Taken from the Hades HelpText Fish_Elysium_Common_01
	-- {
	-- 	Id = "Fish_Elysium_Common_01_Short",
	-- 	DisplayName = "Chlam",
	-- },
	-- {
	-- 	Id = "Fish_Elysium_Common_01",
	-- 	DisplayName = "Chlam",
	-- 	Description = "Common denizen of the River Lethe.",
	-- },
	-- {
	-- 	Id = "Fish_Elysium_Common_01_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolRodIcon} {$WeaponShopItemData.ToolFishingRod.Name} at {$Keywords.FishingPointPlural} in {#BoldFormat}Elysium (Nightmare){#Prev}"
	-- },
	-- -- Adapted from the Hades CodexText CodexData_FishElysiumCommon01_01
	-- {
	-- 	Id = "Fish_Elysium_Common_01_Flavor",
	-- 	DisplayName = "",
	-- 	Description =
	-- 	"The common Chlam is plentiful within the misty waters of the River Lethe, flowing through the hills and valleys of Elysium. Its shell most of the time is shut so tight, it cannot be opened.",
	-- },

	-- {
	-- 	Id = "Fish_Elysium_Rare_01_Short",
	-- 	DisplayName = "Charp",
	-- },
	-- {
	-- 	Id = "Fish_Elysium_Rare_01",
	-- 	DisplayName = "Charp",
	-- 	Description = "Uncommon denizen of the River Lethe.",
	-- },
	-- {
	-- 	Id = "Fish_Elysium_Rare_01_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolRodIcon} {$WeaponShopItemData.ToolFishingRod.Name} at {$Keywords.FishingPointPlural} in {#BoldFormat}Elysium (Nightmare){#Prev}"
	-- },
	-- {
	-- 	Id = "Fish_Elysium_Rare_01_Flavor",
	-- 	DisplayName = "",
	-- 	Description =
	-- 	"The Elysian Charp seems to be the shade of a surface-dwelling fish highly reminiscent of it, with similarly multicolored scales and a placid, almost contemplative temperament.",
	-- },

	-- {
	-- 	Id = "Fish_Elysium_Legendary_01_Short",
	-- 	DisplayName = "Seamare",
	-- },
	-- {
	-- 	Id = "Fish_Elysium_Legendary_01",
	-- 	DisplayName = "Seamare",
	-- 	Description = "Elusive denizen of the River Lethe.",
	-- },
	-- {
	-- 	Id = "Fish_Elysium_Legendary_01_Details",
	-- 	Description =
	-- 	"· Found infrequently using the {!Icons.ToolRodIcon} {$WeaponShopItemData.ToolFishingRod.Name} at {$Keywords.FishingPointPlural} in {#BoldFormat}Elysium (Nightmare){#Prev}"
	-- },
	-- {
	-- 	Id = "Fish_Elysium_Legendary_01_Flavor",
	-- 	DisplayName = "",
	-- 	Description =
	-- 	"In Elysium, many former heroes can be seen staring endlessly into the River Lethe's waters, simply in the hopes of catching a brief glimpse of one of these majestic creatures.",
	-- },

	-- #endregion
	-- #region Styx
	-- -- Taken from the Hades HelpText Fish_Styx_Common_01
	-- {
	-- 	Id = "Fish_Styx_Common_01_Short",
	-- 	DisplayName = "Gupp",
	-- },
	-- {
	-- 	Id = "Fish_Styx_Common_01",
	-- 	DisplayName = "Gupp",
	-- 	Description = "Common denizen of the River Styx.",
	-- },
	-- {
	-- 	Id = "Fish_Styx_Common_01_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolRodIcon} {$WeaponShopItemData.ToolFishingRod.Name} at {$Keywords.FishingPointPlural} in {#BoldFormat}Styx (Nightmare){#Prev}"
	-- },
	-- -- Adapted from the Hades CodexText CodexData_FishStyxCommon01_01
	-- {
	-- 	Id = "Fish_Styx_Common_01_Flavor",
	-- 	DisplayName = "",
	-- 	Description =
	-- 	"This is an altogether odd river-creature, which skirts the border between the surface and the Underworld, likewise persisting in a state somewhere between life and death.",
	-- },

	-- {
	-- 	Id = "Fish_Styx_Rare_01_Short",
	-- 	DisplayName = "Scuffer",
	-- },
	-- {
	-- 	Id = "Fish_Styx_Rare_01",
	-- 	DisplayName = "Scuffer",
	-- 	Description = "Uncommon denizen of the River Styx.",
	-- },
	-- {
	-- 	Id = "Fish_Styx_Rare_01_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolRodIcon} {$WeaponShopItemData.ToolFishingRod.Name} at {$Keywords.FishingPointPlural} in {#BoldFormat}Styx (Nightmare){#Prev}"
	-- },
	-- {
	-- 	Id = "Fish_Styx_Rare_01_Flavor",
	-- 	DisplayName = "",
	-- 	Description =
	-- 	"Truly a bottom-feeder, the Scuffer evidently is much more adventurous than similar varieties, as it dares to dwell in the waters of the River Styx near the border where the waters plummet down into the abyss.",
	-- },

	-- {
	-- 	Id = "Fish_Styx_Legendary_01_Short",
	-- 	DisplayName = "Stonewhal",
	-- },
	-- {
	-- 	Id = "Fish_Styx_Legendary_01",
	-- 	DisplayName = "Stonewhal",
	-- 	Description = "Elusive denizen of the River Styx.",
	-- },
	-- {
	-- 	Id = "Fish_Styx_Legendary_01_Details",
	-- 	Description =
	-- 	"· Found infrequently using the {!Icons.ToolRodIcon} {$WeaponShopItemData.ToolFishingRod.Name} at {$Keywords.FishingPointPlural} in {#BoldFormat}Styx (Nightmare){#Prev}"
	-- },
	-- {
	-- 	Id = "Fish_Styx_Legendary_01_Flavor",
	-- 	DisplayName = "",
	-- 	Description =
	-- 	"The harpoon-nosed Stonewhal is an elusive species that feeds on lesser river creatures that dwell close to the gates of the Underworld, slaying them so that their souls may be eligible for the rest of the journey.",
	-- },

	-- #endregion
	-- #region Surface
	-- -- Taken from the Hades HelpText Fish_Surface_Common_01
	-- {
	-- 	Id = "Fish_Surface_Common_01_Short",
	-- 	DisplayName = "Trout",
	-- },
	-- {
	-- 	Id = "Fish_Surface_Common_01",
	-- 	DisplayName = "Trout",
	-- 	Description = "Common denizen of the Surface Waters.",
	-- },
	-- {
	-- 	Id = "Fish_Surface_Common_01_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolRodIcon} {$WeaponShopItemData.ToolFishingRod.Name} at {$Keywords.FishingPointPlural} on the {#BoldFormat}Surface (Nightmare){#Prev}"
	-- },
	-- -- Adapted from the Hades CodexText CodexData_FishSurfaceCommon01_01
	-- {
	-- 	Id = "Fish_Surface_Common_01_Flavor",
	-- 	DisplayName = "",
	-- 	Description =
	-- 	"On the surface, there are aquatic creatures that live in the drinkable waters of rivers and lakes, and those of Lord Poseidon's salt-filled seas. In the former category, the Trout is a perfectly common breed.",
	-- },

	-- {
	-- 	Id = "Fish_Surface_Rare_01_Short",
	-- 	DisplayName = "Bass",
	-- },
	-- {
	-- 	Id = "Fish_Surface_Rare_01",
	-- 	DisplayName = "Bass",
	-- 	Description = "Uncommon denizen of the Surface Waters.",
	-- },
	-- {
	-- 	Id = "Fish_Surface_Rare_01_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolRodIcon} {$WeaponShopItemData.ToolFishingRod.Name} at {$Keywords.FishingPointPlural} on the {#BoldFormat}Surface (Nightmare){#Prev}"
	-- },
	-- {
	-- 	Id = "Fish_Surface_Rare_01_Flavor",
	-- 	DisplayName = "",
	-- 	Description =
	-- 	"The seas and rivers of the surface absolutely teem with marine life, and people are quite skilled at capturing creatures such as this, which are often traded far and wide.",
	-- },

	-- {
	-- 	Id = "Fish_Surface_Legendary_01_Short",
	-- 	DisplayName = "Sturgeon",
	-- },
	-- {
	-- 	Id = "Fish_Surface_Legendary_01",
	-- 	DisplayName = "Sturgeon",
	-- 	Description = "Elusive denizen of the Surface Waters.",
	-- },
	-- {
	-- 	Id = "Fish_Surface_Legendary_01_Details",
	-- 	Description =
	-- 	"· Found infrequently using the {!Icons.ToolRodIcon} {$WeaponShopItemData.ToolFishingRod.Name} at {$Keywords.FishingPointPlural} on the {#BoldFormat}Surface (Nightmare){#Prev}"
	-- },
	-- {
	-- 	Id = "Fish_Surface_Legendary_01_Flavor",
	-- 	DisplayName = "",
	-- 	Description =
	-- 	"The monstrous Sturgeon is a king among fish. Some are massive in size, their bone-like ridges affording them considerable defense. Little wonder, then, that they are so highly sought-after.",
	-- },

	-- #endregion
	-- #endregion
	-- #region Ore
	-- #region Tartarus
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreTartarus",
	-- 	DisplayName = "Candle Wax",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreTartarus_Short",
	-- 	DisplayName = "Wax",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreTartarus_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_OreTartarus",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_OreTartarus} Candle Wax",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreTartarus_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolPickIcon} {$WeaponShopItemData.ToolPickaxe.Name} on {$Keywords.PickaxePointPlural} in {#BoldFormat}Tartarus (Nightmare){#Prev}"
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreTartarus_Flavor",
	-- 	Description = "Ancient drippings hardened by time, their flames long since extinguished."
	-- },
	-- #endregion
	-- #region Asphodel
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreAsphodel",
	-- 	DisplayName = "Granite",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreAsphodel_Short",
	-- 	DisplayName = "Granite",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreAsphodel_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_OreAsphodel",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_OreAsphodel} Granite",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreAsphodel_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolPickIcon} {$WeaponShopItemData.ToolPickaxe.Name} on {$Keywords.PickaxePointPlural} in {#BoldFormat}Asphodel (Nightmare){#Prev}"
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreAsphodel_Flavor",
	-- 	Description = "In the heat of Asphodel, only the sturdiest of rocks can hope to withstand the test of time."
	-- },
	-- #endregion
	-- #region Elysium
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreElysium",
	-- 	DisplayName = "Lapis Lazuli",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreElysium_Short",
	-- 	DisplayName = "Lazuli",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreElysium_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_OreElysium",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_OreElysium} Lapis Lazuli",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreElysium_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolPickIcon} {$WeaponShopItemData.ToolPickaxe.Name} on {$Keywords.PickaxePointPlural} in {#BoldFormat}Elysium (Nightmare){#Prev}"
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreElysium_Flavor",
	-- 	Description = "Even amongst the most worthy of shades, this celestial stone stands as a treasure worth seeking."
	-- },
	-- #endregion
	-- #region Styx
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreStyx",
	-- 	DisplayName = "Amber",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreStyx_Short",
	-- 	DisplayName = "Amber",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreStyx_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_OreStyx",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_OreStyx} Amber",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreStyx_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolPickIcon} {$WeaponShopItemData.ToolPickaxe.Name} on {$Keywords.PickaxePointPlural} in {#BoldFormat}Styx (Nightmare){#Prev}"
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_OreStyx_Flavor",
	-- 	Description = "Many things seep from the surface into the depths of the Underworld, some more valuable than others."
	-- },
	-- #endregion
	-- #endregion
	-- #region Plants/HarvestPoint
	-- #region Tartarus
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantTartarus",
	-- 	DisplayName = "Blood Root",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantTartarus_Short",
	-- 	DisplayName = "Blood Root",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantTartarus_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_PlantTartarus",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_PlantTartarus} Blood Root",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantTartarus_Details",
	-- 	Description = "· Gathered by hand in {#BoldFormat}Tartarus (Nightmare){#Prev}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantTartarus_Flavor",
	-- 	Description = "The rough hewn stone floors of Tartarus allow this hardy root to take hold and break free.",
	-- },
	-- #endregion
	-- #region Asphodel
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantAsphodel",
	-- 	DisplayName = "Volcanic Fumes",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantAsphodel_Short",
	-- 	DisplayName = "Fumes",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantAsphodel_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_PlantAsphodel",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_PlantAsphodel} Fumes",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantAsphodel_Details",
	-- 	Description = "· Gathered by hand in {#BoldFormat}Asphodel (Nightmare){#Prev}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantAsphodel_Flavor",
	-- 	Description = "In the constant heat of Asphodel, these fumes rise up from cracks in the earth.",
	-- },
	-- #endregion
	-- #region Elysium
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantElysium",
	-- 	DisplayName = "Laurel",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantElysium_Short",
	-- 	DisplayName = "Laurel",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantElysium_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_PlantElysium",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_PlantElysium} Laurel",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantElysium_Details",
	-- 	Description = "· Gathered by hand in {#BoldFormat}Elysium (Nightmare){#Prev}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantElysium_Flavor",
	-- 	Description =
	-- 	"The glorious heroes of Elysium are showered with laurels even in death, where they have no more use for them.",
	-- },
	-- #endregion
	-- #region Styx
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantStyx",
	-- 	DisplayName = "Horned Melon",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantStyx_Short",
	-- 	DisplayName = "Melon",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantStyx_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_PlantStyx",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_PlantStyx} Melon",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantStyx_Details",
	-- 	Description = "· Gathered by hand in {#BoldFormat}Styx (Nightmare){#Prev}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PlantStyx_Flavor",
	-- 	Description = "The toxic environs of Styx give rise to all manner of strange flora.",
	-- },
	-- #endregion
	-- #endregion
	-- #region Seeds/ShovelPoint
	-- #region Tartarus
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedTartarus",
	-- 	DisplayName = "Deathcap Spores",
	-- 	Description =
	-- 	"In {$GardenData.Seeds.ModsNikkelMHadesBiomes_SeedTartarus.GrowTimeMax}{!Icons.Clock}, grow into hearty funghi.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedTartarus_Short",
	-- 	DisplayName = "D·Spores",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedTartarus_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_SeedTartarus",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_SeedTartarus_Icon} Deathcap Spores",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedTartarus_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolShovelIcon} {$WeaponShopItemData.ToolShovel.Name} on {$Keywords.DiggingPointPlural} in {#BoldFormat}Tartarus (Nightmare){#Prev}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedTartarus_Flavor",
	-- 	Description = "It should surprise no one that this mushroom's spores find their way even into Tartarus.",
	-- },
	-- #endregion
	-- #region Asphodel
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedAsphodel",
	-- 	DisplayName = "Ash Flower Seeds",
	-- 	Description =
	-- 	"In {$GardenData.Seeds.ModsNikkelMHadesBiomes_SeedAsphodel.GrowTimeMax}{!Icons.Clock}, grow into warming petals.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedAsphodel_Short",
	-- 	DisplayName = "Ash·Seeds",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedAsphodel_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_SeedAsphodel",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_SeedAsphodel_Icon} Ash Flower Seeds",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedAsphodel_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolShovelIcon} {$WeaponShopItemData.ToolShovel.Name} on {$Keywords.DiggingPointPlural} in {#BoldFormat}Asphodel (Nightmare){#Prev}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedAsphodel_Flavor",
	-- 	Description = "The constant cycle of fire and ash leaves behind only the most resilient shells.",
	-- },
	-- #endregion
	-- #region Elysium
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedElysium",
	-- 	DisplayName = "Rose Quartz Buds",
	-- 	Description =
	-- 	"In {$GardenData.Seeds.ModsNikkelMHadesBiomes_SeedElysium.GrowTimeMax}{!Icons.Clock}, grow into frozen beauty.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedElysium_Short",
	-- 	DisplayName = "Rose·Buds",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedElysium_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_SeedElysium",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_SeedElysium_Icon} Rose Quartz Buds",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedElysium_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolShovelIcon} {$WeaponShopItemData.ToolShovel.Name} on {$Keywords.DiggingPointPlural} in {#BoldFormat}Elysium (Nightmare){#Prev}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedElysium_Flavor",
	-- 	Description = "Though delicate in appearance, these buds are as tough as the heroes of Elysium themselves.",
	-- },
	-- #endregion
	-- #region Styx
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedStyx",
	-- 	DisplayName = "Pumpkin Seeds",
	-- 	Description =
	-- 	"In {$GardenData.Seeds.ModsNikkelMHadesBiomes_SeedStyx.GrowTimeMax}{!Icons.Clock}, grow into golden gourds.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedStyx_Short",
	-- 	DisplayName = "P·Seeds",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedStyx_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_SeedStyx",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_SeedStyx_Icon} Pumpkin Seeds",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedStyx_Details",
	-- 	Description =
	-- 	"· Found using the {!Icons.ToolShovelIcon} {$WeaponShopItemData.ToolShovel.Name} on {$Keywords.DiggingPointPlural} in {#BoldFormat}Styx (Nightmare){#Prev}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SeedStyx_Flavor",
	-- 	Description = "Every witch needs a jar of these seeds stashed away for a rainy day.",
	-- },
	-- #endregion
	-- #endregion
	-- #region Crops/Garden
	-- #region Tartarus
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropTartarus",
	-- 	DisplayName = "Deathcap",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropTartarus_Short",
	-- 	DisplayName = "Deathcap",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropTartarus_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_CropTartarus",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_CropTartarus_Icon} Deathcap",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropTartarus_Details",
	-- 	Description = "· Grown in the {#BoldFormat}Crossroads {#Prev}using {$ResourceData.ModsNikkelMHadesBiomes_SeedTartarus.Name}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropTartarus_Flavor",
	-- 	Description = "Having once grown on the Surface, this mushroom has now adapted to lowest depths of the Underworld as well.",
	-- },
	-- #endregion
	-- #region Asphodel
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropAsphodel",
	-- 	DisplayName = "Ash Flower",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropAsphodel_Short",
	-- 	DisplayName = "Ash Flower",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropAsphodel_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_CropAsphodel",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_CropAsphodel_Icon} Ash Flower",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropAsphodel_Details",
	-- 	Description = "· Grown in the {#BoldFormat}Crossroads {#Prev}using {$ResourceData.ModsNikkelMHadesBiomes_SeedAsphodel.Name}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropAsphodel_Flavor",
	-- 	Description = "As everything in Asphodel, even the flora has adapted to thrive in extreme heat.",
	-- },
	-- #endregion
	-- #region Elysium
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropElysium",
	-- 	DisplayName = "Rose Quartz",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropElysium_Short",
	-- 	DisplayName = "Rose Quartz",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropElysium_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_CropElysium",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_CropElysium_Icon} Rose Quartz",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropElysium_Details",
	-- 	Description = "· Grown in the {#BoldFormat}Crossroads {#Prev}using {$ResourceData.ModsNikkelMHadesBiomes_SeedElysium.Name}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropElysium_Flavor",
	-- 	Description = "A curious mix of plant and crystal, this flower radiates warmth and hope.",
	-- },
	-- #endregion
	-- #region Styx
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropStyx",
	-- 	DisplayName = "Pumpkin",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropStyx_Short",
	-- 	DisplayName = "Pumpkin",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropStyx_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_CropStyx",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_CropStyx_Icon} Pumpkin",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropStyx_Details",
	-- 	Description = "· Grown in the {#BoldFormat}Crossroads {#Prev}using {$ResourceData.ModsNikkelMHadesBiomes_SeedStyx.Name}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_CropStyx_Flavor",
	-- 	Description = "The most sturdy of gourds can find their way into those chambers of Styx nearest the surface.",
	-- },
	-- #endregion
	-- #endregion
	-- #region Boss Drops
	-- #region Tartarus
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceTartarus",
	-- 	DisplayName = "Chthonic Key",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceTartarus_Short",
	-- 	DisplayName = "C·Key",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceTartarus_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_BossResourceTartarus",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_BossResourceTartarus} Chthonic Key",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceTartarus_Details",
	-- 	Description = "· Reward for vanquishing the {#BoldFormat}Guardian {#Prev}of {#BoldFormat}Tartarus (Nightmare){#Prev}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceTartarus_Flavor",
	-- 	Description = "These living keys crumble to dust once used, their purpose fulfilled.",
	-- },
	-- #endregion
	-- #region Asphodel
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceAsphodel",
	-- 	DisplayName = "Diamonds",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceAsphodel_Short",
	-- 	DisplayName = "Diamonds",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceAsphodel_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_BossResourceAsphodel",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_BossResourceAsphodel} Diamonds",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceAsphodel_Details",
	-- 	Description = "· Reward for vanquishing the {#BoldFormat}Guardian {#Prev}of {#BoldFormat}Asphodel (Nightmare){#Prev}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceAsphodel_Flavor",
	-- 	Description = "Forged under pressure in the searing heat of Asphodel.",
	-- },
	-- #endregion
	-- #region Elysium
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceElysium",
	-- 	DisplayName = "Celestial Essence",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceElysium_Short",
	-- 	DisplayName = "C·Essence",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceElysium_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_BossResourceElysium",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_BossResourceElysium} Celestial Essence",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceElysium_Details",
	-- 	Description = "· Reward for vanquishing the {#BoldFormat}Guardians {#Prev}of {#BoldFormat}Elysium (Nightmare){#Prev}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceElysium_Flavor",
	-- 	Description = "Bestowed only upon the most worthy of heroes, this intangible substance emits all colours of light.",
	-- },
	-- #endregion
	-- #region Styx
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceStyx",
	-- 	DisplayName = "Titan Blood",
	-- 	Description = "Not even the Fates are privy to what purpose this may hold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceStyx_Short",
	-- 	DisplayName = "T·Blood",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceStyx_Icon",
	-- 	InheritFrom = "ModsNikkelMHadesBiomes_BossResourceStyx",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomes_BossResourceStyx} Titan Blood",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceStyx_Details",
	-- 	Description = "· Reward for vanquishing the {#BoldFormat}Guardian {#Prev}of {#BoldFormat}Styx (Nightmare){#Prev}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BossResourceStyx_Flavor",
	-- 	Description = "Pulsing with primordial power, this drop of blood contains but a fraction of a Titan's might.",
	-- },
	-- #endregion
	-- #endregion
	-- #endregion

	-- #region Incantations
	-- Unlock Hades Cosmetics with Dora
	-- {
	-- 	Id = "ModsNikkelMHadesBiomesUnlockCosmeticsIncantation",
	-- 	DisplayName = "Recovery of Lost Inventory",
	-- 	Description =
	-- 	"Allow {$Keywords.CharDora} to procure new furnishings and decorations for the renewal project, inspired by your family's past and the {$Keywords.ModsNikkelMHadesBiomesModdedRoute}."
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomesUnlockCosmeticsIncantation_Flavor",
	-- 	Description =
	-- 	"The Princess of the Underworld and her brother Zagreus share an affinity for redecorating their respective abodes, much to the dismay of both their guardians."
	-- },
	-- Add ShrineChallenges/Erebus Gates to modded runs
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockShrinePointGatesIncantation",
	-- 	DisplayName = "Unbinding of Hellish Gateways",
	-- 	Description =
	-- 	"Cause {$Keywords.RoomPlural} in the {$Keywords.ModsNikkelMHadesBiomesModdedRoute} to sometimes contain an {$Keywords.ShrinePointGate}."
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockShrinePointGatesIncantation_Flavor",
	-- 	Description =
	-- 	"Erebus is so much more than the woods surrounding the Crossroads. Your father, the Lord Hades, once used it to keep the ever-growing army of shades awaiting his judgement at bay."
	-- },
	-- Add Pool of Purging/SellShops/SellTraitShops to post-boss rooms
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockPostBossSellShopsIncantation",
	-- 	DisplayName = "Surge of Blood-Red Fountains",
	-- 	Description =
	-- 	"Cause a {$Keywords.SellTraitShop} to always appear in the space between each {$Keywords.Biome} in the {$Keywords.ModsNikkelMHadesBiomesModdedRoute}."
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockPostBossSellShopsIncantation_Flavor",
	-- 	Description =
	-- 	"The Titan Chronos and the boatman Charon may disagree on more things than not, but both are aware that most anything can be bought for the right price, even Olympian favors."
	-- },
	-- Add Pool of Purging/SellShops/SellTraitShops to any rooms during a run
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockInRunSellShopsIncantation",
	-- 	DisplayName = "Rise of Blood-Red Fountains",
	-- 	Description =
	-- 	"Cause {$Keywords.RoomPlural} in the {$Keywords.ModsNikkelMHadesBiomesModdedRoute} to sometimes contain a {$Keywords.SellTraitShop}."
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockPostBossSellShopsIncantation_Flavor",
	-- 	Description =
	-- 	"One would think that any Olympian boon is one to be cherished, but sometimes even the Princess of the Underworld finds herself in need of coin."
	-- },
	-- Add Well of Charon/WellShops to post-boss rooms
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockPostBossWellShopsIncantation",
	-- 	DisplayName = "Surge of Lilac-Flowing Fountains",
	-- 	Description =
	-- 	"Cause a {$Keywords.WellShop} to always appear in the space between each {$Keywords.Biome} in the {$Keywords.ModsNikkelMHadesBiomesModdedRoute}."
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockPostBossWellShopsIncantation_Flavor",
	-- 	Description =
	-- 	"The great Lord Charon has long been known to offer more than just passage across the River Styx - for those who can afford it."
	-- },
	-- Add Well of Charon/WellShops to any rooms during a run
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockInRunWellShopsIncantation",
	-- 	DisplayName = "Rise of Lilac-Flowing Fountains",
	-- 	Description =
	-- 	"Cause {$Keywords.RoomPlural} in the {$Keywords.ModsNikkelMHadesBiomesModdedRoute} to sometimes contain a {$Keywords.WellShop}."
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockInRunWellShopsIncantation_Flavor",
	-- 	Description =
	-- 	"The boatman Charon was of great help to the Prince Zagreus on his attempts to escape the Underworld, always willing to lend a hand - for the right price."
	-- },
	-- Add Keepsake Racks/GiftRack to post-boss rooms
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockPostBossGiftRackIncantation",
	-- 	DisplayName = "Regional Keepsakes",
	-- 	Description =
	-- 	"Manifest your collection of {$Keywords.Keepsakes} in the spaces separating each {$Keywords.Biome} in the {$Keywords.ModsNikkelMHadesBiomesModdedRoute}."
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockPostBossGiftRackIncantation_Flavor",
	-- 	Description =
	-- 	"For the Princess of Nightmares, no dream is too far removed from reality to not allow her to be reminded of those she holds dear."
	-- },
	-- Add Reprieve/Fountain Chambers
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockTartarusReprieveIncantation",
	-- 	DisplayName = "Eerie Lifespring",
	-- 	Description =
	-- 	"Reveal a hidden chamber in {$Keywords.ModsNikkelMHadesBiomesLocation_Hades_Tartarus_Short} in the {$Keywords.ModsNikkelMHadesBiomesModdedRoute}, where you may restore some {!Icons.HealthRestoreHome} and elude your foes."
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockTartarusReprieveIncantation_Flavor",
	-- 	Description =
	-- 	"Tucked away in a long lost corner of Tartarus is an abandoned bath house, where the Erinyes once sought respite from their eternal duties.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockAsphodelReprieveIncantation",
	-- 	DisplayName = "Scalding Lifespring",
	-- 	Description =
	-- 	"Reveal a hidden chamber in {$Keywords.ModsNikkelMHadesBiomesLocation_Hades_Asphodel_Short} in the {$Keywords.ModsNikkelMHadesBiomesModdedRoute}, where you may restore some {!Icons.HealthRestoreHome} and elude your foes."
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockAsphodelReprieveIncantation_Flavor",
	-- 	Description =
	-- 	"How this forgotten fountain has not yet evaporated in the heat of Asphodel is a mystery best not pondered too deeply, lest it leads to answers you do not wish to know.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockElysiumReprieveIncantation",
	-- 	DisplayName = "Foggy Lifespring",
	-- 	Description =
	-- 	"Reveal a hidden chamber in {$Keywords.ModsNikkelMHadesBiomesLocation_Hades_Elysium_Short} in the {$Keywords.ModsNikkelMHadesBiomesModdedRoute}, where you may restore some {!Icons.HealthRestoreHome} and elude your foes."
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockElysiumReprieveIncantation_Flavor",
	-- 	Description =
	-- 	"Even the greatest of heroes who have passed into Elysium are not allowed to drink of the waters flowing from it's fountains, which is reserved for the gods alone.",
	-- },
	-- Add Infernal Troves/Moon Monuments
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockInfernalTrovesIncantation",
	-- 	DisplayName = "Exhumed Plunder",
	-- 	Description =
	-- 	"Cause {$Keywords.RoomPlural} throughout the {$Keywords.ModsNikkelMHadesBiomesModdedRoute} to sometimes contain an {$Keywords.ChallengeSwitch}."
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockInfernalTrovesIncantation_Flavor",
	-- 	Description =
	-- 	"He would not stand to hear it, but the Lord Hades and his father Chronos are not so different when it comes to their safekeeping techniques for Gold.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockMoonMonumentsIncantation",
	-- 	DisplayName = "Claws of Night and Darkness",
	-- 	Description =
	-- 	"Cause {$Keywords.RoomPlural} in the {$Keywords.ModsNikkelMHadesBiomesModdedRoute} to sometimes contain a {$Keywords.EliteChallengeSwitch} or an {$Keywords.PerfectClearChallengeSwitch}."
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_UnlockMoonMonumentsIncantation_Flavor",
	-- 	Description =
	-- 	"The Unseen's reach is greater than many assume, and so it is no surprise that even the {$Keywords.ModsNikkelMHadesBiomesModdedRoute} is not beyond their grasp.",
	-- },	
	-- Add Gold Urns/Breakables
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BreakableValue1Incantation",
	-- 	DisplayName = "Urns of Wealth, Lesser",
	-- 	Description =
	-- 	"Reveal {#BoldFormatGraftDark}Golden Urns {#Prev}in various {$Keywords.RoomPlural} in the {$Keywords.ModsNikkelMHadesBiomesModdedRoute}, which yield {#UpgradeFormatDark}+{$EnemyData.Breakable.BreakableValueOptions[3].MoneyDropOnDeath.MaxValue}{#Prev}{!Icons.Currency} once shattered."
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BreakableValue1Incantation_Flavor",
	-- 	Description =
	-- 	"Gold is a currency accepted both above the Surface and below it.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BreakableValue2Incantation",
	-- 	DisplayName = "Urns of Wealth, Greater",
	-- 	Description =
	-- 	"{#BoldFormatGraftDark}Golden Urns {#Prev}in the {$Keywords.ModsNikkelMHadesBiomesModdedRoute} now yield up to {#UpgradeFormatDark}+{$EnemyData.Breakable.BreakableValueOptions[2].MoneyDropOnDeath.MaxValue}{#Prev}{!Icons.Currency} once shattered."
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BreakableValue2Incantation_Flavor",
	-- 	Description =
	-- 	"Every soul traveling into the Underworld is expected to bring with them payment for their passage - some brough more than required and discarded the excess along the way.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BreakableValue3Incantation",
	-- 	DisplayName = "Urns of Wealth, Superior",
	-- 	Description =
	-- 	"{#BoldFormatGraftDark}Golden Urns {#Prev} in the {$Keywords.ModsNikkelMHadesBiomesModdedRoute} now yield up to {#UpgradeFormatDark}+{$EnemyData.Breakable.BreakableValueOptions[1].MoneyDropOnDeath.MaxValue}{#Prev}{!Icons.Currency} once shattered."
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_BreakableValue3Incantation_Flavor",
	-- 	Description =
	-- 	"The boatman Charon has many sources of income, and often finds himself with more coin than he can carry, knowing any discarded excess will eventually find its way back to him regardless.",
	-- },
	-- #endregion

	-- #region Keywords
	-- {
	-- 	Id = "ModsNikkelMHadesBiomesModdedRoute",
	-- 	DisplayName = "Nightmare Realm",
	-- 	Description = "The {$Keywords.HealthGate} in the Training Grounds reveals a version of the Underworld as it once was.",
	-- },
	-- {
	-- 	Id = "ShrinePointGate",
	-- 	DisplayName = "Erebus Gate",
	-- 	Description = "The {$Keywords.Shrine} is key to entering these challenges at the outer reaches.",
	-- },
	-- #endregion

	-- #region Quests/Minor Prophecies
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestFirstClear",
	-- 	-- Space at the end of the display name is intentional to center the quest in the quest log, where the icon is hidden
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Is There No Escape? ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of breaking free from the realm in which she was born.",
	-- },
	-- {
	-- 	Id = "PersephoneFirstMeeting",
	-- 	DisplayName = "Escape your Nightmare"
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestMeetChthonicGods",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Chthonic Colleagues ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of meeting some of the rulers of the Underworld.",
	-- },
	-- {
	-- 	Id = "A_Boss01",
	-- 	DisplayName = "Met Megaera"
	-- },
	-- {
	-- 	Id = "A_Boss02",
	-- 	DisplayName = "Met Alecto"
	-- },
	-- {
	-- 	Id = "A_Boss03",
	-- 	DisplayName = "Met Tisiphone"
	-- },
	-- {
	-- 	Id = "D_Boss01",
	-- 	DisplayName = "Met Hades"
	-- },
	-- {
	-- 	Id = "ThanatosFirstAppearance",
	-- 	DisplayName = "Met Thanatos"
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestWeaponClears",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Master of Arms ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of breaking free from the realm in which she was born, using each of the {#Emph}Nocturnal Arms{#Prev}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestKeepsakesQuest",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Close at Heart ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday equip various Keepsakes from those who grew closer to her brother.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestMiniBossKills",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Wanton Ransacking ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of slaying various armored Wardens guarding key Underworld chambers.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestCosmeticsSmall",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} A Simple Job ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday employ the Shade called {$Keywords.CharDora} to procure {#Emph}{$QuestData.ModsNikkelMHadesBiomes_QuestCosmeticsSmall.CompleteGameStateRequirements.1.Value} decorations {#Prev}dreamt up from her family's past.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestCodexSmall",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Chthonic Knowledge ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday recall a portion of the knowledge once contained in her brother's Underworld Codex entrusted to him by the great {$Keywords.CharAchilles}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestMetaUpgrades",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Dark Reflections ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of breaking free from the realm in which she was born, whilst influenced by each different {#Emph}{$Keywords.Card}{#Prev}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestPactUpgrades",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Harsh Conditions ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of breaking free from the realm in which she was born, while under the influence of each of the Vows from the {#Emph}Oath of the Unseen{#Prev}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestChaosKeepsakeFullRun",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Amusing Chaos ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of carrying the {#Emph}{$TraitData.RandomBlessingKeepsake.Name} {#Prev}of {#Emph}Primordial Chaos {#Prev}from the start of her nightmare to the very end, and overcome her own father.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestChaosKeepsakeFullRun_Condition",
	-- 	DisplayName = "{!Icons.QuestProgressIncomplete} Take the Embryo All the Way to Victory (In a Nightmare)",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestChaosKeepsakeFullRun_Cleared",
	-- 	DisplayName = "{!Icons.QuestProgressComplete} Take the Embryo All the Way to Victory (In a Nightmare)",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestHermesBeatCharon",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} A Friendly Wager ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of overcoming the Stygian Boatman in two successive battles against him, at the urging of the god of swiftness.",
	-- },
	-- {
	-- 	Id = "BossCharonHermesQuestComplete01",
	-- 	DisplayName = "Defeat Charon in Two Successive Battles Against Him",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestWeaponClearsHighHeat",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Nightmare Princess ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of breaking free from the realm in which she was born, using each of the {#Emph}Nocturnal Arms {#Prev}and {#UseShrinePointFormat}32{#Prev}{!Icons.ShrinePointSmall} from the {#Emph}Oath of the Unseen{#Prev}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestWeaponClearsFast",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Short Work ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of breaking free from the realm in which she was born, in no more than {#BoldFormatGraft}20 minutes{#Prev}, using each of the {#Emph}Nocturnal Arms {#Prev}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestShutdownThanatos",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Death Dealer ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of battling Underworld wretches with {$Keywords.CharThanatos} at her side, and not let him land a single blow.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_ShutdownThanatosFlag",
	-- 	DisplayName = "Beat {$Keywords.CharThanatos} and Don't Let Him Get a Single Kill",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestTenClears",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} The Family Secret ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of breaking free from the realm in which she was born, again and again, until she discovers what her brother's attempts set in motion.",
	-- },
	-- {
	-- 	Id = "Ending01",
	-- 	DisplayName = "Complete Zagreus' Journey",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestSongsSmall",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} The Gift of Song ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday encourage the {$Keywords.MusicPlayer} to perform {#Emph}{$QuestData.ModsNikkelMHadesBiomes_QuestSongsSmall.CompleteGameStateRequirements.1.Value} music pieces {#Prev}once played by the great {$Keywords.CharOrpheus} in the House of Hades.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestPurgeLegendaryBoon",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Thanks, No Thanks ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of risking the wrath of the Gods by trading their most valuable gifts for coin.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_SoldLegendaryBoonFlag",
	-- 	DisplayName =
	-- 	"Purge a Legendary Boon In a {$Keywords.SellTraitShop} In the {$Keywords.ModsNikkelMHadesBiomesModdedRoute}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestThanatosKeepsakeHighPercentage",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Thorn Of Thanatos ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of evading her foes' every strike, whilst carrying the {#Emph}{$TraitData.zannc-SharedKeepsakePort-PerfectClearDamageBonusKeepsake.Name} {#Prev}from {$Keywords.CharThanatos}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_ThanatosKeepsakeAchievedHighPercentage",
	-- 	DisplayName =
	-- 	"Achieve 30% Bonus Damage From the {$TraitData.zannc-SharedKeepsakePort-PerfectClearDamageBonusKeepsake.Name} In the {$Keywords.ModsNikkelMHadesBiomesModdedRoute}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestClearedExtremeMeasuresRun",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Extreme Measures ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of overcoming her father and his strongest allies whilst they are empowered by the {#Emph}{$MetaUpgradeData.BossDifficultyShrineUpgrade.Name}{#Prev}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestClearedExtremeMeasuresRun_Condition",
	-- 	DisplayName =
	-- 	"{!Icons.QuestProgressIncomplete} Defeat {$Keywords.CharHades} With {#LegendaryFormat}Rank IV {#Prev}of the {$MetaUpgradeData.BossDifficultyShrineUpgrade.Name} Active",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestClearedExtremeMeasuresRun_Cleared",
	-- 	DisplayName =
	-- 	"{!Icons.QuestProgressComplete} Defeat {$Keywords.CharHades} With {#LegendaryFormat}Rank IV {#Prev}of the {$MetaUpgradeData.BossDifficultyShrineUpgrade.Name} Active",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestHitlessErebusEncounters",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Hold The Onions ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of overcoming her foes without being hit during {#Emph}{$QuestData.ModsNikkelMHadesBiomes_QuestHitlessErebusEncounters.CompleteGameStateRequirements.1.Value} consecutive {#Prev} {$Keywords.ShrinePointGate} challenges that she has accepted.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestSisyphusUpgrades",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Shade of Chains ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of claiming a variety of gifts offered by the eternal laborer {#Emph}{$Keywords.CharSisyphus}{#Prev}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestEurydiceUpgrades",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Muse of Music ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of sampling the many treats prepared by the carefree nymph {#Emph}{$Keywords.CharEurydice}{#Prev}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestPatroclusUpgrades",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Warrior of Old ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of receiving a number of unwanted blessings handed out by the forgotten warrior {#Emph}{$Keywords.CharPatroclus}{#Prev}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestBouldyUpgrades",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Heart of Stone ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of investing herself and enough {!Icons.GiftPoints} to start believing in the steadfast friend that is {#Emph}{$Keywords.CharBouldy}{#Prev}, and have him believe in her.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestBouldyUpgrades_Condition",
	-- 	DisplayName =
	-- 	"{!Icons.QuestProgressIncomplete} Start Believing in {$Keywords.CharBouldy}, and {$Keywords.CharBouldy} Will Start Believing in You",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestBouldyUpgrades_Cleared",
	-- 	DisplayName =
	-- 	"{!Icons.QuestProgressComplete} Start Believing in {$Keywords.CharBouldy}, and {$Keywords.CharBouldy} Will Start Believing in You",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestAspectClears",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Master of Armaments ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of breaking free from the realm in which she was born, using each and every {#Emph}Aspect {#Prev}of the {#Emph}Nocturnal Arms {#Prev}available to her.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestAspectClearsHighHeat",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Nightmare Queen ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of breaking free from the realm in which she was born, using each and every {#Emph}Aspect {#Prev}of the {#Emph}Nocturnal Arms {#Prev}available to her and {#UseShrinePointFormat}32{#Prev}{!Icons.ShrinePointSmall} from the {#Emph}Oath of the Unseen{#Prev}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestAspectClearsFast",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Short Labor ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of breaking free from the realm in which she was born, in no more than {#BoldFormatGraft}20 minutes{#Prev}, using each and every {#Emph}Aspect {#Prev}of the {#Emph}Nocturnal Arms {#Prev}available to her.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestCropsSmall",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Careful Cultivation ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday gather a variety of strange seeds in the {#Emph}{$Keywords.ModsNikkelMHadesBiomesModdedRoute} {#Prev}and nurture them to full bloom in her {#Emph}Garden{#Prev}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestCropsSmall_Tartarus",
	-- 	DisplayName = "Grow a Hearty {$ResourceData.ModsNikkelMHadesBiomes_CropTartarus.Name}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestCropsSmall_Asphodel",
	-- 	DisplayName = "Grow a Warming {$ResourceData.ModsNikkelMHadesBiomes_CropAsphodel.Name}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestCropsSmall_Elysium",
	-- 	DisplayName = "Grow a Fragile {$ResourceData.ModsNikkelMHadesBiomes_CropElysium.Name}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestCropsSmall_Styx",
	-- 	DisplayName = "Grow a Golden {$ResourceData.ModsNikkelMHadesBiomes_CropStyx.Name}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestFlippedMetaUpgrades",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Reversed Reflections ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of breaking free from the realm in which she was born, whilst influenced by each {#Emph}reversed {$Keywords.Card}{#Prev}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestLog_BaseStaffAspect",
	-- 	DisplayName = "Aspect of Melinoë (Descura)",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestLog_DaggerBackstabAspect",
	-- 	-- Using & due to character length limitation
	-- 	DisplayName = "Aspect of Melinoë (Lim & Oros)",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestLog_TorchSpecialDurationAspect",
	-- 	DisplayName = "Aspect of Melinoë (Ygnium)",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestLog_AxeRecoveryAspect",
	-- 	DisplayName = "Aspect of Melinoë (Zorephet)",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestLog_LobAmmoBoostAspect",
	-- 	DisplayName = "Aspect of Melinoë (Revaal)",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestLog_BaseSuitAspect",
	-- 	DisplayName = "Aspect of Melinoë (Xinth)",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestModdedRandomBountyClearStreak",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Implausible Outcomes ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday clear any of the {#Emph}{$BountyData.ModsNikkelMHadesBiomes_PackageBountyRandom_Difficulty1.Name} {#Prev}Trials appearing in the {#Emph}{$Keywords.BountyBoard} {#Prev}at least three times, without fail.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestModdedRandomBountyClearStreak_Condition",
	-- 	DisplayName =
	-- 	"{!Icons.QuestProgressIncomplete} Successively Clear Any Three All-Random {$Keywords.PackagedBounties} in the {$Keywords.ModsNikkelMHadesBiomesModdedRoute}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestModdedRandomBountyClearStreak_Cleared",
	-- 	DisplayName =
	-- 	"{!Icons.QuestProgressComplete} Successively Clear Any Three All-Random {$Keywords.PackagedBounties} in the {$Keywords.ModsNikkelMHadesBiomesModdedRoute}",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_QuestEliteAttributeKills",
	-- 	DisplayName = "{!Icons.ModsNikkelMHadesBiomesRunHistoryDoorLarge} Exposed Fangs ",
	-- 	Description =
	-- 	"The daughter of the god of the dead shall someday dream of vanquishing foes imbued with each of the different dangerous Perks {#Emph}unique to the {$Keywords.ModsNikkelMHadesBiomesModdedRoute} {#Prev}from the {#Emph}{$MetaUpgradeData.EnemyEliteShrineUpgrade.Name} {#Prev}in the {#Emph}Oath of the Unseen{#Prev}."
	-- },
	-- #endregion

	-- #region Chaos Trials/Bounties
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PackageBountyRandom_Difficulty1",
	-- 	DisplayName = "Chaos Within",
	-- 	Description =
	-- 	"Let {$Keywords.CharChaos} influence almost every factor in your battle through the {$Keywords.ModsNikkelMHadesBiomesModdedRoute}, though with {#ShrineHighlightFormat}{$BountyData.ModsNikkelMHadesBiomes_PackageBountyRandom_Difficulty1.RandomShrineUpgradePointTotal}{#Prev}{!Icons.ShrinePointNoTooltip} {#Emph}Fear{#Prev}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PackageBountyRandom_Difficulty1_Short",
	-- 	DisplayName = "Chaos Within",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PackageBountyRandom_Difficulty2",
	-- 	DisplayName = "Great Chaos Within",
	-- 	Description =
	-- 	"Let {$Keywords.CharChaos} influence almost every factor in your battle through the {$Keywords.ModsNikkelMHadesBiomesModdedRoute}, including {#ShrineHighlightFormat}{$BountyData.ModsNikkelMHadesBiomes_PackageBountyRandom_Difficulty2.RandomShrineUpgradePointTotal}{#Prev}{!Icons.ShrinePointNoTooltip} {#Emph}Fear {#Prev}of randomly selected {#Emph}Vows{#Prev}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PackageBountyRandom_Difficulty2_Short",
	-- 	DisplayName = "Great Chaos Within",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PackageBountyRandom_Difficulty3",
	-- 	DisplayName = "Greater Chaos Within",
	-- 	Description =
	-- 	"Let {$Keywords.CharChaos} influence almost every factor in your battle through the {$Keywords.ModsNikkelMHadesBiomesModdedRoute}, including {#ShrineHighlightFormat}{$BountyData.ModsNikkelMHadesBiomes_PackageBountyRandom_Difficulty3.RandomShrineUpgradePointTotal}{#Prev}{!Icons.ShrinePointNoTooltip} {#Emph}Fear {#Prev}of randomly selected {#Emph}Vows{#Prev}.",
	-- },
	-- {
	-- 	Id = "ModsNikkelMHadesBiomes_PackageBountyRandom_Difficulty3_Short",
	-- 	DisplayName = "Greater Chaos Within",
	-- },
	-- #endregion
}

local hadesHelpTextCopiedEntries = mod.ModifyHadesHelpTextEntries(hadesHelpTextTable)

sjson.hook(hadesTwoHelpTextFile, function(data)
	mod.AddTableKeysSkipDupes(data.Texts, newData, "Id", order)
	mod.AddTableKeysSkipDupes(data.Texts, hadesHelpTextCopiedEntries, "Id", order)
end)
