local hadesTwoTartarusObstacleFile = rom.path.combine(rom.paths.Content(),
	"Game\\Animations\\Obstacle_Deprecated_VFX.sjson")

-- Modifications to existing obstacle animations in Hades II
-- These should NOT be in use by Hades II to not break functionality there!
local hadesTwoObstacleModifications = {
	-- #region TARTARUS
	-- For the reaction animations, they cannot be set as a ChildAnimation, must be in CreateAnimations
	["TartarusPillarBase04A-Fx"] = {
		ChildAnimation = "null",
		CreateAnimation = "TartarusPillarBase04A-Transition",
	},
	["TartarusPillarBase04B-Fx"] = {
		ChildAnimation = "null",
		CreateAnimation = "TartarusPillarBase04B-Transition",
	},
	["TartarusPillarBase04C-Fx"] = {
		ChildAnimation = "null",
		CreateAnimation = "TartarusPillarBase04C-Transition",
	},
	-- #endregion

	-- #region ASPHODEL
	AsphodelBoatSunkUnlocked = {
		ChildAnimation = "AsphodelRoomRewardAvailable-Back",
	},
	HealthFountainEmptyAsphodel = {
		ChildAnimation = "ModsNikkelMHadesBiomes-HealthFountainEmptyAsphodelWater",
	},
	-- #endregion

	-- #region ELYSIUM
	-- For the reaction animations, they cannot be set as a ChildAnimation, must be in CreateAnimations
	ElysiumPillarB = {
		ChildAnimation = "null",
		CreateAnimation = "Elysium_Pillar04TransitionA",
	},
	ElysiumPillarC = {
		ChildAnimation = "null",
		CreateAnimation = "Elysium_Pillar04TransitionB",
	},
	-- #endregion

	-- #region STYX
	StyxDoorOpen = {
		ChildAnimation = "null",
		CreateAnimation = "StyxDoorOpenAnim",
	},
	StyxDoorClose = {
		ChildAnimation = "null",
		CreateAnimation = "StyxDoorCloseAnim",
	},
	StyxPillarB = {
		ChildAnimation = "null",
		CreateAnimation = "Styx_Pillar03TransitionA",
	},
	StyxPillarC = {
		ChildAnimation = "null",
		CreateAnimation = "Styx_Pillar03TransitionB",
	},
	StyxPillarD = {
		ChildAnimation = "null",
		CreateAnimation = "Styx_Pillar03TransitionC",
	},
	-- #endregion

	-- #region Surface
	BossPillarB = {
		ChildAnimation = "null",
		CreateAnimation = "BossPillarTransitionA",
	},
	BossPillarC = {
		ChildAnimation = "null",
		CreateAnimation = "BossPillarTransitionB",
	},
	BossPillarD = {
		ChildAnimation = "null",
		CreateAnimation = "BossPillarTransitionC",
	},
	-- #endregion
}

local addAnimationsParents = {
	-- #region GENERAL
	{
		Name = "ModsNikkelMHadesBiomesAsphodel-RoomRewardAvailable-Front",
		FilePath = "NikkelM-HadesBiomesFxModded\\Fx\\RoomRewardAvailable-Front\\RoomRewardAvailable-Front",
		Scale = 1.1,
		AngleFromOwner = "Ignore",
		ColorFromOwner = "Ignore",
		EndFrame = 40,
		Loop = true,
		NumFrames = 40,
		PlaySpeed = 30.0,
		StartFrame = 1,
		ScaleFromOwner = "Ignore",
		Ambient = 0.0,
		OnlyWhenVisible = true,
	},
	-- #endregion

	-- #region STYX
	{
		Name = "PoisonCureFountainFull",
		ChildAnimation = "PoisonCureFountainFullAnim",
		FilePath = "Tilesets\\Styx\\Styx_PoisonCure_01",
		Sound = "/SFX/PoisonCureFountainBubbleLoop",
		StopSoundOnFinishFade = 0.3,
		EndFrame = 1,
		NumFrames = 1,
		StartFrame = 1,
		OffsetY = -400.0,
		Scale = 0.4,
		SoundAllowedAfterFrame = -1,
	},
	{
		Name = "HealthFountainFullStyx",
		ChildAnimation = "StyxHealthFountainWater",
		FilePath = "Tilesets\\Styx\\Styx_Fountain_01",
		Sound = "/Leftovers/Object Ambiences/WaterStyxHealthRestoreFountain",
		StopSoundOnFinishFade = 0.3,
		EndFrame = 1,
		NumFrames = 1,
		StartFrame = 1,
		OffsetY = -400.0,
		VisualFxIntervalMax = 0.12,
		VisualFxIntervalMin = 0.1,
		SoundAllowedAfterFrame = -1,
	},
	-- #endregion
}

local addAnimations = {
	-- #region GENERAL
	{
		Name = "ModsNikkelMHadesBiomesAsphodel-RoomRewardAvailable-Front_MetaReward",
		InheritFrom = "ModsNikkelMHadesBiomesAsphodel-RoomRewardAvailable-Front",
		Hue = -0.5,
	},
	-- #endregion

	-- #region ASPHODEL
	{
		Name = "ModsNikkelMHadesBiomes-HealthFountainEmptyAsphodelWater",
		InheritFrom = "HealthFountainFullAsphodelWater",
		VisualFx = nil,
		Alpha = 0.6,
	},
	-- #endregion

	-- #region STYX
	{
		Name = "PoisonCureFountainStyxFullStart",
		InheritFrom = "PoisonCureFountainFull",
		ChainTo = "PoisonCureFountainFull",
		Sound = "/EmptyCue",
		Duration = 0.1,
	},
	{
		Name = "PoisonCureFountainSparkles",
		FilePath = "Particles\\particle_snow_03",
		Angle = 90.0,
		AngleFromOwner = "Ignore",
		AddColor = true,
		EndFrame = 1,
		NumFrames = 1,
		RandomDurationMax = 2.0,
		RandomDurationMin = 1.0,
		StartFrame = 1,
		OffsetZ = 55.0,
		RandomOffsetX = 30.0,
		RandomOffsetY = 2.0,
		LocationFromOwner = "Ignore",
		SortMode = "FromParent",
		VelocityMax = 60.0,
		VelocityMin = 10.0,
		EndScale = 0.0,
		Scale = 0.1,
		ScaleFromOwner = "Ignore",
		ScaleMax = 1.0,
		ScaleMin = 0.5,
		RandomAccelerationMax = -5.0,
		RandomAccelerationMin = -20.0,
		Color = { Red = 0.50, Green = 0.4, Blue = 0.0 },
	},
	{
		Name = "PoisonCureFountainFullAnim",
		ChildAnimation = "PoisonCureFountainGlow",
		FilePath = "Fx\\StyxPoisonCureWater\\StyxPoisonCureWater",
		VisualFx = "PoisonCureFountainSparkles",
		EndFrame = 30,
		Loop = true,
		NumFrames = 30,
		PlaySpeed = 30.0,
		StartFrame = 1,
		OffsetY = -145.0,
		Scale = 1.66,
		Ambient = 0.0,
		VisualFxIntervalMax = 0.12,
		VisualFxIntervalMin = 0.1,
	},
	{
		Name = "PoisonCureFountainGlow",
		FilePath = "Particles\\particle_glow",
		GroupName = "FX_Standing_Add",
		VisualFx = "PoisonCureFountainGlowSmoke",
		AngleFromOwner = "Ignore",
		ColorFromOwner = "Ignore",
		EndAlpha = 0.25,
		PingPongColor = true,
		StartAlpha = 0.15,
		Duration = 2.0,
		EaseOut = 1.0,
		EndFrame = 1,
		Loop = true,
		NumFrames = 1,
		StartFrame = 1,
		OffsetZ = 100.0,
		DieWithOwner = true,
		SortMode = "FromParent",
		ScaleFromOwner = "Ignore",
		ScaleX = 0.75,
		ScaleY = 1.25,
		Ambient = 0.0,
		VisualFxIntervalMax = 0.6,
		VisualFxIntervalMin = 0.5,
		Color = { Red = 1.0, Green = 0.90, Blue = 0.50 },
	},
	{
		Name = "PoisonCureFountainGlowSmoke",
		FilePath = "Fx\\DeathFxDark\\DeathFxDark",
		GroupName = "FX_Standing_Add",
		AddColor = true,
		AlphaMax = 0.2,
		AlphaMin = 0.1,
		EndAlpha = 1.0,
		PingPongColor = true,
		EaseOut = 1.0,
		EndFrame = 56,
		NumFrames = 56,
		RandomPlaySpeedMax = 30.0,
		RandomPlaySpeedMin = 24.0,
		StartFrame = 1,
		RandomFlipHorizontal = true,
		OffsetZ = -30.0,
		OriginX = 182.0,
		OriginY = 328.0,
		RandomOffsetX = 30.0,
		DieWithOwner = true,
		LocationZFromOwner = "Ignore",
		SortMode = "FromParent",
		EndScaleY = 1.5,
		Scale = 2.0,
		ScaleMax = 1.0,
		ScaleMin = 0.6,
		Ambient = 0.0,
		Color = { Red = 1.0, Green = 0.90, Blue = 0.4 },
	},
	{
		Name = "PoisonCureFountainEmpty",
		InheritFrom = "PoisonCureFountainFull",
		ChildAnimation = "null",
		FilePath = "Tilesets\\Styx\\Styx_PoisonCure_01b",
		Sound = "/EmptyCue",
		Saturation = -0.2,
		Color = { Red = 0.6, Green = 0.70, Blue = 0.8 },
	},
	{
		Name = "HealthFountainFullStyxStart",
		InheritFrom = "HealthFountainFullStyx",
		ChainTo = "HealthFountainFullStyx",
		Duration = 0.1,
	},
	{
		Name = "StyxHealthFountainWater",
		FilePath = "Fx\\StyxHealthFountainWater\\StyxHealthFountainWater",
		VisualFx = "HealthFountainSparkleStyx",
		EndFrame = 30,
		Loop = true,
		NumFrames = 30,
		PlaySpeed = 30.0,
		StartFrame = 1,
		OffsetX = 6.0,
		OffsetY = -560.0,
		TransferFrameFromThis = true,
		Scale = 2.0,
		Ambient = 0.0,
		VisualFxIntervalMax = 0.15,
		VisualFxIntervalMin = 0.1,
	},
	{
		Name = "HealthFountainStreaksStyx",
		FilePath = "Particles\\particle_streak",
		GroupName = "FX_Standing_Add",
		Angle = 90.0,
		AddColor = true,
		AlphaMax = 1.0,
		AlphaMin = 0.1,
		EndAlpha = 0.2,
		PingPongColor = true,
		EaseOut = 1.0,
		EndFrame = 1,
		NumFrames = 1,
		RandomDurationMax = 2.0,
		RandomDurationMin = 1.0,
		StartFrame = 1,
		RandomFlipHorizontal = true,
		RandomFlipVertical = true,
		EndOffsetY = -60.0,
		OffsetZ = 600.0,
		RandomOffsetX = 100.0,
		RandomOffsetY = 75.0,
		SortMode = "Id",
		EndScaleY = 3.0,
		ScaleFromOwner = "Ignore",
		ScaleMax = 1.0,
		ScaleMin = 0.8,
		ScaleX = 1.5,
		ScaleY = 0.5,
		StartScaleY = 0.25,
		Color = { Red = 1.0, Green = 0.8, Blue = 0.6 },
	},
	{
		Name = "HealthFountainSparkleStyx",
		CreateAnimation = "HealthFountainStreaksStyx",
		FilePath = "Particles\\particle_addFlake2",
		GroupName = "FX_Standing_Add",
		AngleMax = 91.0,
		AngleMin = 90.0,
		AddColor = true,
		AlphaMax = 1.0,
		EndFrame = 1,
		NumFrames = 1,
		RandomDurationMax = 4.0,
		RandomDurationMin = 2.0,
		StartFrame = 1,
		OffsetZ = 350.0,
		OriginX = -30.0,
		OriginY = 30.0,
		RandomOffsetX = 150.0,
		RandomOffsetY = 75.0,
		LocationFromOwner = "Ignore",
		SortMode = "Id",
		Acceleration = -30.0,
		VelocityMax = 120.0,
		VelocityMin = 60.0,
		RandomRotation = true,
		RandomRotationSpeedMax = 90.0,
		RandomRotationSpeedMin = -90.0,
		PingPongScale = true,
		Scale = 2.0,
		ScaleFromOwner = "Ignore",
		ScaleMax = 0.25,
		ScaleMin = 0.02,
		StartScale = 0.0,
		Ambient = 0.0,
		AngleFromOwner = "Ignore",
		Color = { Red = 0.0, Green = 0.8, Blue = 1.0 },
	},
	{
		Name = "HealthFountainEmptyStyx",
		InheritFrom = "HealthFountainFullStyx",
		ChildAnimation = "StyxHealthFountainWaterFade",
		Sound = "/EmptyCue",
		EndBlue = 0.25,
		EndGreen = 0.25,
		EndRed = 0.25,
		StartBlue = 1.0,
		StartGreen = 1.0,
		StartRed = 1.0,
		Duration = 0.3,
		HoldLastFrame = true,
	},
	{
		Name = "StyxHealthFountainWaterFade",
		InheritFrom = "StyxHealthFountainWater",
		VisualFx = "null",
		EndBlue = 0.25,
		EndGreen = 0.25,
		EndRed = 0.25,
		StartAlpha = 1.0,
		StartBlue = 1.0,
		StartGreen = 1.0,
		StartRed = 1.0,
		Duration = 0.3,
		HoldLastFrame = true,
		Loop = false,
		LoopFramesOnly = true,
		TransferFrameToThis = true,
	},
	{
		Name = "HubBossDoorOpen",
		FilePath = "Screens\\HubBossDoorOpen\\HubBossDoorOpen",
		VideoTexture = "HubBossDoorOpen",
		Sound = "/Leftovers/World Sounds/ScribeGateUp",
		EndFrame = 95,
		HoldLastFrame = true,
		NumFrames = 95,
		PlaySpeed = 30.0,
		StartFrame = 1,
		Scale = 4.0,
		AngleFromOwner = "Ignore",
		CreateAnimations = {
			{ Name = "HubBossDoorOpenFog" },
			{ Name = "HubBossDoorOpenFog" },
			{ Name = "HubBossDoorOpenFog" },
			{ Name = "HubBossDoorOpenFog" },
		},
	},
	{
		Name = "HubBossDoorOpenFog",
		FilePath = "Fx\\GroundFogIso\\GroundFogIso",
		NumFrames = 138,
		RandomPlaySpeedMin = 24,
		RandomPlaySpeedMax = 30,
		StartAlpha = 0,
		EndAlpha = 1,
		PingPongColor = true,
		LoopFramesOnly = true,
		Loop = false,
		RandomDurationMin = 2,
		RandomDurationMax = 4,
		RandomStartFrame = true,
		UseOwnAngle = false,
		AngleMin = 200,
		AngleMax = 260,
		RandomOffsetX = 0,
		OffsetZ = 0,
		ScaleMin = 0.8,
		ScaleMax = 1.0,
		Scale = 1,
		AngleFromOwner = "Ignore",
		LocationFromOwner = "Ignore",
		LocationZFromOwner = "Ignore",
		Red = 0.7,
		Green = 0.85,
		Blue = 1.0,
		VelocityMin = 200,
		VelocityMax = 300,
		Acceleration = -200,
		StartScale = 1,
		EndScale = 2,
		ReRandomizeOnLoop = false,
		ScaleFromOwner = "Ignore",
		GroupName = "Standing",
		SortMode = "FromParent",
		Material = "Unlit",
	},
	-- #endregion

	-- #region HADES
	{
		Name = "ModsNikkelMHadesBiomesBloodstoneProjectileHades",
		InheritFrom = "BloodstoneProjectileHades",
		ChildAnimation = "BloodstoneProjectileHadesFlameSpanwer"
	}
	-- #endregion
}

sjson.hook(hadesTwoTartarusObstacleFile, function(data)
	local sjsonLoads = mod.TryLoadCachedSjsonFile("sjsonLoads.sjson") or {}
	sjsonLoads["Obstacle_Deprecated_VFX"] = true
	mod.SaveCachedSjsonFile("sjsonLoads.sjson", sjsonLoads)

	mod.AddTableKeysSkipDupes(data.Animations, addAnimationsParents, "Name")
	mod.AddTableKeysSkipDupes(data.Animations, addAnimations, "Name")
	mod.ApplyNestedSjsonModifications(data.Animations, hadesTwoObstacleModifications)
end)
