-- Contains the original Hades Credits data, as well as mod credits at the top
-- TODO: Mod credits
mod.CreditsFormat = {
	Header = {
		Font = "SpectralSCExtraLight",
		Justification = "Center",
		Scale = 0.70,
		Color = game.Color.White,
		ShadowColor = { 0, 0, 0, 1.0 },
		OutlineColor = { 0, 0, 0, 0 },
		ShadowOffsetY = 2,
		ShadowOffsetX = 0,
		ShadowAlpha = 1,
		ShadowBlur = 0,
		LangKoScaleModifier = 1.4,
		LangJaScaleModifier = 1.4,
		LangCnScaleModifier = 1.4,
		-- 
		FontSize = 50,
	},
	Craft = {
		Font = "SpectralSCLight",
		Justification = "Center",
		Scale = 0.6,
		Color = { 255, 221, 103, 255 },
		ShadowColor = { 0, 0, 0, 1.0 },
		OutlineColor = { 0, 0, 0, 0 },
		ShadowOffsetY = 2,
		ShadowOffsetX = 0,
		ShadowAlpha = 1,
		ShadowBlur = 0,
		LangKoScaleModifier = 1.4,
		LangJaScaleModifier = 1.6,
		LangCnScaleModifier = 1.4,
		-- 
		FontSize = 40,
	},
	Dedication = {
		Font = "SpectralSCLight",
		Justification = "Center",
		Scale = 0.7,
		Color = game.Color.White,
		ShadowColor = { 0, 0, 0, 1.0 },
		OutlineColor = { 0, 0, 0, 0 },
		ShadowOffsetY = 2,
		ShadowOffsetX = 0,
		ShadowAlpha = 1,
		ShadowBlur = 0,
		LangKoScaleModifier = 1.4,
		LangCnScaleModifier = 1.4,
	},
	Name = {
		Font = "SpectralSCMedium",
		Justification = "Center",
		Scale = 0.6,
		Color = game.Color.White,
		ShadowColor = { 0, 0, 0, 1.0 },
		OutlineColor = { 0, 0, 0, 0 },
		ShadowOffsetY = 2,
		ShadowOffsetX = 0,
		ShadowAlpha = 0,
		ShadowBlur = 0,
		LangKoScaleModifier = 1.4,
		LangCnScaleModifier = 1.4,
		-- 
		FontSize = 40,
	},
	Company = {
		Font = "SpectralSCLight",
		Justification = "Center",
		Scale = 0.6,
		Color = { 206, 193, 154, 255 },
		ShadowColor = { 0, 0, 0, 1.0 },
		OutlineColor = { 0, 0, 0, 0 },
		ShadowOffsetY = 2,
		ShadowOffsetX = 0,
		ShadowAlpha = 0,
		ShadowBlur = 0,
		LangKoScaleModifier = 1.4,
		LangCnScaleModifier = 1.4,
		-- 
		FontSize = 40,
	},
	Info = {
		Font = "SpectralSCMedium",
		Justification = "Center",
		Scale = 0.53,
		Color = { 254, 255, 187, 255 },
		ShadowColor = { 0, 0, 0, 1.0 },
		OutlineColor = { 0, 0, 0, 0 },
		ShadowOffsetY = 2,
		ShadowOffsetX = 0,
		ShadowAlpha = 0,
		ShadowBlur = 0,
		LangKoScaleModifier = 1.4,
		LangCnScaleModifier = 1.4,
		-- 
		FontSize = 40,
	},
	TranslatedLanguage = {
		Font = "SpectralSCMedium",
		Justification = "Center",
		Scale = 0.6,
		Color = { 255, 227, 140, 255 },
		ShadowColor = { 0, 0, 0, 1.0 },
		OutlineColor = { 0, 0, 0, 0 },
		ShadowOffsetY = 2,
		ShadowOffsetX = 0,
		ShadowAlpha = 0,
		ShadowBlur = 0,
		LangKoScaleModifier = 1.4,
		LangCnScaleModifier = 1.4,
		-- 
		FontSize = 40,
	},
	Legal = {
		Font = "SpectralSCMedium",
		Justification = "Center",
		Scale = 0.72,
		Color = game.Color.White,
		ShadowColor = { 0, 0, 0, 0 },
		OutlineColor = { 0, 0, 0, 0 },
		ShadowOffsetY = 2,
		ShadowOffsetX = 0,
		ShadowAlpha = 0,
		ShadowBlur = 0,
		LangKoScaleModifier = 1.4,
		LangCnScaleModifier = 1.4,
		-- 
		FontSize = 40,
	},
}

local screenShiftX = 530
local screenTop = 60
mod.CreditSpacing = {
	ColumnLeft = game.ScreenCenterX - 240 - screenShiftX,
	ColumnRight = game.ScreenCenterX + 240 - screenShiftX,
	ColumnCenter = game.ScreenCenterX - screenShiftX,

	CColumnLeft = game.ScreenCenterX - 200 - screenShiftX,
	CColumnRight = game.ScreenCenterX + 200 - screenShiftX,

	CreditScrollStart = game.ScreenHeight + 120,

	CreditLineBufferTitle = 160,
	CreditLineBufferCraftToName = 32,
	CreditLineBufferNameToNextCraft = 58,
	CreditLineBufferScroll = 100,
}

mod.CreditsData = {
	Return01 = {
		-- Supergiant
		-- { PreWait = 36.4 },
		{ PreWait = 2.4 },

		{ CreateScreenObstacle = "EndCreditsVignette",                         X = 0,                              Y = 540,                         SkipScreenAnchors = true },
		{ CreateScreenObstacle = "EndCreditsSupergiantLogo",                   X = game.ScreenCenterX - 530,       Y = screenTop + 25 },

		{ CreditLineBuffer = 192 },

		{ PreWait = 2.3 },

		{ Text = "InGameCredits_Craft_Amir",                                   X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Craft },
		{ Text = "InGameCredits_Craft_Gavin",                                  X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Amir",                                    X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Gavin",                                   X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferNameToNextCraft },

		{ PreWait = 0.3 },

		{ Text = "InGameCredits_Craft_Greg",                                   X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Craft },
		{ Text = "InGameCredits_Craft_Andrew",                                 X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Greg",                                    X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Andrew",                                  X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferNameToNextCraft },

		{ PreWait = 0.3 },

		{ Text = "InGameCredits_Craft_Darren",                                 X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Craft },
		{ Text = "InGameCredits_Craft_Jen",                                    X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Darren",                                  X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Jen",                                     X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferNameToNextCraft },

		{ PreWait = 0.3 },

		{ Text = "InGameCredits_Craft_Josh",                                   X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Craft },
		{ Text = "InGameCredits_Craft_JP",                                     X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Josh",                                    X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_JP",                                      X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferNameToNextCraft },

		{ PreWait = 0.3 },

		{ Text = "InGameCredits_Craft_Dexter",                                 X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Craft },
		{ Text = "InGameCredits_Craft_Ed",                                     X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Dexter",                                  X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Ed",                                      X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferNameToNextCraft },

		{ PreWait = 0.3 },

		{ Text = "InGameCredits_Craft_Alice",                                  X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Craft },
		{ Text = "InGameCredits_Craft_Joanne",                                 X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Alice",                                   X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Joanne",                                  X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferNameToNextCraft },

		{ PreWait = 0.3 },

		{ Text = "InGameCredits_Craft_Caitlin",                                X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Craft },
		{ Text = "InGameCredits_Craft_Paige",                                  X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Caitlin",                                 X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Paige",                                   X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferNameToNextCraft },

		{ PreWait = 0.3 },

		{ Text = "InGameCredits_Craft_Thinh",                                  X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Craft },
		{ Text = "InGameCredits_Craft_Will",                                   X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Thinh",                                   X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Will",                                    X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferNameToNextCraft },

		{ PreWait = 0.3 },

		{ Text = "InGameCredits_Craft_Nikola",                                 X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Craft },
		{ Text = "InGameCredits_Craft_Jesse",                                  X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Nikola",                                  X = mod.CreditSpacing.ColumnLeft,   Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Jesse",                                   X = mod.CreditSpacing.ColumnRight,  Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = 44 },

		{ PreWait = 0.3 },

		{ Text = "InGameCredits_Craft_Logan",                                  X = mod.CreditSpacing.ColumnCenter, Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Logan",                                   X = mod.CreditSpacing.ColumnCenter, Format = mod.CreditsFormat.Name },

		{ PreWait = 9.0 },

		{ ScrollOn = true },
	},

	Return02 = {
		-- Additional Credits

		{ PreWait = 1.0 },

		{ CreateScreenObstacle = "EndCreditsVignette",                     X = 0,                             Y = 540,                      SkipScreenAnchors = true },
		{ ScrollOn = true,                                                 ScrollSpeedOverride = 56,          ScrollDistanceOverride = 4880 },

		{ CreditLineBuffer = mod.CreditSpacing.CreditScrollStart },

		{ Text = "InGameCredits_Header_AdditionalCredits",                 Format = mod.CreditsFormat.Header },

		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferTitle },

		{ Text = "InGameCredits_Craft_Michael",                            Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Michael",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Craft_Camilo",                             Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Camilo",                              Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Craft_Morgan",                             Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Morgan",                              Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Craft_Ashley",                             Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ashley",                              Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Craft_Andre",                              Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Andre",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tyler",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Craft_Brad",                               Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Brad",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Craft_James",                              Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_James",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Allison",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ellis",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Craft_SDL",                                Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Company_SDL",                              Format = mod.CreditsFormat.Company },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Craft_84",                                 Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Company_84",                               Format = mod.CreditsFormat.Company },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_84_1",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_84_2",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_84_3",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_84_4",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_84_4_1",                              Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_84_5",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_84_6",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_84_7",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_84_8",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_84_9",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Craft_PlasticFern",                        Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Company_PlasticFern",                      Format = mod.CreditsFormat.Company },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_PlasticFern1",                        Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_PlasticFern2",                        Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_PlasticFern3",                        Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Craft_Hans",                               Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Hans",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Craft_Xing",                               Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Xing",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Craft_Shaun",                              Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Shaun",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Craft_DavidRosen",                         Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_DavidRosen",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Craft_Confetti",                           Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Company_Confetti",                         Format = mod.CreditsFormat.Company },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Mykhailo",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ajay",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Devansh",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Erfan",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Konstantin",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_DavidErler",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Manas",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Antoine",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Olaf",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_DavidSrour",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Alex",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ethan",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Wolfgang",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },
	},

	Return03 = {
		-- Cast, Abbey Road

		{ PreWait = 1.0 },

		{ CreateScreenObstacle = "EndCreditsVignette",                     X = 0,                            Y = 540,                      SkipScreenAnchors = true },
		{ ScrollOn = true,                                                 ScrollSpeedOverride = 59,         ScrollDistanceOverride = 6080 },

		{ CreditLineBuffer = mod.CreditSpacing.CreditScrollStart },

		{ Text = "InGameCredits_Header_Cast",                              Format = mod.CreditsFormat.Header },

		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferTitle },

		{ Text = "InGameCredits_Cast_Logan",                               Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ CreditLineBuffer = 16 }, -- additional buffer for the paragraph break
		{ Text = "InGameCredits_Name_Logan",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = 16 }, -- additional buffer for the paragraph break
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_Darren",                              Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Darren",                              Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_Avalon",                              Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Avalon",                              Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_Chris",                               Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Chris",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_Marin",                               Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Marin",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_Cyrus",                               Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Cyrus",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_Courtney",                            Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Courtney",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_Jamie",                               Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Jamie",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_Peter",                               Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Peter",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_Laila",                               Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Laila",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_AndrewMarks",                         Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_AndrewMarks",                         Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_Francesca",                           Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Francesca",                           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_Ben",                                 Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ben",                                 Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_Michael",                             Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Michael",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_Greg",                                Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Greg",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_Kelly",                               Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Kelly",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Cast_SoloHiggins",                         Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_SoloHiggins",                         Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ CreditLineBuffer = 80 },

		{ Text = "InGameCredits_Header_MusicProduction",                   Format = mod.CreditsFormat.Header },

		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferTitle },
		{ CreditLineBuffer = 30 },

		{ Text = "InGameCredits_Music_MusicAndLyrics",                     Format = mod.CreditsFormat.Info },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Vocals",                             Format = mod.CreditsFormat.Info },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Mastering",                          Format = mod.CreditsFormat.Info },

		{ CreditLineBuffer = 80 },

		{ Text = "InGameCredits_Music_AbbeyRoad",                          Format = mod.CreditsFormat.Info },

		{ CreditLineBuffer = 80 },

		{ Text = "InGameCredits_Music_Craft_RecordingEngineer",            Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_RecordingEngineer",             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_AssistantEngineer",            Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_AssistantEngineer1",            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_AssistantEngineer2",            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_MusicPrep",                    Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_MusicPrep",                     Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_ScoreEditor",                  Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_ScoreEditor",                   Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_OrchestralMixing",             Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_OrchestralMixing",              Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_Austin",                       Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Austin",                        Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_Flute",                        Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Flute",                         Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_Oboe",                         Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Oboe",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_Clarinet",                     Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Clarinet",                      Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_Trombone",                     Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Trombone1",                     Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Trombone2",                     Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Trombone3",                     Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_Harp",                         Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Harp",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_Percussion",                   Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Percussion1",                   Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Percussion2",                   Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_Violin1",                      Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Violin1",                       Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_Violin2",                      Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Violin2",                       Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_Viola",                        Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Viola",                         Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_Cello",                        Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Cello",                         Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_Bass",                         Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Bass",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_Librarian",                    Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Librarian",                     Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Music_Craft_Reader",                       Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_Reader",                        Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ CreditLineBuffer = 80 },

		{ Text = "InGameCredits_Music_Craft_GuitarSoloists",               Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_GuitarSoloists1",               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Music_Name_GuitarSoloists2",               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

	},

	Return04 = {
		-- Community Moderators, Testers and Translators
		{ PreWait = 1.0 },

		{ CreateScreenObstacle = "EndCreditsVignette",                     X = 0,                                        Y = 540,                        SkipScreenAnchors = true },
		{ ScrollOn = true,                                                 ScrollSpeedOverride = 62,                     ScrollDistanceOverride = 7000 },

		{ CreditLineBuffer = mod.CreditSpacing.CreditScrollStart },

		{ Text = "InGameCredits_Header_Community",                         Format = mod.CreditsFormat.Header },

		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferTitle },

		{ Text = "InGameCredits_Craft_Moderators",                         Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Moderator9",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Moderator5",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Moderator8",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Moderator7",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Moderator10",                         Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Moderator1",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Moderator6",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Moderator2",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Moderator14",                         Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Moderator4",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Moderator3",                          Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Moderator13",                         Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Moderator12",                         Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Moderator11",                         Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },


		{ Text = "InGameCredits_Craft_Translators",                        Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Language_French",                          Format = mod.CreditsFormat.TranslatedLanguage },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_French1",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_French2",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_French3",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Language_Italian",                         Format = mod.CreditsFormat.TranslatedLanguage },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Italian1",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Italian2",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Italian3",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Language_German",                          Format = mod.CreditsFormat.TranslatedLanguage },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_German1",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_German2",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_German3",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_German4",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Language_Spanish",                         Format = mod.CreditsFormat.TranslatedLanguage },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Spanish1",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Spanish2",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Spanish3",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Spanish4",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Language_Russian",                         Format = mod.CreditsFormat.TranslatedLanguage },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Russian1",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Russian2",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Russian3",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Russian4",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Language_Polish",                          Format = mod.CreditsFormat.TranslatedLanguage },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Polish1",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Polish2",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Polish3",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Polish4",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Language_Brazilian_Portuguese",            Format = mod.CreditsFormat.TranslatedLanguage },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_PTBR1",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_PTBR2",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_PTBR3",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_PTBR4",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Language_Chinese",                         Format = mod.CreditsFormat.TranslatedLanguage },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Chinese1",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Chinese2",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Chinese3",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Chinese8",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Chinese4",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Chinese5",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Chinese6",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Chinese7",                            Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Language_Korean",                          Format = mod.CreditsFormat.TranslatedLanguage },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Korean1",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Korean2",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Korean3",                             Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ Text = "InGameCredits_Craft_BetaTesters",                        Format = mod.CreditsFormat.Craft },
		{ CreditLineBuffer = 80 },
		{ Text = "InGameCredits_Name_Tester1",                             X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester2",                             X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester3",                             X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester4",                             X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester5",                             X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester6",                             X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester7",                             X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester8",                             X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester9",                             X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester10",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester11",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester12",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester13",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester14",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester15",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester16",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester17",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester18",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester19",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester20",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester21",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester22",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester23",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester24",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester25",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester26",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester27",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester28",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester29",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester30",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester31",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester32",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester33",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester34",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester35",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester37",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester38",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester39",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester40",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester43",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester42",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester47",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester44",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester45",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester46",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester41",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester48",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester49",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester50",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester51",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester52",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester53",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester54",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Tester55",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Tester56",                            X = mod.CreditSpacing.CColumnLeft,            Format = mod.CreditsFormat.Name },
		{ Text = "InGameCredits_Name_Italian3",                            X = mod.CreditSpacing.CColumnRight,           Format = mod.CreditsFormat.Name },

		{ CreditLineBuffer = 150 },

		{ Text = "InGameCredits_Info_EarlyAccess",                         Format = mod.CreditsFormat.Info },

	},

	Return05 = {
		-- Acknowledgements & Legal & Signoff

		{ CreateScreenObstacle = "EndCreditsVignette",                     X = 0,                            Y = 540,                       SkipScreenAnchors = true },
		{ PreWait = 1.0 },

		{ ScrollOn = true,                                                 ScrollSpeedOverride = 66,         ScrollDistanceOverride = 5080, },

		{ CreditLineBuffer = mod.CreditSpacing.CreditScrollStart },

		{ Text = "InGameCredits_Header_SpecialThanks",                     Format = mod.CreditsFormat.Header },

		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferTitle },

		{ Text = "InGameCredits_Name_ST1",                                 Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST56",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST2",                                 Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST3",                                 Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST40",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST4",                                 Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST53",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST5",                                 Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST45",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST7",                                 Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST8",                                 Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST9",                                 Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST11",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST10",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST12",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST39",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST48",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST13",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST43",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST42",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST14",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST38",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST15",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST34",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST16",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST37",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST55",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST17",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST60",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST18",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST19",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST33",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST52",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST32",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST54",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST46",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST57",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST20",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST47",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST21",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST35",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST22",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST23",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST49",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST51",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST26",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST6",                                 Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST50",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST24",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST25",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST36",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST58",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST44",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST59",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST27",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST28",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST29",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST30",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST41",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_ST31",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferScroll },

		{ CreditLineBuffer = 120 },

		{ Text = "InGameCredits_Header_Acknowledgements",                  Format = mod.CreditsFormat.Header },

		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferTitle },

		{ Text = "InGameCredits_Info_Acknowledgements_Open",               Format = mod.CreditsFormat.Info },
		{ CreditLineBuffer = 80 },

		{ Text = "InGameCredits_Name_Ack1",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack2",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack3",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack4",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack5",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack6",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack7",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack8",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack9",                                Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack10",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack11",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack12",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack13",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack14",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack15",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack16",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack17",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack18",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack19",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack20",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack21",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack22",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack23",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack24",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack25",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack26",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack27",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack28",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack29",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack30",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Name_Ack31",                               Format = mod.CreditsFormat.Name },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },

		{ CreditLineBuffer = 80 },
		{ Text = "InGameCredits_Info_Acknowledgements_Close",              Format = mod.CreditsFormat.Info },

		{ CreditLineBuffer = 220 },
		{ Text = "InGameCredits_Legal_Line1",                              Format = mod.CreditsFormat.Legal },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Legal_Line2",                              Format = mod.CreditsFormat.Legal },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ CreditLineBuffer = 80 },
		{ Text = "InGameCredits_Legal_Line3",                              Format = mod.CreditsFormat.Legal },
		{ CreditLineBuffer = mod.CreditSpacing.CreditLineBufferCraftToName },
		{ Text = "InGameCredits_Legal_Line4",                              Format = mod.CreditsFormat.Legal },

		{ CreditLineBuffer = 220 },
	},

	Return06 = {
		-- Blank
	},
}
