-- Adds enemy sets for the new regions
local additionalEnemySets = {
	-- TARTARUS
	EnemiesBiome1 = {
		"Swarmer",
		"SwarmerElite",
		"LightSpawner",
		"ThiefMineLayer",
		"ThiefMineLayerElite",
		"PunchingBagUnit",
		"HeavyMelee",
		"DisembodiedHand",
		"DisembodiedHandElite",
		"LightRanged",
		"HeavyRanged",
		"HeavyMeleeElite",
		"LightRangedElite",
		"PunchingBagUnitElite",
		"HeavyRangedElite",
	},
	EnemiesBiome1Devotion = {
		"HeavyMeleeElite",
		"LightRangedElite",
		"PunchingBagUnitElite",
		"HeavyRangedElite",
	},
	EnemiesBiome1Survival = {
		"Swarmer",
		"SwarmerElite",
		"LightSpawner",
		"ThiefMineLayer",
		"ThiefMineLayerElite",
		"PunchingBagUnit",
		"HeavyMelee",
		"LightRanged",
		"HeavyRanged",
		"HeavyMeleeElite",
		"LightRangedElite",
		"PunchingBagUnitElite",
		"HeavyRangedElite",
	},
	EnemiesBiome1Hard = {
		"SwarmerElite",
		"HeavyMeleeElite",
		"LightRangedElite",
		"ThiefMineLayerElite",
		"PunchingBagUnitElite",
		"HeavyRangedElite",
	},
	EnemiesBiome1Thanatos = {
		"SwarmerElite",
		"PunchingBagUnit",
		"HeavyMelee",
		"HeavyRanged",

		"HeavyMeleeElite",
		"LightRangedElite",
		"ThiefMineLayerElite",
		"PunchingBagUnitElite",
		"HeavyRangedElite",
	},
	EnemiesBiome1_EliteChallenge = {
		"HeavyMeleeElite",
		"PunchingBagUnitElite",
	},
	EnemiesBiome1MiniBoss = {
		"BloodlessGrenadierElite",
		"BloodlessSelfDestructElite",
		"BloodlessPitcherElite",
	},
	-- ASPHODEL
	EnemiesBiome2 = {
		"CrusherUnit",
		"LightSpawnerElite",
		"BloodlessNaked",
		"BloodlessNakedElite",
		"BloodlessNakedBerserker",
		"BloodlessNakedBerserkerElite",
		"BloodlessGrenadier",
		"BloodlessGrenadierElite",
		"BloodlessSelfDestruct",
		"BloodlessSelfDestructElite",
		"BloodlessPitcher",
		"BloodlessPitcherElite",
		"BloodlessWaveFist",
		"BloodlessWaveFistElite",
		"SpreadShotUnit",
		"SpreadShotUnitElite",
		"FreezeShotUnit",
		"FreezeShotUnitElite",
		"RangedBurrower",
		"RangedBurrowerElite",
	},
	-- TimeChallenge
	EnemiesBiome2Challenge = {
		"LightSpawnerElite",
		"BloodlessNaked",
		"BloodlessNaked",
		"BloodlessNakedElite",
		"BloodlessNakedBerserkerElite",
		"BloodlessGrenadier",
		"BloodlessGrenadierElite",
		"BloodlessSelfDestruct",
		"BloodlessSelfDestructElite",
		"BloodlessPitcher",
		"BloodlessPitcherElite",
		"BloodlessWaveFist",
		"BloodlessWaveFistElite",
		"HeavyRangedElite",
		"SpreadShotUnit",
		"SpreadShotUnitElite",
		"FreezeShotUnit",
		"FreezeShotUnitElite",
		"RangedBurrower",
		"RangedBurrowerElite",
	},
	EnemiesBiome2Thanatos = {
		"CrusherUnit",
		"BloodlessNaked",
		"BloodlessNakedElite",
		"BloodlessNakedBerserker",
		"BloodlessNakedBerserkerElite",
		"BloodlessGrenadier",
		"BloodlessSelfDestruct",
		"BloodlessSelfDestructElite",
		"BloodlessPitcher",
		"BloodlessWaveFist",
		"BloodlessWaveFistElite",
		"SpreadShotUnit",
		"SpreadShotUnitElite",
		"FreezeShotUnit",
		"RangedBurrower",
		"RangedBurrowerElite",
	},
	EnemiesBiome2_EliteChallenge = {
		"BloodlessSelfDestructElite",
		"BloodlessNakedBerserkerElite",
		"BloodlessSelfDestructElite",
		"BloodlessPitcherElite",
		"BloodlessWaveFistElite",
	},
	EnemiesBiome2Wrapping = {
		"BloodlessNakedElite",
		"BloodlessGrenadierElite",
		"BloodlessSelfDestructElite",
		"BloodlessPitcherElite",
		"BloodlessWaveFistElite",
		-- ShieldRanged, -- Added through the encounter directly for each wave
	},
	EnemiesBiome2Devotion = {
		"SpreadShotUnitElite",
		"FreezeShotUnitElite",
		"BloodlessNakedElite",
		"BloodlessNakedBerserkerElite",
		"BloodlessGrenadierElite",
		"BloodlessSelfDestructElite",
		"BloodlessPitcherElite",
		"BloodlessWaveFistElite",
		"RangedBurrowerElite",
		-- Multiplying to favour elite enemies when available
		"SpreadShotUnitElite",
		"FreezeShotUnitElite",
		"BloodlessNakedElite",
		"BloodlessNakedBerserkerElite",
		"BloodlessGrenadierElite",
		"BloodlessSelfDestructElite",
		"BloodlessPitcherElite",
		"BloodlessWaveFistElite",
		"RangedBurrowerElite",
		"SpreadShotUnitElite",
		"FreezeShotUnitElite",
		"BloodlessNakedElite",
		"BloodlessNakedBerserkerElite",
		"BloodlessGrenadierElite",
		"BloodlessSelfDestructElite",
		"BloodlessPitcherElite",
		"BloodlessWaveFistElite",
		"RangedBurrowerElite",
		"SpreadShotUnitElite",
		"FreezeShotUnitElite",
		"BloodlessNakedElite",
		"BloodlessNakedBerserkerElite",
		"BloodlessGrenadierElite",
		"BloodlessSelfDestructElite",
		"BloodlessPitcherElite",
		"BloodlessWaveFistElite",
		"RangedBurrowerElite",
		-- Need to add some non-elite enemies, to ensure there are always valid enemies available
		"SpreadShotUnit",
		"RangedBurrower",
		"BloodlessPitcher",
		"BloodlessWaveFist",
	},
	EnemiesBiome2Hard = {
		"SpreadShotUnitElite",
		"LightSpawnerElite",
		"FreezeShotUnitElite",
		"CrusherUnit",
		"BloodlessNakedElite",
		"BloodlessNakedBerserkerElite",
		"BloodlessGrenadierElite",
		"BloodlessSelfDestructElite",
		"BloodlessPitcherElite",
		"BloodlessWaveFistElite",
		"RangedBurrowerElite",
	},
	HydraHeads = {
		"HydraHeadDartmaker",
		"HydraHeadLavamaker",
		"HydraHeadSummoner",
		"HydraHeadSlammer",
		"HydraHeadWavemaker",
	},
	-- ELYSIUM
	EnemiesBiome3 = {
		"ShadeSpearUnit",
		"ShadeSpearUnitElite",
		"ShadeBowUnit",
		"ShadeBowUnitElite",
		"ShadeShieldUnit",
		"ShadeShieldUnitElite",
		"ShadeSwordUnit",
		"ShadeSwordUnitElite",

		"ShieldRangedElite",
		"ShieldRangedElite",

		"SplitShotUnit",
		"SplitShotUnitElite",
		"Chariot",
		"ChariotElite",
		"ChariotSuicide",
		"ChariotSuicideElite",
		"FlurrySpawner",
		"FlurrySpawner",
	},
	EnemiesBiome3Survival = {
		"ShadeSpearUnit",
		"ShadeSpearUnitElite",
		"ShadeBowUnit",
		"ShadeBowUnitElite",
		"ShadeShieldUnit",
		"ShadeShieldUnitElite",
		"ShadeSwordUnit",
		"ShadeSwordUnitElite",

		"SplitShotUnit",
		"SplitShotUnitElite",
		"Chariot",
		"ChariotElite",
	},
	EnemiesBiome3Hard = {
		"ShieldRangedElite",
		"ShadeSpearUnitElite",
		"ShadeBowUnitElite",
		"ShadeShieldUnitElite",
		"ShadeSwordUnitElite",
		"SplitShotUnitElite",
		"ChariotElite",
	},
	EnemiesBiome3Devotion = {
		"ShieldRangedElite",
		"ShadeSpearUnitElite",
		"ShadeBowUnitElite",
		"ShadeShieldUnitElite",
		"ShadeSwordUnitElite",
		"SplitShotUnitElite",
		"ChariotElite",
	},
	-- STYX
	-- Decides which traps can be added to rooms that randomize traps
	TrapsBiome1 = { "SpikeTrap", },
	TrapsBiome2 = { "GasTrapPassive", },
}

table.insert(game.EnemySets.GenericEliteAttributes, "ModsNikkelMHadesBiomesStasisDeath")

for oldName, newName in pairs(mod.EnemyNameMappings) do
	mod.UpdateField(additionalEnemySets, oldName, newName, {}, "EnemySets.lua")
end

-- Adds the new enemy sets to the game
for setName, setData in pairs(additionalEnemySets) do
	if not game.EnemySets[setName] then
		game.EnemySets[setName] = setData
	end
end
