-- #region Textline groups for requirements
local newGameDataTables = {
	GodAboutGodVoiceLines = {
		"ZeusAboutPoseidon01",
		"ZeusAboutAthena01",
		"ZeusAboutAphrodite01",
		"ZeusAboutArtemis01",
		"ZeusAboutAres01",
		"ZeusAboutDionysus01",
		"ZeusAboutHermes01",
		"ZeusAboutDemeter03",
		"ZeusAboutDemeter01",
		"ZeusAboutDemeter02",

		"PoseidonAboutZeus01",
		"PoseidonAboutAthena01",
		"PoseidonAboutAphrodite01",
		"PoseidonAboutAres01",
		"PoseidonAboutArtemis01",
		"PoseidonAboutDionysus01",
		"PoseidonAboutHermes01",
		"PoseidonAboutHermes02",
		"PoseidonAboutDemeter01",

		"AthenaAboutZeus01",
		"AthenaAboutPoseidon01",
		"AthenaAboutAphrodite01",
		"AthenaAboutAres01",
		"AthenaAboutArtemis01",
		"AthenaAboutDionysus01",
		"AthenaAboutHermes01",
		"AthenaAboutDemeter01",

		"AphroditeAboutZeus01",
		"AphroditeAboutPoseidon01",
		"AphroditeAboutAthena01",
		"AphroditeAboutAres01",
		"AphroditeAboutArtemis01",
		"AphroditeAboutDionysus01",
		"AphroditeAboutDemeter01",

		"AresAboutZeus01",
		"AresAboutPoseidon01",
		"AresAboutAthena01",
		"AresAboutAphrodite01",
		"AresAboutArtemis01",
		"AresAboutDionysus01",
		"AresAboutHermes01",
		"AresAboutDemeter01",

		"ArtemisAboutZeus01",
		"ArtemisAboutPoseidon01",
		"ArtemisAboutAthena01",
		"ArtemisAboutAres01",
		"ArtemisAboutAphrodite01",
		"ArtemisAboutDionysus01",
		"ArtemisAboutDemeter01",

		"DionysusAboutZeus01",
		"DionysusAboutPoseidon01",
		"DionysusAboutAthena01",
		"DionysusAboutAphrodite01",
		"DionysusAboutArtemis01",
		"DionysusAboutAres01",
		"DionysusAboutDemeter01",

		"DemeterAboutZeus01",
		"DemeterAboutPoseidon01",
		"DemeterAboutAthena01",
		"DemeterAboutAphrodite01",
		"DemeterAboutAres01",
		"DemeterAboutArtemis01",
		"DemeterAboutDionysus01",

		"AthenaAboutHadesKeepsake01",
		"AthenaAboutHadesKeepsake02",
		"AresAboutHadesKeepsake01",
		"DionysusAboutHadesKeepsake01",
		"HermesAboutHadesKeepsake01",
	},
	AresAboutNyxTextLines = {
		"AresGift01",
		"NyxGift01",
		"AresAboutNyxIntro01",
		"AresAboutNyx01",
		"AresAboutNyx01_B",
		"AresAboutNyx02",
		"AresAboutNyx02_B",
		"AresAboutNyx03",
		"AresAboutNyx03_B",
		"AresAboutNyx04",
		"AresAboutNyx04_B",
		"AresAboutNyx05",
		"AresAboutNyx05_B",
		"AresAboutNyx06",
		"AresAboutNyx06_B",
	},
	AresBasicPickUpTextLines = {
		"AresFirstPickUp",
		"AresMiscPickup01",
		"AresMiscPickup02",
		"AresMiscPickup03",
		"AresMiscPickup04",
		"AresMiscPickup05",
		"AresMiscPickup06",
		"AresMiscPickup07",
		"AresMiscPickup08",
		"AresMiscPickup09",
		"AresMiscPickup10",
		"AresMiscPickup11",
		"AresMiscPickup12",
		"AresMiscPickup13",
		"AresMiscPickup14",
		"AresMiscPickup15",
		"AresMiscPickup16",
		"AresMiscPickup17",
	},
	ArtemisAboutCallistoTextLines = {
		"ArtemisAboutCallisto01",
		"ArtemisAboutCallisto02",
		"ArtemisAboutCallisto03",
		"ArtemisAboutCallisto04",
		"ArtemisAboutCallisto05",
		"ArtemisAboutCallisto06",
	},
	AthenaBasicPickUpTextLines = {
		"AthenaFirstPickUp",
		"AthenaMiscPickup02",
		"AthenaMiscPickup03",
		"AthenaMiscPickup04",
		"AthenaMiscPickup05",
		"AthenaMiscPickup07",
		"AthenaMiscPickup08",
		"AthenaMiscPickup09",
		"AthenaMiscPickup14",
		"AthenaMiscPickup15",
		"AthenaMiscPickup17",
		"AthenaMiscPickup18",
		"AthenaMiscPickup19",
		"AthenaMiscPickup20",
	},
	ZeusBasicPickUpTextLines = {
		"ZeusFirstPickUp",
		"ZeusMiscPickup02",
		"ZeusMiscPickup03",
		"ZeusMiscPickup05",
		"ZeusMiscPickup07",
		"ZeusMiscPickup09",
		"ZeusMiscPickup11",
		"ZeusMiscPickup12",
		"ZeusMiscPickup14",
		"ZeusMiscPickup16",
		"ZeusMiscPickup17",
		"ZeusMiscPickup18",
		"ZeusMiscPickup20",
		"ZeusMiscPickup25",
		"ZeusMiscPickup26",
		"ZeusMiscPickup27",
	},
	HermesBasicPickUpTextLines = {
		"HermesFirstPickUp",
		"HermesMiscPickup01",
		"HermesMiscPickup02",
		"HermesMiscPickup03",
		"HermesMiscPickup04",
		"HermesMiscPickup05",
		"HermesMiscPickup06",
		"HermesMiscPickup07",
		"HermesMiscPickup08",
		"HermesMiscPickup09",
		"HermesMiscPickup10",
		"HermesMiscPickup11",
		"HermesMiscPickup12",
		"HermesMiscPickup13",
		"HermesMiscPickup14",
		"HermesMiscPickup15",
		"HermesMiscPickup16",
		"HermesMiscPickup17",
		"HermesMiscPickup18",
		"HermesMiscPickup19",
		"HermesMiscPickupExtra01",
		"HermesMiscPickupExtra02",
	},
}

-- Deduplicate any TextLineSet names shared between the games
for groupName, textLines in pairs(newGameDataTables) do
	for i, textLineName in ipairs(textLines) do
		textLines[i] = mod.MapDuplicateTextLineName(textLineName)
	end
	if game.GameData[groupName] ~= nil then
		mod.DebugPrint("GameData group already exists: " .. groupName, 1)
	else
		game.GameData[groupName] = textLines
	end
end
--#endregion

-- Ensures that conversations for these are loaded when entering the room
local hadesNPCNames = {
	"NPC_Sisyphus_01",
	"NPC_Orpheus_01",
	"NPC_Orpheus_Story_01",
	"NPC_Eurydice_01",
	"NPC_Patroclus_01",
	"NPC_Thanatos_01",
	"NPC_FurySister_01",
	-- "NPC_Achilles_01",
	-- "NPC_Dusa_01",
	"ModsNikkelMHadesBiomes_NPC_Bouldy_01",
	"ModsNikkelMHadesBiomes_NPC_Cerberus_Field_01",
	"ModsNikkelMHadesBiomes_NPC_Persephone_01",
}
game.NarrativeData.ConversationOrder = game.CombineTables(game.NarrativeData.ConversationOrder, hadesNPCNames)

-- Gifting
local hadesNPCGiftLinePriorities = {
	NPC_Sisyphus_01 = {
		"SisyphusGift01",
		"SisyphusGift02",
		"SisyphusGift03",
		"SisyphusGift04",
		"SisyphusGift05",
		"SisyphusGift06",
		"SisyphusGift07_A",
		-- "SisyphusGift08_A", -- If you haven't had Ambrosia with others - would be very rare, so we just exclude it
		"SisyphusGift08_B",
		"SisyphusGift09_A",
	},
	NPC_Orpheus_01 = {
		"OrpheusGift01",
		"OrpheusGift02",
		"OrpheusGift03",
		"OrpheusGift04",
		"OrpheusGift04_B",
		"OrpheusGift05",
		"OrpheusGift06",
		"OrpheusGift07",
		"OrpheusGift08",
	},
	NPC_Eurydice_01 = {
		"EurydiceGift01",
		"EurydiceGift02",
		"EurydiceGift03",
		"EurydiceGift04",
		"EurydiceGift05",
		"EurydiceGift06",
		"EurydiceGift07",
		"EurydiceGift08",
	},
	NPC_Patroclus_01 = {
		"PatroclusGift01",
		"PatroclusGift02",
		"PatroclusGift03",
		"PatroclusGift04",
		"PatroclusGift05",
		"PatroclusGift06",
		"PatroclusGift07_A",
		"PatroclusGift08_A"
	},
	NPC_Thanatos_01 = {
		"ThanatosGift01",
		"ThanatosGift02",
		"ThanatosGift03",
		"ThanatosGift04",
		"ThanatosGift04_B",
		"ThanatosGift05",
		"ThanatosGift06",
		"ThanatosGift07_A",
		"ThanatosGift08",
		"ThanatosGift09",
		"ThanatosGift10",
	},
	NPC_FurySister_01 = {
		"MegaeraGift01",
		"MegaeraGift02",
		"MegaeraGift03",
		"MegaeraGift04",
		"MegaeraGift05",
		"MegaeraGift06",
		"MegaeraGift07",
		"MegaeraGift08",
		"MegaeraGift09",
		"MegaeraGift10",
	},
	-- NPC_Achilles_01 = {},
	-- NPC_Dusa_01 = {},
	-- TODO When Hypnos is added, port his gift textline priorities here since we will reimplement his gifting
}
-- Create dummy entries to allow the relationship bar to be built in the Codex
for _, npcName in ipairs(hadesNPCNames) do
	game.NarrativeData[npcName] = {
		GiftTextLinePriorities = hadesNPCGiftLinePriorities[npcName] or {},
	}
end

-- Events
local newGameData = {
	BouldyRepeatableTextLines = {
		"BouldyGiftRepeatable01",
		"BouldyGiftRepeatable02",
		"BouldyGiftRepeatable03",
		"BouldyGiftRepeatable04",
		"BouldyGiftRepeatable05",
		"BouldyGiftRepeatable06",
		"BouldyGiftRepeatable07",
		"BouldyGiftRepeatable08",
		"BouldyGiftRepeatable09",
		"BouldyGiftRepeatable10",
		"BouldyGiftRepeatable11",
		"BouldyGiftRepeatable12",
		"BouldyGiftRepeatable13",
		"BouldyGiftRepeatable14",
		"BouldyGiftRepeatable15",
		"BouldyGiftRepeatable16",
		"BouldyGiftRepeatable17",
		"BouldyGiftRepeatable18",
		"BouldyGiftRepeatable19",
	},
	GardenTextLines = {
		"PersephoneHomeMeeting03",
		"PersephoneHomeMeeting04",
		"PersephoneHomeMeeting06",
		"PersephoneChat13",
		"PersephoneChat17",
		"PersephoneWithHades01",
		"PersephoneWithHades03",
		"PersephoneWithHades04",
		"PersephoneChatWithHades01",
		"PersephoneChatWithHades07",
		"PersephoneChatWithHades08",
	},
	HadesGardenTextLines = {
		"PersephoneWithHades01",
		"PersephoneWithHades03",
		"PersephoneWithHades04",
		"PersephoneChatWithHades01",
		"PersephoneChatWithHades07",
		"PersephoneChatWithHades08",
	},
	OrpheusWithEurydiceTextLines = {
		"OrpheusWithEurydice01",
		"OrpheusWithEurydice02",
		"OrpheusWithEurydice03",
		"OrpheusWithEurydiceMiscChat01",
		"OrpheusWithEurydiceMiscChat02",
		"OrpheusWithEurydiceMiscChat03",
		"OrpheusWithEurydiceMiscChat04",
		"OrpheusWithEurydiceMiscChat05",
		"OrpheusWithEurydiceMiscChat06",
		"OrpheusWithEurydiceMiscChat07",
		"OrpheusWithEurydiceMiscChat08",
		"OrpheusWithEurydiceMiscChat09",
		"OrpheusWithEurydiceMiscChat10",
		"OrpheusWithEurydiceMiscChat11",
		"OrpheusWithEurydiceMiscChat12",
		"OrpheusWithEurydiceMiscChat13",
		"OrpheusWithEurydiceMiscChat14",
		"OrpheusWithEurydiceMiscChat15",
		"OrpheusWithEurydiceMiscChat16",
		"OrpheusWithEurydiceMiscChat17",
		"OrpheusWithEurydiceMiscChat18",
		"OrpheusWithEurydiceMiscChat19",
		"OrpheusWithEurydiceMiscChat20",
		"OrpheusWithEurydiceMiscChat21",
		"OrpheusWithEurydiceMiscChat22",
		"OrpheusWithEurydiceMiscChat23",
		"OrpheusWithEurydiceMiscChat24",
		"OrpheusWithEurydiceMiscChat25",
		"OrpheusWithEurydiceInTheBloodChat01",
		"OrpheusWithEurydiceInTheBloodChat02",
		"OrpheusWithEurydiceInTheBloodChat03",
		"OrpheusWithEurydiceInTheBloodChat04",
		"OrpheusWithEurydiceInTheBloodChat05",
		"OrpheusWithEurydiceInTheBloodChat06",
		"OrpheusWithEurydiceInTheBloodChat07",
	},
	OrpheusWithEurydiceAltTextLines = {
		"Inspect_DeathAreaOffice_SealedContract_02",
		"OrpheusWithEurydice01",
		"OrpheusWithEurydice02",
		"OrpheusWithEurydice03",
		"OrpheusWithEurydiceMiscChat01",
		"OrpheusWithEurydiceMiscChat02",
		"OrpheusWithEurydiceMiscChat03",
		"OrpheusWithEurydiceMiscChat04",
		"OrpheusWithEurydiceMiscChat05",
		"OrpheusWithEurydiceMiscChat06",
		"OrpheusWithEurydiceMiscChat07",
		"OrpheusWithEurydiceMiscChat08",
		"OrpheusWithEurydiceMiscChat09",
		"OrpheusWithEurydiceMiscChat10",
		"OrpheusWithEurydiceMiscChat11",
		"OrpheusWithEurydiceMiscChat12",
		"OrpheusWithEurydiceMiscChat13",
		"OrpheusWithEurydiceMiscChat14",
		"OrpheusWithEurydiceMiscChat15",
		"OrpheusWithEurydiceMiscChat16",
		"OrpheusWithEurydiceMiscChat17",
		"OrpheusWithEurydiceMiscChat18",
		"OrpheusWithEurydiceMiscChat19",
		"OrpheusWithEurydiceMiscChat20",
		"OrpheusWithEurydiceMiscChat21",
		"OrpheusWithEurydiceMiscChat22",
		"OrpheusWithEurydiceMiscChat23",
		"OrpheusWithEurydiceMiscChat24",
		"OrpheusWithEurydiceMiscChat25",
		"OrpheusWithEurydiceInTheBloodChat01",
		"OrpheusWithEurydiceInTheBloodChat02",
		"OrpheusWithEurydiceInTheBloodChat03",
		"OrpheusWithEurydiceInTheBloodChat04",
		"OrpheusWithEurydiceInTheBloodChat05",
		"OrpheusWithEurydiceInTheBloodChat06",
		"OrpheusWithEurydiceInTheBloodChat07",
	},
	MegThanIntermissionTextLines = {
		"BecameCloseWithMegaera01Meg_GoToHer",
		"BecameCloseWithMegaera01_BMeg_GoToHer",
		"BecameCloseWithThanatos01Than_GoToHim",
		"BecameCloseWithThanatos01_BThan_GoToHim",
		"MegaeraWithThanatosBedroom01",
		"ThanatosHomeIntermissionChat01",
		"ThanatosHomeIntermissionChat02",
		"ThanatosHomeIntermissionChat03",
		"ThanatosHomeIntermissionChat04",
		"ThanatosHomeIntermissionChat05",
		"ThanatosHomeIntermissionChat06",
		"MegIntermissionChat01",
		"MegIntermissionChat02",
		"MegIntermissionChat03",
		"MegIntermissionChat04",
		"MegIntermissionChat05",
		"MegIntermissionChat06",
	},
	AchillesWithPatroclusTextLines = {
		"PatroclusWithAchilles01",
		"PatroclusWithAchilles02",
		"PatroclusWithAchilles03",
		"PatroclusReunionChat02",
		"PatroclusReunionChat05",
		"PatroclusReunionChat06",
		"PatroclusReunionChat07",
		"PatroclusReunionChat11",
		"PatroclusReunionChat12",
	},
	EndingTextLines = {
		"PersephoneFirstMeeting",
		"PersephoneMeeting02",
		"PersephoneMeeting03",
		"PersephoneMeeting04",
		"PersephoneMeeting05_A",
		"PersephoneMeeting05_B",
		"PersephoneMeeting06",
		"PersephoneMeeting07",
		"PersephoneMeeting08",
		"PersephoneMeeting09",
		"PersephoneReturnsHome01",
		"OlympianReunionQuestComplete",
	},
}
for property, textLines in pairs(newGameData) do
	if game.GameData[property] == nil then
		game.GameData[property] = textLines
	else
		mod.DebugPrint("GameData property " .. property .. " already exists, not overwriting", 2)
	end
end

-- GameData changes for randomized Chaos Trials/Bounties
game.GameData.AllRandomPackagedBounties = game.ConcatTableValuesIPairs(
	game.GameData.AllRandomPackagedBounties, mod.RandomizedChaosTrialBountyNames)
