-- Map conversation animations for Zagreus to animations that exist for Melinoe

local animationsFile = rom.path.combine(rom.paths.Content(),
	"Game/Animations/Model/Hero_Melinoe_Animation_Personality.sjson")

local order = {
	"Name",
	"InheritFrom",
}

local newData = {
	-- #region REPLACEMENTS
	{
		Name = "ZagreusTalkEmpathyStart",
		InheritFrom = "MelTalkExplaining01",
	},
	{
		Name = "ZagreusTalkEmpathy_Return",
		InheritFrom = "MelTalkExplaining01ReturnToIdle",
	},
	{
		Name = "ZagreusTalkDenialStart",
		InheritFrom = "MelTalkBrooding01",
	},
	{
		Name = "ZagreusTalkDenial_Full",
		InheritFrom = "MelTalkBroodingFull01",
	},
	{
		Name = "ZagreusTalkDenialReturnToIdle",
		InheritFrom = "MelTalkBrooding01ReturnToIdle",
	},
	{
		Name = "ZagreusInteractionThoughtful",
		InheritFrom = "MelTalkBrooding01",
	},
	{
		Name = "ZagreusInteractEquip",
		InheritFrom = "MelTalkGifting01",
		HoldLastFrame = false,
		ChainTo = "MelTalkGifting01ReturnToIdle"
	},
	{
		Name = "ZagreusInteractionComeHither_Start",
		InheritFrom = "Melinoe_Hug_Start",
	},
	{
		Name = "ZagreusInteractionComeHither_Hold",
		InheritFrom = "Melinoe_Hug_FireLoop",
	},
	{
		Name = "ZagreusInteractionComeHither_End",
		InheritFrom = "Melinoe_Hug_End",
	},
	{
		Name = "ZagreusInjured_IdleToSick",
		InheritFrom = "MelinoeIdleWeaponless",
	},
	-- #endregion

	-- #region ACTUAL ZAGREUS
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusIdle",
		FilePath = "Animations\\Zagreus\\Idle\\ZagreusIdle",
		Type = "Book",
		VideoTexture = "ZagreusIdle_Bink",
		EndFrame = 120,
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusIdle.sga",
		Loop = true,
		NumAngles = 32,
		NumFrames = 120,
		StartFrame = 1,
		OffsetY = -105.0,
		SetOwnerEndAngle = true,
		Scale = 1.05,
		CancelOnOwnerMove = true,
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusStart",
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusRun",
		FilePath = "Animations\\Zagreus\\Start\\ZagreusStart",
		Type = "Slide",
		VideoTexture = "ZagreusStart_Bink",
		EndFrame = 32,
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusStart.sga",
		NumAngles = 64,
		NumFrames = 32,
		StartFrame = 1,
		OffsetY = -105.0,
		Scale = 1.05,
		NativeMoveSpeed = 540.0,
		SoundManagerCap = 16,
		Slides = {
			-- TODO: For all animations, update the frame where the footsteps spawn
			{ DurationFrames = 1 },
			{ DurationFrames = 1, FootstepFxR = "FireFootstepR-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurface" },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1, FootstepFxL = "FireFootstepL-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurface" },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
		},
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusRun",
		FilePath = "Animations\\Zagreus\\Run\\ZagreusRun",
		Type = "Book",
		VideoTexture = "ZagreusRun_Bink",
		EndFrame = 32,
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusRun.sga",
		Loop = true,
		NumAngles = 64,
		NumFrames = 32,
		PlaySpeed = 60.0,
		StartFrame = 1,
		OffsetY = -105.0,
		Scale = 1.05,
		NativeMoveSpeed = 540.0,
		SoundManagerCap = 16,
		Slides = {
			{ DurationFrames = 1, FootstepFxR = "FireFootstepR-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurfaceRun", Frame = 1 },
			{ DurationFrames = 1, FootstepFxL = "FireFootstepL-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurfaceRun", Frame = 16 },
		},
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusStop",
		FilePath = "Animations\\Zagreus\\Stop\\ZagreusStop",
		Type = "Slide",
		VideoTexture = "ZagreusStop_Bink",
		EndFrame = 32,
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusStop.sga",
		NumAngles = 32,
		NumFrames = 32,
		StartFrame = 1,
		OffsetY = -105.0,
		Scale = 1.05,
		CancelOnOwnerMove = true,
		SoundManagerCap = 16,
		Slides = {

			{ DurationFrames = 0 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1, FootstepSound = "/SFX/Player Sounds/FootstepsHardSurface" },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
		},
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusWalk2",
		FilePath = "Animations\\Zagreus\\Walk2\\ZagreusWalk",
		StopAnimation = "ModsNikkelMHadesBiomes_ZagreusWalkStop2",
		Type = "Slide",
		VideoTexture = "ZagreusWalk2_Bink",
		EndFrame = 60,
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusWalk2.sga",
		Loop = true,
		NumAngles = 32,
		NumFrames = 60,
		StartFrame = 1,
		OffsetY = -105.0,
		Scale = 1.05,
		SoundManagerCap = 16,
		Slides = {
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1, FootstepFxL = "FireFootstepL-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurfaceRun", },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1, FootstepFxR = "FireFootstepR-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurfaceRun" },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
		},
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusWalkStop2",
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusIdle",
		FilePath = "Animations\\Zagreus\\WalkStop2\\ZagreusWalkStop2",
		Type = "Slide",
		VideoTexture = "ZagreusWalkStop2_Bink",
		EndFrame = 60,
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusWalkStop.sga",
		NumAngles = 32,
		NumFrames = 60,
		StartFrame = 1,
		OffsetY = -105.0,
		SetOwnerEndAngle = true,
		Scale = 1.05,
		CancelOnOwnerMove = true,
		Slides = {

			{ DurationFrames = 1, FootstepFxL = "FireFootstepL-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurfaceRun" },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1, FootstepFxR = "FireFootstepR-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurfaceRun" },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
		},
	},
	-- {
	-- 	Name = "ZagreusDeathFullscreen",
	-- 	FilePath = "Screens\\ZagreusDeadPool\\ZagreusDeadPool",
	-- 	GroupName = "Overlay",
	-- 	Type = "Book",
	-- 	VideoTexture = "ZagreusDeathFullscreen",
	-- 	AngleFromOwner = "Ignore",
	-- 	Sound = "/SFX/Player Sounds/PlayerDeathBloodComponents",
	-- 	EndFrame = 250,
	-- 	HoldLastFrame = true,
	-- 	NumFrames = 250,
	-- 	PlaySpeed = 30.0,
	-- 	StartFrame = 1,
	-- 	Material = "Unlit",
	-- 	DisableOwnerInteract = true,
	-- 	TimeModifierFraction = 0.1,
	-- 	Slides = {
	-- 		{ DurationFrames = 1, Sound = "/SFX/StabSplatter", Frame = 1, },
	-- 	},
	-- },
	-- #endregion
}

sjson.hook(animationsFile, function(data)
	for _, newValue in ipairs(newData) do
		table.insert(data.Animations, sjson.to_object(newValue, order))
	end
end)
