-- Map conversation animations for Zagreus to animations that exist for Melinoe

local animationsFile = rom.path.combine(rom.paths.Content(),
	"Game/Animations/Model/Hero_Melinoe_Animation_Personality.sjson")

local order = {
	"Name",
	"InheritFrom",
}

local newData = {
	-- #region REPLACEMENTS
	{
		Name = "ZagreusTalkEmpathyStart",
		InheritFrom = "MelTalkExplaining01",
	},
	{
		Name = "ZagreusTalkEmpathy_Return",
		InheritFrom = "MelTalkExplaining01ReturnToIdle",
	},
	{
		Name = "ZagreusTalkDenialStart",
		InheritFrom = "MelTalkBrooding01",
	},
	{
		Name = "ZagreusTalkDenial_Full",
		InheritFrom = "MelTalkBroodingFull01",
	},
	{
		Name = "ZagreusTalkDenialReturnToIdle",
		InheritFrom = "MelTalkBrooding01ReturnToIdle",
	},
	{
		Name = "ZagreusInteractionThoughtful",
		InheritFrom = "MelTalkBrooding01",
	},
	{
		Name = "ZagreusInteractEquip",
		InheritFrom = "MelTalkGifting01",
		HoldLastFrame = false,
		ChainTo = "MelTalkGifting01ReturnToIdle"
	},
	-- #endregion

	-- For the Surface dialogues only, easier to use SwapAnimations there
	-- #region TalkEmpathy
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusTalkEmpathy",
		FilePath = "Animations\\Zagreus\\TalkEmpathy\\ZagreusTalkEmpathy",
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusInteractionEmpathy.sga",
		VideoTexture = "ZagreusTalkEmpathy_Bink",
		EndFrame = 200,
		NumAngles = 8,
		NumFrames = 200,
		StartFrame = 1,
		OffsetY = -105.0,
		SetOwnerEndAngle = true,
		Scale = 1.05,
		CancelOnOwnerMove = true,
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusTalkEmpathyStart",
		InheritFrom = "ModsNikkelMHadesBiomes_ZagreusTalkEmpathy",
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusTalkEmpathyLoop",
		EndFrame = 110,
		NumFrames = 200,
		StartFrame = 1,
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusTalkEmpathyLoop",
		InheritFrom = "ModsNikkelMHadesBiomes_ZagreusTalkEmpathy",
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusTalkEmpathy_Return",
		EndFrame = 160,
		Loop = true,
		NumFrames = 200,
		StartFrame = 111,
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusTalkEmpathy_Return",
		InheritFrom = "ModsNikkelMHadesBiomes_ZagreusTalkEmpathy",
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusIdle",
		EndFrame = 200,
		NumFrames = 200,
		StartFrame = 160,
	},
	-- #endregion

	-- #region TalkDenial
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusTalkDenial",
		FilePath = "Animations\\Zagreus\\TalkDenial\\ZagreusTalkDenial",
		VideoTexture = "ZagreusTalkDenial_Bink",
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusInteractionTalk.sga",
		EndFrame = 355,
		NumAngles = 8,
		NumFrames = 355,
		PlaySpeed = 60.0,
		StartFrame = 1,
		OffsetY = -105.0,
		SetOwnerEndAngle = true,
		TransferFrameFromThis = true,
		Scale = 1.05,
		CancelOnOwnerMove = true,
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusTalkDenialStart",
		InheritFrom = "ModsNikkelMHadesBiomes_ZagreusTalkDenial",
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusTalkDenial_Loop1",
		EndFrame = 30,
		NumFrames = 355,
		StartFrame = 1,
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusTalkDenial_Loop1",
		InheritFrom = "ModsNikkelMHadesBiomes_ZagreusTalkDenial",
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusTalkDenial_WeightShift",
		EndFrame = 90,
		Loop = true,
		NumFrames = 355,
		StartFrame = 31,
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusTalkDenial_Loop_Full",
		InheritFrom = "ModsNikkelMHadesBiomes_ZagreusTalkDenial_Loop1",
		Loop = false,
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusTalkDenialReturnToIdle",
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusTalkDenialReturnToIdle",
		InheritFrom = "ModsNikkelMHadesBiomes_ZagreusTalkDenialStart",
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusIdle",
		EndFrame = 30,
		NumFrames = 355,
		PlayBackwards = true,
		StartFrame = 1,
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusTalkDenial_WeightShift",
		InheritFrom = "ModsNikkelMHadesBiomes_ZagreusTalkDenial",
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusTalkDenial_Loop2",
		EndFrame = 160,
		NumFrames = 355,
		StartFrame = 91,
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusTalkDenial_Loop2",
		InheritFrom = "ModsNikkelMHadesBiomes_ZagreusTalkDenial",
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusTalkDenial_WeightShift2",
		EndFrame = 220,
		NumFrames = 355,
		StartFrame = 161,
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusTalkDenial_WeightShift2",
		InheritFrom = "ModsNikkelMHadesBiomes_ZagreusTalkDenial",
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusIdle",
		EndFrame = 355,
		NumFrames = 355,
		StartFrame = 221,
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusTalkDenial_Full",
		InheritFrom = "ModsNikkelMHadesBiomes_ZagreusTalkDenial",
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusTalkDenial_Loop_Full",
		EndFrame = 30,
		NumFrames = 355,
		StartFrame = 1,
	},
	-- #endregion

	-- #region TalkEmpathy
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusInteractionThoughtful",
		FilePath = "Animations\\Zagreus\\InteractionThoughtful\\ZagreusInteractionThoughtful",
		VideoTexture = "ZagreusInteractionThoughtful_Bink",
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusInteractionThoughtful.sga",
		EndFrame = 334,
		NumAngles = 8,
		NumFrames = 334,
		StartFrame = 1,
		OffsetY = -105.0,
		SetOwnerEndAngle = true,
		CancelOnOwnerMove = true,
		Scale = 1.05,
	},
	-- #endregion

	-- #region ComeHither
	{
		Name = "ZagreusInteractionComeHither_Start",
		FilePath = "Animations\\Zagreus\\InteractionComeHither\\ZagreusInteractionComeHither",
		VideoTexture = "ZagreusInteractionComeHither_Bink",
		ChainTo = "ZagreusInteractionComeHither_Hold",
		EndFrame = 80,
		NumAngles = 8,
		NumFrames = 170,
		StartFrame = 2,
		OffsetY = -105.0,
		SetOwnerEndAngle = true,
		Scale = 1.05,
	},
	{
		Name = "ZagreusInteractionComeHither",
		FilePath = "Animations\\Zagreus\\InteractionComeHither\\ZagreusInteractionComeHither",
		VideoTexture = "ZagreusInteractionComeHither_Bink",
		ChainTo = "ZagreusInteractionComeHither_End",
		EndFrame = 170,
		NumAngles = 8,
		NumFrames = 170,
		StartFrame = 2,
		OffsetY = -105.0,
		SetOwnerEndAngle = true,
		Scale = 1.05,
	},
	{
		Name = "ZagreusInteractionComeHither_Hold",
		InheritFrom = "ZagreusInteractionComeHither",
		ChainTo = "ZagreusInteractionComeHither_End",
		EndFrame = 80,
		Loop = true,
		NumFrames = 170,
		StartFrame = 80,
		OffsetY = -105.0,
		SetOwnerEndAngle = true,
		Scale = 1.05,
	},
	{
		Name = "ZagreusInteractionComeHither_End",
		InheritFrom = "ZagreusInteractionComeHither",
		EndFrame = 170,
		NumFrames = 170,
		StartFrame = 80,
		OffsetY = -105.0,
		SetOwnerEndAngle = true,
		Scale = 1.05,
	},
	-- #endregion

	-- #region Sick/Injured
	{
		Name = "ZagreusInjured_IdleToSick",
		FilePath = "Animations\\Zagreus\\InteractionEnding\\InjuredIdleToSick\\ZagreusInjuredIdleToSick",
		ChainTo = "ZagreusInjured_SickStanding_Loop",
		VideoTexture = "ZagreusInjured_IdleToSick_Bink",
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusEndingInjuredIdleToSick.sga",
		NumAngles = 8,
		EndFrame = 50,
		Loop = false,
		NumFrames = 50,
		PlaySpeed = 60.0,
		StartFrame = 2,
		OffsetY = -105.0,
		Scale = 1.05,
		CancelOnOwnerMove = true,
		SetOwnerEndAngle = true,
	},
	{
		Name = "ZagreusInjured_SickStandingSet",
		FilePath = "Animations\\Zagreus\\InteractionEnding\\InjuredSickToKneel\\ZagreusInjuredSickToKneel",
		VideoTexture = "ZagreusInjured_SickStandingSet_Bink",
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusEndingInjuredSickToKneel.sga",
		EndFrame = 280,
		NumAngles = 8,
		NumFrames = 280,
		PlaySpeed = 60.0,
		StartFrame = 1,
		OffsetY = -105.0,
		SetOwnerEndAngle = true,
		TransferFrameFromThis = true,
		Scale = 1.05,
		CancelOnOwnerMove = true,
	},
	{
		Name = "ZagreusInjured_SickStanding_Loop",
		InheritFrom = "ZagreusInjured_SickStandingSet",
		ChainTo = "ZagreusInjured_SickStanding_ToKneeling",
		EndFrame = 90,
		Loop = true,
		NumFrames = 280,
		StartFrame = 1,
	},
	{
		Name = "ZagreusInjured_SickStanding_ToKneeling",
		InheritFrom = "ZagreusInjured_SickStandingSet",
		ChainTo = "ZagreusInjured_SickKneeling_Loop",
		EndFrame = 189,
		NumFrames = 280,
		Loop = false,
		StartFrame = 91,
	},
	{
		Name = "ZagreusInjured_SickKneeling_Loop",
		InheritFrom = "ZagreusInjured_SickStandingSet",
		-- Custom, used to be ZagreusInjured_SickKneeling_ToReach which doesn't exist?
		ChainTo = "ZagreusInjured_SickKneelingSet_ToDeath",
		EndFrame = 280,
		NumFrames = 280,
		StartFrame = 190,
		Loop = true,
	},
	{
		Name = "ZagreusInjured_SickKneelingSet",
		FilePath = "Animations\\Zagreus\\InteractionEnding\\InjuredKneelToDeathVFX\\InjuredKneelToDeath",
		VideoTexture = "ZagreusInjured_SickKneelingSet_Bink",
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusEndingInjureKneeToDeath.sga",
		EndFrame = 320,
		NumAngles = 1,
		NumFrames = 320,
		PlaySpeed = 30.0,
		StartFrame = 1,
		OffsetY = -105.0,
		SetOwnerEndAngle = true,
		TransferFrameFromThis = true,
		Scale = 0.685,
		CancelOnOwnerMove = true,
		HoldLastFrame = true,
		AngleFromOwner = "Ignore",
		Slides = {
			{ Frame = 152, Sound = "/Leftovers/World Sounds/ClickSplash" },
			{ Frame = 156, Sound = "/Leftovers/SFX/GeyserSplash" },
			{ Frame = 182, Sound = "/SFX/BloodGeyserSplash" },
			{ Frame = 203, Sound = "/SFX/BloodGeyserSplash" },
		},
	},
	-- #endregion

	-- #region Fishing
	{
		Name = "ZagreusInteractionFishing",
		FilePath = "Animations\\Zagreus\\InteractionFishing\\ZagreusInteractionFishingSuccess",
		VideoTexture = "ZagreusInteractionFishing_Bink",
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusFishingSuccess.sga",
		NumAngles = 8,
		EndFrame = 260,
		Loop = false,
		NumFrames = 260,
		PlaySpeed = 60.0,
		StartFrame = 1,
		OffsetY = -105.0,
		Scale = 1.05,
		CancelOnOwnerMove = true,
		SetOwnerEndAngle = true,
		DisableOwnerInteract = true,
	},
	{
		Name = "ZagreusInteractionFishing_Start",
		InheritFrom = "ZagreusInteractionFishing",
		ChainTo = "ZagreusInteractionFishing_FishingWait",
		EndFrame = 60,
		Loop = false,
		NumFrames = 260,
		StartFrame = 1,
		TimeModifierFraction = 0.0,
		Sound = "/Leftovers/World Sounds/TrainingMontageWhoosh",
	},
	{
		Name = "ZagreusInteractionFishing_FishingWait",
		InheritFrom = "ZagreusInteractionFishing",
		ChainTo = "ZagreusInteractionFishing_FishingWait2",
		EndFrame = 87,
		NumFrames = 260,
		StartFrame = 61,
		PlaySpeed = 30,
		TimeModifierFraction = 0.0,
	},
	{
		Name = "ZagreusInteractionFishing_FishingWait2",
		InheritFrom = "ZagreusInteractionFishing",
		EndFrame = 87,
		NumFrames = 260,
		StartFrame = 61,
		TimeModifierFraction = 1.0,
		Loop = true,
	},
	{
		Name = "ZagreusInteractionFishing_PullSuccess",
		InheritFrom = "ZagreusInteractionFishing",
		ChainTo = "ZagreusInteractionFishing_CatchSuccess",
		EndFrame = 128,
		Loop = false,
		NumFrames = 260,
		StartFrame = 88,
		TimeModifierFraction = 0.0,
		Slides = {
			{ Frame = 122, Sound = "/Leftovers/World Sounds/TrainingMontageWhoosh" },
		},
	},
	{
		Name = "ZagreusInteractionFishing_PullFailure",
		InheritFrom = "ZagreusInteractionFishing_PullSuccess",
		ChainTo = "ZagreusInteractionFishingFail",
		Sound = "/Leftovers/World Sounds/TrainingMontageWhoosh",
	},
	{
		Name = "ZagreusInteractionFishing_CatchSuccess",
		InheritFrom = "ZagreusInteractionFishing",
		ChainTo = "ZagreusInteractionFishing_CatchSuccessHold1",
		EndFrame = 158,
		Loop = false,
		NumFrames = 260,
		StartFrame = 129,
		TimeModifierFraction = 0.0,
		Slides = {
			{ Frame = 129, Sound = "/Leftovers/World Sounds/TrainingMontageWhoosh" },
			{ Frame = 134, Sound = "/Leftovers/World Sounds/BigSplash" },
			{ Frame = 160, Sound = "/Leftovers/World Sounds/Caravan Interior/FloatingRockInteract" },
		},
	},
	{
		Name = "ZagreusInteractionFishing_CatchSuccessHold1",
		InheritFrom = "ZagreusInteractionFishing",
		ChainTo = "ZagreusInteractionFishing_CatchSuccessHold2",
		EndFrame = 184,
		Loop = false,
		NumFrames = 260,
		StartFrame = 159,
		PlaySpeed = 30,
		TimeModifierFraction = 0.0,
	},
	{
		Name = "ZagreusInteractionFishing_CatchSuccessHold2",
		InheritFrom = "ZagreusInteractionFishing",
		ChainTo = "ZagreusInteractionFishing_CatchSuccessHold3",
		EndFrame = 184,
		Loop = false,
		NumFrames = 260,
		StartFrame = 159,
		PlaySpeed = 30,
		TimeModifierFraction = 0.0,
	},
	{
		Name = "ZagreusInteractionFishing_CatchSuccessHold3",
		InheritFrom = "ZagreusInteractionFishing",
		ChainTo = "ZagreusInteractionFishing_CatchSuccessHold4",
		EndFrame = 184,
		Loop = false,
		NumFrames = 260,
		StartFrame = 159,
		PlaySpeed = 30,
		TimeModifierFraction = 0.0,
	},
	{
		Name = "ZagreusInteractionFishing_CatchSuccessHold4",
		InheritFrom = "ZagreusInteractionFishing",
		ChainTo = "ZagreusInteractionFishing_CatchSuccessReturnToIdle",
		EndFrame = 184,
		Loop = false,
		NumFrames = 260,
		StartFrame = 159,
		PlaySpeed = 60,
		TimeModifierFraction = 0.0,
	},
	{
		Name = "ZagreusInteractionFishing_CatchSuccessReturnToIdle",
		InheritFrom = "ZagreusInteractionFishing",
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusIdle",
		EndFrame = 260,
		Loop = false,
		NumFrames = 260,
		StartFrame = 185,
		TimeModifierFraction = 0.0,
		Slides = {
			{ Frame = 198, Sound = "/SFX/Player Sounds/WeaponSwing" },
			{ Frame = 199, Sound = "/VO/ZagreusEmotes/EmoteDodgingAlt" },
		},
	},
	{
		Name = "ZagreusInteractionFishingFail",
		FilePath = "Animations\\Zagreus\\InteractionFishingFail\\ZagreusInteractionFishingFail",
		VideoTexture = "ZagreusInteractionFishingFail_Bink",
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusFishingFail.sga",
		NumAngles = 8,
		EndFrame = 98,
		Loop = false,
		NumFrames = 98,
		PlaySpeed = 60.0,
		StartFrame = 1,
		OffsetY = -105.0,
		Scale = 1.05,
		CancelOnOwnerMove = true,
		SetOwnerEndAngle = true,
		Slides = {
			{ Frame = 1, Sound = "/VO/ZagreusEmotes/EmoteUnpetrified" }
		},
	},
	-- #endregion

	-- #region Ending Boat
	{
		Name = "ZagreusEndingBoat_IdleLoop",
		FilePath = "Animations\\Zagreus\\InteractionEnding\\BoatEndingIdleLoop\\ZagreusEndingBoatIdleLoop",
		VideoTexture = "ZagreusEndingBoatIdleLoop_Bink",
		ChainTo = "null",
		EndFrame = 120,
		NumAngles = 1,
		NumFrames = 120,
		Loop = true,
		AngleFromOwner = "Ignore",
		PlaySpeed = 30.0,
		StartFrame = 1,
		OffsetY = -105.0,
		Scale = 1.05,
		CancelOnOwnerMove = true,
	},
	{
		Name = "ZagreusEndingBoat_IdleFidget1",
		FilePath = "Animations\\Zagreus\\InteractionEnding\\BoatEndingIdleFidget1\\ZagreusEndingBoatIdleFidget1",
		VideoTexture = "ZagreusEndingBoatIdleFidget1_Bink",
		ChainTo = "ZagreusEndingBoat_IdleLoop",
		EndFrame = 120,
		NumAngles = 1,
		NumFrames = 120,
		AngleFromOwner = "Ignore",
		PlaySpeed = 30.0,
		StartFrame = 1,
		OffsetY = -105.0,
		Scale = 1.05,
		CancelOnOwnerMove = true,
	},
	{
		Name = "ZagreusEndingBoat_IdleFidget2",
		FilePath = "Animations\\Zagreus\\InteractionEnding\\BoatEndingIdleFidget2\\ZagreusEndingBoatIdleFidget2",
		VideoTexture = "ZagreusEndingBoatIdleFidget2_Bink",
		ChainTo = "ZagreusEndingBoat_IdleLoop",
		EndFrame = 120,
		NumAngles = 1,
		NumFrames = 120,
		AngleFromOwner = "Ignore",
		PlaySpeed = 30.0,
		StartFrame = 1,
		OffsetY = -105.0,
		Scale = 1.05,
		CancelOnOwnerMove = true,
	},
	{
		Name = "ZagreusEndingBoat_IdleLoop1",
		InheritFrom = "ZagreusEndingBoat_IdleLoop",
		Loop = false,
		ChainTo = "ZagreusEndingBoat_IdleFidgetLoop1",
	},
	{
		Name = "ZagreusEndingBoat_IdleFidgetLoop1",
		InheritFrom = "ZagreusEndingBoat_IdleFidget1",
		ChainTo = "ZagreusEndingBoat_IdleLoop2",
	},
	{
		Name = "ZagreusEndingBoat_IdleLoop2",
		InheritFrom = "ZagreusEndingBoat_IdleLoop",
		Loop = false,
		ChainTo = "ZagreusEndingBoat_IdleLoop3",
	},
	{
		Name = "ZagreusEndingBoat_IdleLoop3",
		InheritFrom = "ZagreusEndingBoat_IdleLoop",
		Loop = false,
		ChainTo = "ZagreusEndingBoat_IdleLoop4",
	},
	{
		Name = "ZagreusEndingBoat_IdleLoop4",
		InheritFrom = "ZagreusEndingBoat_IdleLoop",
		Loop = false,
		ChainTo = "ZagreusEndingBoat_IdleLoop5",
	},
	{
		Name = "ZagreusEndingBoat_IdleLoop5",
		InheritFrom = "ZagreusEndingBoat_IdleLoop",
		Loop = false,
		ChainTo = "ZagreusEndingBoat_IdleFidgetLoop2",
	},
	{
		Name = "ZagreusEndingBoat_IdleFidgetLoop2",
		InheritFrom = "ZagreusEndingBoat_IdleFidget2",
		ChainTo = "ZagreusEndingBoat_IdleLoop1",
	},
	-- #endregion

	-- #region Locomotion
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusIdle",
		FilePath = "Animations\\Zagreus\\Idle\\ZagreusIdle",
		VideoTexture = "ZagreusIdle_Bink",
		EndFrame = 120,
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusIdle.sga",
		Loop = true,
		NumAngles = 32,
		NumFrames = 120,
		StartFrame = 1,
		OffsetY = -105.0,
		SetOwnerEndAngle = true,
		Scale = 1.05,
		CancelOnOwnerMove = true,
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusStart",
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusRun",
		FilePath = "Animations\\Zagreus\\Start\\ZagreusStart",
		VideoTexture = "ZagreusStart_Bink",
		EndFrame = 32,
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusStart.sga",
		NumAngles = 64,
		NumFrames = 32,
		StartFrame = 1,
		OffsetY = -105.0,
		Scale = 1.05,
		NativeMoveSpeed = 540.0,
		SoundManagerCap = 16,
		Slides = {
			{ DurationFrames = 1 },
			{ DurationFrames = 1, FootstepFxR = "FireFootstepR-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurface" },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1, FootstepFxL = "FireFootstepL-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurface" },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
		},
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusRun",
		FilePath = "Animations\\Zagreus\\Run\\ZagreusRun",
		VideoTexture = "ZagreusRun_Bink",
		EndFrame = 32,
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusRun.sga",
		Loop = true,
		NumAngles = 64,
		NumFrames = 32,
		PlaySpeed = 60.0,
		StartFrame = 1,
		OffsetY = -105.0,
		Scale = 1.05,
		NativeMoveSpeed = 540.0,
		SoundManagerCap = 16,
		Slides = {
			{ DurationFrames = 1, FootstepFxR = "FireFootstepR-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurfaceRun", Frame = 1 },
			{ DurationFrames = 1, FootstepFxL = "FireFootstepL-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurfaceRun", Frame = 16 },
		},
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusStop",
		FilePath = "Animations\\Zagreus\\Stop\\ZagreusStop",
		VideoTexture = "ZagreusStop_Bink",
		EndFrame = 32,
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusStop.sga",
		NumAngles = 32,
		NumFrames = 32,
		StartFrame = 1,
		OffsetY = -105.0,
		Scale = 1.05,
		CancelOnOwnerMove = true,
		SoundManagerCap = 16,
		Slides = {

			{ DurationFrames = 0 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1, FootstepSound = "/SFX/Player Sounds/FootstepsHardSurface" },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
		},
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusWalk2",
		FilePath = "Animations\\Zagreus\\Walk2\\ZagreusWalk",
		StopAnimation = "ModsNikkelMHadesBiomes_ZagreusWalkStop2",
		VideoTexture = "ZagreusWalk2_Bink",
		EndFrame = 60,
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusWalk2.sga",
		Loop = true,
		NumAngles = 32,
		NumFrames = 60,
		StartFrame = 1,
		OffsetY = -105.0,
		Scale = 1.05,
		SoundManagerCap = 16,
		Slides = {
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1, FootstepFxL = "FireFootstepL-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurfaceRun", },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1, FootstepFxR = "FireFootstepR-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurfaceRun" },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
		},
	},
	{
		Name = "ModsNikkelMHadesBiomes_ZagreusWalkStop2",
		ChainTo = "ModsNikkelMHadesBiomes_ZagreusIdle",
		FilePath = "Animations\\Zagreus\\WalkStop2\\ZagreusWalkStop2",
		VideoTexture = "ZagreusWalkStop2_Bink",
		EndFrame = 60,
		FrameDataFile = "Game\\Animations\\FrameData\\ZagreusWalkStop.sga",
		NumAngles = 32,
		NumFrames = 60,
		StartFrame = 1,
		OffsetY = -105.0,
		SetOwnerEndAngle = true,
		Scale = 1.05,
		CancelOnOwnerMove = true,
		Slides = {

			{ DurationFrames = 1, FootstepFxL = "FireFootstepL-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurfaceRun" },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1, FootstepFxR = "FireFootstepR-Spawner", FootstepSound = "/SFX/Player Sounds/FootstepsHardSurfaceRun" },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },

			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
			{ DurationFrames = 1 },
		},
	},

	-- #region Death
	{
		Name = "ZagreusInjured_SickKneelingSet_ToDeath",
		InheritFrom = "ZagreusInjured_SickKneelingSet",
	},
	{
		Name = "ZagreusInjured_SickStanding_ToDeath",
		InheritFrom = "ZagreusInjured_SickStandingSet",
		ChainTo = "ZagreusInjured_SickKneelingSet_ToDeath",
		EndFrame = 189,
		NumFrames = 280,
		Loop = false,
		StartFrame = 91,
		Slides = {
			{ Frame = 127, Sound = "/SFX/FistImpactMedium" },
			{ Frame = 128, Sound = "/Leftovers/World Sounds/ClickSplash" },
			{ Frame = 129, Sound = "/VO/ZagreusEmotes/EmoteChoking" },
		},
	},
	-- #endregion
	-- #endregion
}

sjson.hook(animationsFile, function(data)
	for _, newValue in ipairs(newData) do
		table.insert(data.Animations, sjson.to_object(newValue, order))
	end
end)
