-- Defines animation names that already exist in Hades II and should therefore be skipped when the Hades Portrait animations are imported

-- The destination filename, used in a couple of places in the mod, therefore defined centrally
mod.HadesPortraitAnimationsDestinationFilename = "Game\\Animations\\Z_ModsNikkelmHadesBiomesPortraitAnimations.sjson"

mod.HadesPortraitAnimationModifications = {}

mod.HadesPortraitAnimationAdditions = {
	-- #region Zagreus and Melinoe partner portraits
	{
		Name = "ModsNikkelMHadesBiomes_Portrait_Zag_Default_01",
		InheritFrom = "Portrait_Base_01",
		FilePath = "Portraits\\MelAndZagDefault",
		OffsetY = 32,
		OffsetX = -135,
	},
	{
		Name = "ModsNikkelMHadesBiomes_Portrait_Zag_Default_01_Exit",
		InheritFrom = "Portrait_Base_01_Exit",
		FilePath = "Portraits\\MelAndZagDefault",
		OffsetY = 32,
		OffsetX = -135,
	},
	{
		Name = "ModsNikkelMHadesBiomes_Portrait_Zag_Serious_01",
		InheritFrom = "Portrait_Base_01",
		FilePath = "Portraits\\MelAndZagSerious",
		OffsetY = 32,
		OffsetX = -70,
	},
	{
		Name = "ModsNikkelMHadesBiomes_Portrait_Zag_Serious_01_Exit",
		InheritFrom = "Portrait_Base_01_Exit",
		FilePath = "Portraits\\MelAndZagSerious",
		OffsetY = 32,
		OffsetX = -70,
	},
	{
		Name = "ModsNikkelMHadesBiomes_Portrait_Zag_Defiant_01",
		InheritFrom = "Portrait_Base_01",
		FilePath = "Portraits\\MelAndZagDefiant",
		OffsetY = 32,
		OffsetX = 0,
	},
	{
		Name = "ModsNikkelMHadesBiomes_Portrait_Zag_Defiant_01_Exit",
		InheritFrom = "Portrait_Base_01_Exit",
		FilePath = "Portraits\\MelAndZagDefiant",
		OffsetY = 32,
		OffsetX = 0,
	},
	{
		Name = "ModsNikkelMHadesBiomes_Portrait_Zag_Empathetic_01",
		InheritFrom = "Portrait_Base_01",
		FilePath = "Portraits\\MelAndZagEmpathetic",
		OffsetY = 32,
		OffsetX = -100,
	},
	{
		Name = "ModsNikkelMHadesBiomes_Portrait_Zag_Empathetic_01_Exit",
		InheritFrom = "Portrait_Base_01_Exit",
		FilePath = "Portraits\\MelAndZagEmpathetic",
		OffsetY = 32,
		OffsetX = -100,
	},
	{
		Name = "ModsNikkelMHadesBiomes_Portrait_Zag_Unwell_01",
		InheritFrom = "Portrait_Base_01",
		FilePath = "Portraits\\MelAndZagUnwell",
		OffsetY = 32,
		OffsetX = -100,
	},
	{
		Name = "ModsNikkelMHadesBiomes_Portrait_Zag_Unwell_01_Exit",
		InheritFrom = "Portrait_Base_01_Exit",
		FilePath = "Portraits\\MelAndZagUnwell",
		OffsetY = 32,
		OffsetX = -100,
	},
	-- #endregion
	-- #region Character Dialogue portraits that are duplicates between the games
	{
		Name = "ModsNikkelMHadesBiomes_Portrait_Bouldy",
		InheritFrom = "Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesPortraits\\Portraits_Bouldy_01",
		Scale = 1.0,
		OffsetY = -117,
	},
	{
		Name = "ModsNikkelMHadesBiomes_Portrait_Bouldy_Exit",
		InheritFrom = "Portrait_Base_01_Exit",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesPortraits\\Portraits_Bouldy_01",
		Scale = 1.0,
		OffsetY = -117,
	},
	{
		Name = "ModsNikkelMHadesBiomes_Portrait_Cerberus",
		InheritFrom = "Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesPortraits\\Portraits_Cerberus_01",
		Scale = 1.0,
		OffsetY = -117,
	},
	{
		Name = "ModsNikkelMHadesBiomes_Portrait_Cerberus_Exit",
		InheritFrom = "Portrait_Base_01_Exit",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesPortraits\\Portraits_Cerberus_01",
		Scale = 1.0,
		OffsetY = -117,
	},
	-- #region Codex portraits that are duplicates between the games
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_AsphodelBiome",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_BiomeAsphodel",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_ElysiumBiome",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_BiomeElysium",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_ErebusBiome",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_BiomeErebus",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_TartarusBiome",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_BiomeTartarus",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_ChaosBiome",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_BiomeChaos",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_Persephone",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_Persephone",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_Cerberus",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_Cerberus",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_Charon",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_Charon",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_Skelly",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_Skelly",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_BloodlessBerserker",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_BloodlessBerserker",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_Grenadier",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_BloodlessGrenadier",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_Pitcher",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_BloodlessPitcher",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_SelfDestruct",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_BloodlessSelfDestruct",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_Crawler",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_Crawler",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_CrawlerMiniBoss",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_CrawlerMiniBoss",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_Hades",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_Hades",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_Thug",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_WretchThug",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_Zagreus",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_Zagreus",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_Achilles",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_Achilles",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_Megaera",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_Megaera",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_Orpheus",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_Orpheus",
	},
	{
		Name = "ModsNikkelMHadesBiomes_Codex_Portrait_Thanatos",
		InheritFrom = "Codex_Portrait_Base_01",
		FilePath = "Portraits\\ModsNikkelMHadesBiomesCodex\\CodexPortrait_Thanatos",
	},
	-- #endregion
}

-- Duplicate Fx animation, saved here due to the animations not being hooked, but copied directly
mod.HadesPortraitAnimationDuplicates = {
	["PortraitEmoteNervous"] = true,
	["PortraitEmoteNervousSweat"] = true,
	["PortraitEmoteNervousSound"] = true,
	["PortraitEmoteNervousSweatSmall"] = true,
	["PortraitEmoteDepressed"] = true,
	["PortraitEmoteDepressedLineA"] = true,
	["PortraitEmoteDepressedLineB"] = true,
	["PortraitEmoteDepressedLineC"] = true,
	["PortraitEmoteDepressedLineD"] = true,
	["PortraitEmoteDepressedSound"] = true,
	["PortraitEmoteAnger"] = true,
	["PortraitEmoteAngerFx"] = true,
	["PortraitEmoteAngerFxExclamation"] = true,
	["PortraitEmoteAngerFxExclamation2"] = true,
	["PortraitEmoteAngerSound"] = true,
	["PortraitEmoteAngerVeins"] = true,
	["PortraitEmoteAffection"] = true,
	["PortraitEmoteAffectionHearts"] = true,
	["PortraitEmoteAffectionA"] = true,
	["PortraitEmoteAffectionB"] = true,
	["PortraitEmoteAffectionC"] = true,
	["PortraitEmoteAffectionD"] = true,
	["PortraitEmoteAffectionE"] = true,
	["PortraitEmoteAffectionF"] = true,
	["PortraitEmoteFiredUp"] = true,
	["PortraitEmoteExcitedExclamationPoints"] = true,
	["PortraitEmoteExcitedExclamationPointBase"] = true,
	["PortraitEmoteExcitedExclamationPointA"] = true,
	["PortraitEmoteExcitedExclamationPointB"] = true,
	["PortraitEmoteExcitedExclamationPointC"] = true,
	["PortraitEmoteExcitedExclamationPointD"] = true,
	["PortraitEmoteExcitedExclamationPointE"] = true,
	["PortraitEmoteExcitedExclamationPointF"] = true,
	["PortraitEmoteExcitedSound"] = true,
	["PortraitEmoteCheerful"] = true,
	["PortraitEmoteCheerfulFlowers"] = true,
	["PortraitEmoteCheerfulFlowerBase"] = true,
	["PortraitEmoteCheerfulFlowerBaseDark"] = true,
	["PortraitEmoteCheerfulBurst"] = true,
	["PortraitEmoteCheerfulBurstDark"] = true,
	["PortraitEmoteCheerfulFlowerA"] = true,
	["PortraitEmoteCheerfulFlowerB"] = true,
	["PortraitEmoteCheerfulFlowerC"] = true,
	["PortraitEmoteSparkly"] = true,
	["PortraitEmoteFiredUpSparkle"] = true,
	["PortraitEmoteFiredUpSparkleA"] = true,
	["PortraitEmoteFiredUpSparkleB"] = true,
	["PortraitEmoteFiredUpSparkleC"] = true,
	["PortraitEmoteFiredUpSparkleD"] = true,
	["PortraitEmoteFiredUpSparkleE"] = true,
	["PortraitEmoteFiredUpSparkleF"] = true,
	["PortraitEmoteSurprise"] = true,
	["PortraitEmoteSurpriseSpike"] = true,
	["PortraitEmoteSurpriseSpike2"] = true,
	["PortraitEmoteSurprise_Fade"] = true,
	["PortraitEmoteSurpriseB"] = true,
	["PortraitEmoteSurpriseB_Fade"] = true,
	["PortraitGodAppear"] = true,
	["PortraitGodAppearVertical"] = true,
	["PortraitGodAppearSpectral"] = true,
	["PortraitGodAppear2"] = true,
	["PortraitVerticalRayEmitter_Base"] = true,
	["PortraitVerticalRay"] = true,
	["PortraitRayParticle"] = true,
	["PortraitVerticalRayEmitter_Ares"] = true,
	["PortraitVerticalRay_Ares"] = true,
	["PortraitRayParticle_Ares"] = true,
	["PortraitVerticalRayEmitter_Athena"] = true,
	["PortraitVerticalRay_Athena"] = true,
	["PortraitRayParticle_Athena"] = true,
	["PortraitVerticalRayEmitter_Artemis"] = true,
	["PortraitVerticalRay_Artemis"] = true,
	["PortraitRayParticle_Artemis"] = true,
	["PortraitVerticalRayEmitter_Aphrodite"] = true,
	["PortraitVerticalRay_Aphrodite"] = true,
	["PortraitRayParticle_Aphrodite"] = true,
	["PortraitVerticalRay_Dionysus"] = true,
	["PortraitRayParticle_Dionysus"] = true,
	["PortraitVerticalRayEmitter_Demeter"] = true,
	["PortraitVerticalRay_Demeter"] = true,
	["PortraitRayParticle_Demeter"] = true,
	["PortraitVerticalRayEmitter_Poseidon"] = true,
	["PortraitVerticalRay_Poseidon"] = true,
	["PortraitRayParticle_Poseidon"] = true,
	["PortraitVerticalRayEmitter_Zeus"] = true,
	["PortraitVerticalRay_Zeus"] = true,
	["PortraitRayParticle_Zeus"] = true,
	["PortraitVerticalRayEmitter_Hermes"] = true,
	["PortraitVerticalRay_Hermes"] = true,
	["PortraitRayParticle_Hermes"] = true,
	["PortraitGodRay01"] = true,
	["PortraitGodRay02"] = true,
	["PortraitGodRay03"] = true,
	["PortraitGodRay04"] = true,
	["PortraitGodRay05"] = true,
	["PortraitGodRay06"] = true,
	["PortraitGodRay07"] = true,
	["PortraitGodRay08"] = true,
	["PortraitGodRay09"] = true,
	["PortraitGodRay10"] = true,
	["PortraitGodRay11"] = true,
	["PortraitGodRay12"] = true,
	["PortraitGodRay13"] = true,
	["PortraitGodRay14"] = true,
	["PortraitGodRay15"] = true,
	["PortraitGodRay16"] = true,
	["PortraitGodRay17"] = true,
	["PortraitGodRays"] = true,
	["PortraitGodRayEmitter"] = true,
	["PortraitGodRayEmitter_Hermes"] = true,
	["PortraitGodRayEmitter_Athena"] = true,
	["PortraitGodRayEmitter_Ares"] = true,
	["PortraitGodRayEmitter_Aphrodite"] = true,
	["PortraitGodRayEmitter_Demeter"] = true,
	["PortraitGodRayEmitter_Dionysus"] = true,
	["PortraitGodRayEmitter_Poseidon"] = true,
	["PortraitGodRayEmitter_Zeus"] = true,
	["Portrait_God_01"] = true,
	["Portrait_Cerberus_Default_01"] = true,
	["Portrait_Cerberus_Default_01_Exit"] = true,
	["Portrait_Chaos_Default_01"] = true,
	["Portrait_Chaos_Default_02"] = true,
	["Portrait_Chaos_Default_01_Exit"] = true,
	["Portrait_Skelly_Default_01"] = true,
	["Portrait_Skelly_Default_01_Exit"] = true,
	["Portrait_Nyx_Default_01"] = true,
	["Portrait_Nyx_Default_01_Exit"] = true,
	["Portrait_Demeter_Default_01"] = true,
	["Portrait_Demeter_Default_01_Exit"] = true,
	["Portrait_Athena_Default_01"] = true,
	["Portrait_Athena_Default_01_Exit"] = true,
	["Portrait_Zeus_Default_01"] = true,
	["Portrait_Zeus_Default_01_Exit"] = true,
	["Portrait_Poseidon_Default_01"] = true,
	["Portrait_Poseidon_Default_01_Exit"] = true,
	["Portrait_Artemis_Default_01"] = true,
	["Portrait_Artemis_Default_01_Exit"] = true,
	["Portrait_Aphrodite_Default_01"] = true,
	["Portrait_Aphrodite_Default_01_Exit"] = true,
	["Portrait_Ares_Default_01"] = true,
	["Portrait_Ares_Default_01_Exit"] = true,
	["Portrait_Dionysus_Default_01"] = true,
	["Portrait_Dionysus_Default_01_Exit"] = true,
	["Portrait_Hermes_Default_01"] = true,
	["Portrait_Hermes_Default_01_Exit"] = true,
	["Portrait_Charon_Default_01"] = true,
	["Portrait_Charon_Default_01_Exit"] = true,
	["Portrait_Bouldy_Default_01"] = true,
	["Portrait_Bouldy_Default_01_Exit"] = true,
	["Codex_Portrait_Base_01"] = true,
	["Codex_Portrait_Aphrodite"] = true,
	["Codex_Portrait_Ares"] = true,
	["Codex_Portrait_Artemis"] = true,
	["Codex_Portrait_Athena"] = true,
	["Codex_Portrait_Cerberus"] = true,
	["Codex_Portrait_Dionysus"] = true,
	["Codex_Portrait_Hermes"] = true,
	["Codex_Portrait_Demeter"] = true,
	["Codex_Portrait_Hades"] = true,
	["Codex_Portrait_Poseidon"] = true,
	["Codex_Portrait_Skelly"] = true,
	["Codex_Portrait_Zeus"] = true,
	["Codex_Portrait_Charon"] = true,
	["Codex_Portrait_Chaos"] = true,
	["Codex_Portrait_Hypnos"] = true,
	["Codex_Portrait_Crawler"] = true,
	["Codex_Portrait_ChaosBiome"] = true,
	["Codex_Portrait_AsphodelBiome"] = true,
	["Codex_Portrait_SurfaceBiome"] = true,
	["Codex_Portrait_BloodlessBerserker"] = true,
	["Codex_Portrait_CrawlerMiniBoss"] = true,
	-- Unseen Update
	["Portrait_Ares_Blink"] = true,
	["Portrait_Dionysus_Blink"] = true,
	-- 1.0 Update
	["Codex_Portrait_Zagreus"] = true,
	["Codex_Portrait_Nyx"] = true,
	["Codex_Portrait_Persephone"] = true,
	["Codex_Portrait_ElysiumBiome"] = true,
	["Portrait_Zag_Default_01"] = true,
	["Portrait_Zag_Default_01_Exit"] = true,
	["Portrait_Zag_Serious_01"] = true,
	["Portrait_Zag_Serious_01_Exit"] = true,
	["Portrait_Zag_Defiant_01"] = true,
	["Portrait_Zag_Defiant_01_Exit"] = true,
	["Portrait_Zag_Empathetic_01"] = true,
	["Portrait_Zag_Empathetic_01_Exit"] = true,
	["Portrait_Persephone_Queen_01"] = true,
	["Portrait_Persephone_Queen_01_Exit"] = true,
	["Portrait_Persephone_Queen_Calculating_01"] = true,
	["Portrait_Persephone_Queen_Calculating_01_Exit"] = true,
	["Portrait_Persephone_Queen_Apprehensive_01"] = true,
	["Portrait_Persephone_Queen_Apprehensive_01_Exit"] = true,
	["Portrait_Persephone_Queen_FiredUp_01"] = true,
	["Portrait_Persephone_Queen_FiredUp_01_Exit"] = true,
	-- Post-Launch Update 1
	["Codex_Portrait_Achilles"] = true,
	["Codex_Portrait_Megaera"] = true,
	["Codex_Portrait_Orpheus"] = true,
	["Codex_Portrait_Thanatos"] = true,
}
