-- Some names or Ids from Hades are reused in Hades II for something similar or different
-- These names need to be changed in order to avoid conflicts and to use both versions alongside each other

-- Enemies that exist in both games
mod.EnemyNameMappings = {
	BaseVulnerableEnemy = "HadesBaseVulnerableEnemy",
	-- TARTARUS
	LightRanged = "HadesLightRanged",
	Swarmer = "HadesSwarmer",
	ThiefMineLayer = "HadesThiefMineLayer",
	ThiefMineLayerElite = "HadesThiefMineLayerElite",
	-- ASPHODEL
	-- Most of these already exist in Hades II, so we copy them and do some minor modifications, such as for spawn FX
	BloodlessNaked = "HadesBloodlessNaked",
	BloodlessNakedElite = "HadesBloodlessNakedElite",
	BloodlessGrenadier = "HadesBloodlessGrenadier",
	BloodlessGrenadierElite = "HadesBloodlessGrenadierElite",
	BloodlessSelfDestruct = "HadesBloodlessSelfDestruct",
	BloodlessSelfDestructElite = "HadesBloodlessSelfDestructElite",
	BloodlessPitcher = "HadesBloodlessPitcher",
	BloodlessPitcherElite = "HadesBloodlessPitcherElite",
	BloodlessWaveFist = "HadesBloodlessWaveFist",
	BloodlessWaveFistElite = "HadesBloodlessWaveFistElite",
	SpreadShotUnit = "HadesSpreadShotUnit",
	SpreadShotUnitElite = "HadesSpreadShotUnitElite",
	-- STYX
	Crawler = "HadesCrawler",
	CrawlerMiniBoss = "HadesCrawlerMiniBoss",
}

-- Enemies that should be removed from the Hades enemy data, as they already exist in Hades II. Also applies to Enemies.sjson
mod.EnemyNameRemovals = {
	-- #region Actual duplicates
	-- #region GENERAL
	"TrainingMelee",
	"1_BaseBoss",
	"TrapPadDisabled",
	"PassiveRoomWeapon",
	"DemeterUpgradeRoomWeapon",
	"AresUpgradeRoomWeapon",
	"ZeusUpgradeRoomWeapon",
	"AphroditeUpgradeRoomWeapon",
	"PoseidonUpgradeRoomWeapon",
	"SpikeTrap",
	"TrapFissureDisabled",
	"GasTrapPassive",
	"BlastCubeFused",
	"GunBombUnit",
	"HazardPoint",
	"LavaSplash",
	"LavaTile",
	"LavaTileTriangle01",
	"LavaTileTriangle02",
	"TestCharacter",
	"BloodMine",
	-- #endregion

	-- #region ASPHODEL
	"BloodlessNaked",
	"BloodlessNakedElite",
	"BloodlessGrenadier",
	"BloodlessGrenadierElite",
	"BloodlessSelfDestruct",
	"BloodlessSelfDestructElite",
	"BloodlessPitcher",
	"BloodlessPitcherElite",
	"BloodlessWaveFist",
	"BloodlessWaveFistElite",
	"SpreadShotUnit",
	"SpreadShotUnitElite",
	"BloodlessNakedBerserker",
	"BloodlessNakedBerserkerElite",
	-- #endregion

	-- #region STYX
	"HadesTombstone",
	-- #endregion
	-- #endregion

	-- #region Unused enemies
	"SwarmerHelmeted",
	"SimpleSwarmer",
	"SimpleMelee",
	"SimpleMelee2",
	"ThiefPoisonLayer",
	"ThiefArmorer",
	"ShadeSwordUnitTest",
	"ShadeMagicUnit",
	"ShadeMagicUnitSuperElite",
	"TimeCrystal",
	"HealRanged",
	"HealRangedElite",
	"Illusionist",
	"IllusionistElite",
	"IllusionistClone",
	"IllusionistCloneElite",
	"SeekingShotUnit",
	"DionysusUpgradeRoomWeapon",
	"ArtemisUpgradeRoomWeapon",
	"AthenaUpgradeRoomWeapon",
	"SupportShields",
	"SelfDestructSpawner",
	"ShadeSpawner",
	"ShadeSpawnerElite",
	"UnstableGenerator",
	"UnstableGeneratorElite",
	"BreakableAsphodelHeal",
	"ReflectiveMirror",
	"BannerSupport",
	-- #endregion
}

mod.NPCNameMappings = {}
mod.NPCNameRemovals = {}

mod.EnemyProjectileMappings = {
	-- Not currently used by Hades II
	-- LightRangedWeapon = "HadesLightRangedWeapon",
	-- The two versions have different PressedIn/Out animations
	SpikeTrapWeapon = "HadesSpikeTrapWeapon",
	SwarmerMelee = "HadesSwarmerMelee",
}

mod.EnemyWeaponMappings = {
	-- The two versions have different PressedIn/Out animations
	SpikeTrapWeapon = "HadesSpikeTrapWeapon",
	SwarmerMelee = "HadesSwarmerMelee",
}

mod.EnemyAnimationMappings = {
	HadesStunTotemStatic = "ModsNikkelMHadesBiomesHadesStunTotemStatic",
	HadesTombstoneSpawn = "ModsNikkelMHadesBiomesHadesTombstoneSpawn",
	HadesStunTotemFlame = "ModsNikkelMHadesBiomesHadesStunTotemFlame",
	HadesStunTotemFlameSpawn = "ModsNikkelMHadesBiomesHadesStunTotemFlameSpawn",
	SpikeTrapIdle = "HadesSpikeTrapIdle",
	SpikeTrapPressed = "HadesSpikeTrapPressed",
	SpikeTrapPreFire = "HadesSpikeTrapPreFire",
	SpikeTrapDeactivated = "HadesSpikeTrapDeactivated"
}

mod.FxAnimationMappings = {
	SpikeTrapPressedIn = "HadesSpikeTrapPressedIn",
	SpikeTrapPressedOut = "HadesSpikeTrapPressedOut",

	DoorLocked = "HadesDoorLocked",
	DoorUnlocked = "HadesDoorUnlocked",

	EnemyProjectile = "HadesEnemyProjectile",
	EnemyProjectileIn = "HadesEnemyProjectileIn",
	EnemyProjectileLight = "HadesEnemyProjectileLight",

	HydraTouchdownFx = "HadesHydraTouchdownFx",
}
mod.GUIAnimationMappings = {
	ExitPreview = "ModsNikkelMHadesBiomes_ExitPreview",
	StoryPreview = "ModsNikkelMHadesBiomes_StoryPreview"
}
mod.PortraitAnimationMappings = {
	Portrait_Base_01 = "ModsNikkelMHadesBiomes_Portrait_Base_01",
	Portrait_Base_01_Exit = "ModsNikkelMHadesBiomes_Portrait_Base_01_Exit",
}
mod.CharacterAnimationsNPCsMappings = {}

-- Mappings for Asphodel room names, as B_ is also used in Hades II. Used e.g. in IsGameStateEligible to map requirements for rooms
mod.AsphodelRoomNameMappings = {
	["B_Intro"] = "X_Intro",
	["B_Boss01"] = "X_Boss01",
	["B_Boss02"] = "X_Boss02",
	["B_PostBoss01"] = "X_PostBoss01",
	["B_Wrapping01"] = "X_Wrapping01",
	["B_MiniBoss01"] = "X_MiniBoss01",
	["B_MiniBoss02"] = "X_MiniBoss02",
	["B_PreBoss01"] = "X_PreBoss01",
	["B_Shop01"] = "X_Shop01",
	["B_Reprieve01"] = "X_Reprieve01",
	["B_Combat01"] = "X_Combat01",
	["B_Combat02"] = "X_Combat02",
	["B_Combat03"] = "X_Combat03",
	["B_Combat04"] = "X_Combat04",
	["B_Combat05"] = "X_Combat05",
	["B_Combat06"] = "X_Combat06",
	["B_Combat07"] = "X_Combat07",
	["B_Combat08"] = "X_Combat08",
	["B_Combat09"] = "X_Combat09",
	["B_Combat10"] = "X_Combat10",
	["B_Combat21"] = "X_Combat21",
	["B_Combat22"] = "X_Combat22",
	["B_Story01"] = "X_Story01",
}

-- Mappings for Elysium room names, as C_ is also used in Hades II. Used e.g. in IsGameStateEligible to map requirements for rooms
mod.ElysiumRoomNameMappings = {
	["C_Intro"] = "Y_Intro",
	["C_Boss01"] = "Y_Boss01",
	["C_PostBoss01"] = "Y_PostBoss01",
	["C_PreBoss01"] = "Y_PreBoss01",
	["C_Shop01"] = "Y_Shop01",
	["C_MiniBoss01"] = "Y_MiniBoss01",
	["C_MiniBoss02"] = "Y_MiniBoss02",
	["C_Reprieve01"] = "Y_Reprieve01",
	["C_Combat01"] = "Y_Combat01",
	["C_Combat02"] = "Y_Combat02",
	["C_Combat03"] = "Y_Combat03",
	["C_Combat04"] = "Y_Combat04",
	["C_Combat05"] = "Y_Combat05",
	["C_Combat06"] = "Y_Combat06",
	["C_Combat07"] = "Y_Combat07",
	["C_Combat08"] = "Y_Combat08",
	["C_Combat09"] = "Y_Combat09",
	["C_Combat10"] = "Y_Combat10",
	["C_Combat11"] = "Y_Combat11",
	["C_Combat12"] = "Y_Combat12",
	["C_Combat13"] = "Y_Combat13",
	["C_Combat14"] = "Y_Combat14",
	["C_Combat15"] = "Y_Combat15",
	["C_Story01"] = "Y_Story01",
}

mod.HadesHelpTextFileNames = {
	"_EnemyData",
	"_EncounterData",
	"_LootData",
	"_RoomData",
	"_RoomDataAsphodel",
	"_RoomDataElysium",
	"_RoomDataStyx",
	"_RoomDataSurface",
	"_RoomDataTartarus",
}
-- These files do not exist
mod.HadesHelpTextFileSkipMap = {
	_NPCData = {
		en = true,
	},
	_EnemyData = {
		en = true,
	},
	_EncounterData = {
		en = true,
	},
	_LootData = {
		en = true,
	},
	_RoomData = {
		en = true,
	},
	_RoomDataAsphodel = {
		en = true,
	},
	_RoomDataElysium = {
		en = true,
	},
	_RoomDataStyx = {
		en = true,
	},
	_RoomDataSurface = {
		en = true,
	},
	_RoomDataTartarus = {
		en = true,
	},
}

mod.HadesHelpTextCopyKeys = {
	-- #region Combat Actions
	WallSlamHit = true,
	PitSlamHit = true,
	RubbleSlamHit = true,
	UnitFrozen = true,
	Combat_Enraged = true,
	Combat_PermanentEnraged = true,
	Pierced = true,
	Escaped = true,
	-- AssistNotAvailable = true, -- Duplicate
	-- AssistAvailableHint = true, -- Duplicate
	PoisonStack = true,
	-- DevotionMessage = true, -- Duplicate
	-- #endregion
	-- #region Interaction prompts
	UseLeaveRoomAsphodel = true,
	UseLeaveRoomAsphodel_Reroll = true,
	UseLeaveRoomAsphodel_CannotReroll = true,
	GiftBouldyUseText = true,
	UseTalkToSisyphus = true,
	UseTalkToBouldy = true,
	UseTalkToThanatos = true,
	UseTalkToPatroclus = true,
	UseTalkToCerberus = true,
	UseTalkToEurydice = true,
	UseTalkToFemaleGhost = true,
	UseFinalBossDoor = true,
	UseCerberusDoor = true,
	UseStyxWarpDoor = true,
	-- UseForbiddenItem = true, -- Duplicate
	-- UseCharonStoreDiscount = true, -- Duplicate
	-- #endregion
	-- #region Cerberus Messages
	ClearedCerberus_Title = true,
	ClearedCerberus_Subtitle = true,
	ClearedCerberus_Alt1_Title = true,
	ClearedCerberus_Alt1_Subtitle = true,
	ClearedCerberus_Alt2_Title = true,
	ClearedCerberus_Alt2_Subtitle = true,
	ClearedCerberus_A_Title = true,
	ClearedCerberus_A_Subtitle = true,
	ClearedCerberus_B_Title = true,
	ClearedCerberus_B_Subtitle = true,
	ClearedCerberus_C_Title = true,
	ClearedCerberus_C_Subtitle = true,
	ClearedCerberus_D_Title = true,
	ClearedCerberus_D_Subtitle = true,
	ClearedCerberus_E_Title = true,
	ClearedCerberus_E_Subtitle = true,
	ClearedCerberus_F_Title = true,
	ClearedCerberus_F_Subtitle = true,
	ClearedCerberus_G_Title = true,
	ClearedCerberus_G_Subtitle = true,
	ClearedCerberus_H_Title = true,
	ClearedCerberus_H_Subtitle = true,
	ClearedCerberus_I_Title = true,
	ClearedCerberus_I_Subtitle = true,
	ClearedCerberus_J_Title = true,
	ClearedCerberus_J_Subtitle = true,
	ClearedCerberus_K_Title = true,
	ClearedCerberus_K_Subtitle = true,
	ClearedCerberus_L_Title = true,
	ClearedCerberus_L_Subtitle = true,
	ClearedCerberus_M_Title = true,
	ClearedCerberus_M_Subtitle = true,
	ClearedCerberus_N_Title = true,
	ClearedCerberus_N_Subtitle = true,
	ClearedCerberus_O_Title = true,
	ClearedCerberus_O_Subtitle = true,
	ClearedCerberus_P_Title = true,
	ClearedCerberus_P_Subtitle = true,
	ClearedCerberus_Q_Title = true,
	ClearedCerberus_Q_Subtitle = true,
	-- #endregion
	-- #region Bouldy Blessings
	BouldyBlessing_None = true,
	-- GainedBouldyBlessing = true, -- Duplicate
	-- #endregion
	-- #region ShrinePointDoor
	ShrinePointGate = true,
	UseShrinePointDoor_Locked_PreReward = true,
	UseShrinePointDoor_Locked_PostReward = true,
	UseShrinePointDoor_Unlocked = true,
	UseShrinePointDoor_Unlocked_Reroll = true,
	UseShrinePointDoor_Unlocked_CannotReroll = true,
	ShrinePointDoorEnterRequirement = true,
	ExitBlockedByShrinePointReq = true,
	-- #endregion
	-- #region Combat Objectives
	Objective_ThanatosKills = true,
	-- Objective_SurvivalTimer = false, -- Manually added, as the formatting is different
	-- Objective_PlayerKills = true, -- Duplicate
	-- #endregion
	-- #region Enemies
	Swarmer = true,
	SwarmerElite = true,
	LightSpawner = true,
	LightSpawnerElite = true,
	DisembodiedHand = true,
	HeavyMeleeElite = true,
	LightRanged = true,
	LightRangedElite = true,
	PunchingBagUnit = true,
	PunchingBagUnitElite = true,
	ThiefMineLayer = true,
	ThiefMineLayerElite = true,
	HeavyMelee = true,
	WretchAssassinMiniboss = true,
	HeavyRanged = true,
	HeavyRangedElite = true,
	HeavyRangedSplitterMiniboss = true,
	ShieldRanged = true,
	ShieldRangedElite = true,
	RangedBurrower = true,
	BloodlessNaked = true,
	BloodlessNakedBerserker = true,
	BloodlessGrenadier = true,
	BloodlessGrenadierElite = true,
	BloodlessSelfDestruct = true,
	BloodlessWaveFist = true,
	BloodlessWaveFistElite = true,
	BloodlessPitcher = true,
	BloodlessPitcherElite = true,
	SpreadShotUnit = true,
	SpreadShotUnitMiniboss = true,
	CrusherUnit = true,
	CrusherUnitElite = true,
	FreezeShotUnit = true,
	HitAndRunUnit = true,
	ShadeNaked = true,
	ShadeSwordUnit = true,
	ShadeSpearUnit = true,
	ShadeBowUnit = true,
	ShadeShieldUnit = true,
	SplitShotUnit = true,
	FlurrySpawner = true,
	FlurrySpawnerElite = true,
	ChariotSuicide = true,
	Chariot = true,
	Crawler = true,
	RatThug = true,
	RatThugMiniboss = true,
	ThiefImpulseMineLayer = true,
	ThiefImpulseMineLayerMiniboss = true,
	HeavyRangedForked = true,
	HeavyRangedForkedMiniboss = true,
	SatyrRanged = true,
	SatyrRangedMiniboss = true,
	CrawlerMiniBoss = true,
	CrawlerMiniBoss_Full = true,
	SpikeTrap = true,
	DartTrap = true,
	BlastCubeFused = true,
	GasTrapPassive = true,
	-- #endregion
	-- #region Bosses
	HydraHeadImmortal = true,
	HydraHeadImmortal_Full = true,
	HydraHeadImmortal_NickName = true,
	Theseus = true,
	Minotaur = true,
	Minotaur_Full = true,
	Minotaur_NickName = true,
	Hades_Full = true,
	-- #endregion
	-- #region Characters
	NPC_FurySister_01 = true,
	Harpy = true,
	NPC_FurySister_02 = true,
	NPC_FurySister_Unnamed_02 = true,
	Harpy2 = true,
	Harpy2_Full = true,
	NPC_FurySister_03 = true,
	NPC_FurySister_Unnamed_03 = true,
	Harpy3 = true,
	Harpy3_Full = true,
	NPC_Orpheus_Story_01 = true,
	Orpheus = true,
	NPC_Sisyphus_01 = true,
	NPC_SisyphusAndBouldy_01 = true,
	Sisyphus = true,
	NPC_Patroclus_01 = true,
	NPC_Patroclus_Unnamed_01 = true,
	NPC_Eurydice_01 = true,
	NPC_Eurydice_Unnamed_01 = true,
	NPC_ThanatosUnnamed_01 = true,
	Thanatos = true,
	-- In Hades II, this is "Queen of the Underworld"
	NPC_Persephone_01 = "ModsNikkelMHadesBiomes_NPC_Persephone_01",
	-- This is the same as NPC_Persephone_01 in Hades II
	-- NPC_Persephone_01A = true,
	NPC_Persephone_Unnamed_01 = true,
	NPC_Persephone_Home_01 = true,
	EndingComplete = true,
	EpilogueComplete = true,
	-- NPC_Bouldy_01 = true, -- Duplicate
	-- NPC_Hades_01 = true, -- Duplicate
	-- NPC_Hades_Story_02 = true, -- Using alias
	Achilles = true,
	-- #endregion
	-- #region GameOutroData (Post-Ending)
	Outro_PostEnding01 = true,
	Outro_PostEnding02 = true,
	Outro_PostEnding03 = true,
	Outro_PostEnding04 = true,
	Outro_Inescapable = true,
	Outro_Prince = true,
	Outro_RatherGood = true,
	Outro_Glorious = true,
	Outro_Perfume = true,
	Outro_Avalanche = true,
	Outro_WrongTurn = true,
	Outro_Cactus = true,
	Outro_Bear = true,
	Outro_MountainGoat = true,
	Outro_Snake = true,
	Outro_Spears = true,
	Outro_Doom = true,
	Outro_Horrifying = true,
	Outro_Beetle = true,
	Outro_Precipice = true,
	Outro_Variety = true,
	Outro_Clever = true,
	Outro_Another = true,
	Outro_Setbacks = true,
	Outro_Wall = true,
	Outro_Fungus = true,
	Outro_Dream = true,
	Outro_Confines = true,
	Outro_Change = true,
	Outro_Shiver = true,
	Outro_Tool = true,
	Outro_Tale = true,
	Outro_Sure = true,
	Outro_Chariot = true,
	Outro_Demises = true,
	Outro_Peel = true,
	Outro_Ideas = true,
	Outro_Steam = true,
	Outro_Waiting = true,
	Outro_Mundanity = true,
	Outro_Bloodless = true,
	Outro_Joy = true,
	Outro_StartingOver = true,
	-- #endregion
	-- #region Locations
	Location_Tartarus = true,
	Location_Tartarus_Short = true,
	Tartarus = true,
	Location_Asphodel = true,
	Location_Asphodel_Short = true,
	Asphodel = true,
	Location_Elysium = true,
	Location_Elysium_Short = true,
	Elysium = true,
	Location_Styx = true,
	Location_Styx_Short = true,
	Styx = true,
	Location_Challenge = true,
	Challenge = true,
	Location_Surface = true,
	Surface = true,
	Location_Surface_Alt = true,
	Surface_Alt = true,
	-- #endregion
	-- #region Death
	OutroDeathMessage = true,
	PostEndingDeathMessage = "ModsNikkelMHadesBiomes_PostEndingDeathMessage",
	DeathMessage = "ModsNikkelMHadesBiomes_DeathMessage",
	OutroDeathMessageAlt = "ModsNikkelMHadesBiomes_OutroDeathMessageAlt",
	-- #endregion
	-- #region Vanquished Messages
	BiomeClearedMessage = true,
	HarpyDefeatedMessage = true,
	HarpiesDefeatedMessage = true,
	HydraDefeatedMessage = true,
	HydraDefeatedMessage02 = true,
	TheseusDefeatedMessage = true,
	MinotaurDefeatedMessage = true,
	HadesDefeatedMessage = true,
	ThanatosMessage = true,
	CrawlerDefeatedMessage = "ModsNikkelMHadesBiomes_CrawlerDefeatedMessage",
	-- #endregion
	-- #region Keepsake/Pet messages
	AchillesPatroclusSignoff = true,
	AchillesPatroclusSignoff_AssistMax = true,
	MegaeraSignoff = true,
	MegaeraSignoff_AssistMax_A = true,
	MegaeraSignoff_AssistMax_B = true,
	ThanatosSignoff = true,
	ThanatosSignoff_AssistMax_A = true,
	ThanatosSignoff_AssistMax_B = true,
	DusaSignoff = true,
	DusaSignoff_AssistMax = true,
	SkellySignoff = true,
	SkellySignoff_AssistMax = true,
	SisyphusSignoff = true,
	SisyphusSignoff_Max = true,
	SisyphusBouldySignoff = true,
	SisyphusBouldySignoff_AssistMax = true,
	EurydiceSignoff = true,
	EurydiceSignoff_Max = true,
	PatroclusSignoff = true,
	PatroclusSignoff_Max = true,
	PersephoneSignoff = true,
	Persephone_SignoffMax = true,
	HadesSignoff = true,
	Hades_SignoffMax = true,
	-- #endregion
	-- #region Traits
	FuryAssistTrait_Rack = true,
	FuryAssistTrait_Delta = true,
	FuryAssistTrait = true,
	ThanatosAssistTrait_Rack = true,
	ThanatosAssistTrait_Delta = true,
	ThanatosAssistTrait = true,
	SisyphusAssistTrait_Rack = true,
	SisyphusAssistTrait_Delta = true,
	SisyphusAssistTrait = true,
	SkellyAssistTrait_Rack = true,
	SkellyAssistTrait_Delta = true,
	SkellyAssistTrait = true,
	DusaAssistTrait_Rack = true,
	DusaAssistTrait_Delta = true,
	DusaAssistTrait = true,
	AchillesPatroclusAssistTrait_Rack = true,
	AchillesPatroclusAssistTrait_Delta = true,
	AchillesPatroclusAssistTrait = true,
	-- #endregion
	-- #region RunHistory
	RunHistoryScreenResult_Tartarus = true,
	RunHistoryScreenResult_A_MiniBoss01 = true,
	RunHistoryScreenResult_A_MiniBoss02 = true,
	RunHistoryScreenResult_A_MiniBoss03 = true,
	RunHistoryScreenResult_A_Boss01 = true,
	RunHistoryScreenResult_A_Boss02 = true,
	RunHistoryScreenResult_A_Boss03 = true,
	RunHistoryScreenResult_Asphodel = true,
	RunHistoryScreenResult_B_Wrapping01 = true,
	RunHistoryScreenResult_B_MiniBoss01 = true,
	RunHistoryScreenResult_B_MiniBoss02 = true,
	RunHistoryScreenResult_B_Boss01 = true,
	RunHistoryScreenResult_Elysium = true,
	RunHistoryScreenResult_C_MiniBoss01 = true,
	RunHistoryScreenResult_C_MiniBoss02 = true,
	RunHistoryScreenResult_C_Boss01 = true,
	RunHistoryScreenResult_Styx = true,
	RunHistoryScreenResult_D_Boss01 = true,
	RunHistoryScreenResult_CharonFight01 = true,
	RunHistoryScreenResult_Challenge = true,
	RunHistoryScreen_Assist = true,
	RunHistoryScreen_Cleared = "ModsNikkelMHadesBiomes_RunHistoryScreen_Cleared",
	-- #endregion
	-- #region Victory Screen messages
	ClearNumOne = "ModsNikkelMHadesBiomes_RunClear_ClearNumOne",
	ClearNumTen = "ModsNikkelMHadesBiomes_RunClear_ClearNumTen",
	ClearNumFifty = "ModsNikkelMHadesBiomes_RunClear_ClearNumFifty",
	ClearNumOneHundred = "ModsNikkelMHadesBiomes_RunClear_ClearNumOneHundred",
	ClearNumTwoFifty = "ModsNikkelMHadesBiomes_RunClear_ClearNumTwoFifty",
	ClearNumFiveHundred = "ModsNikkelMHadesBiomes_RunClear_ClearNumFiveHundred",
	ClearNearDeath = "ModsNikkelMHadesBiomes_RunClear_ClearNearDeath",
	ClearFullHealth = "ModsNikkelMHadesBiomes_RunClear_ClearFullHealth",
	ClearHighMaxHealth = "ModsNikkelMHadesBiomes_RunClear_ClearHighMaxHealth",
	ClearTimeFast = "ModsNikkelMHadesBiomes_RunClear_ClearTimeFast",
	ClearTimeVeryFast = "ModsNikkelMHadesBiomes_RunClear_ClearTimeVeryFast",
	ClearTimeSlow = "ModsNikkelMHadesBiomes_RunClear_ClearTimeSlow",
	ClearMoneyNone = "ModsNikkelMHadesBiomes_RunClear_ClearMoneyNone",
	ClearMoneyHigh = "ModsNikkelMHadesBiomes_RunClear_ClearMoneyHigh",
	ClearMetaPointsInvestedNone = "ModsNikkelMHadesBiomes_RunClear_ClearMetaPointsInvestedNone",
	ClearNoOlympianBoons = "ModsNikkelMHadesBiomes_RunClear_ClearNoOlympianBoons",
	ClearAllStoryRooms = "ModsNikkelMHadesBiomes_RunClear_ClearAllStoryRooms",
	ClearAllReprieveRooms = "ModsNikkelMHadesBiomes_RunClear_ClearAllReprieveRooms",
	ClearAllShopRooms = "ModsNikkelMHadesBiomes_RunClear_ClearAllShopRooms",
	ClearRequiredTraitsZeus = "ModsNikkelMHadesBiomes_RunClear_ClearRequiredTraitsZeus",
	ClearRequiredTraitsPoseidon = "ModsNikkelMHadesBiomes_RunClear_ClearRequiredTraitsPoseidon",
	ClearRequiredTraitsAres = "ModsNikkelMHadesBiomes_RunClear_ClearRequiredTraitsAres",
	ClearRequiredTraitsAphrodite = "ModsNikkelMHadesBiomes_RunClear_ClearRequiredTraitsAphrodite",
	ClearRequiredTraitsDemeter = "ModsNikkelMHadesBiomes_RunClear_ClearRequiredTraitsDemeter",
	ClearRequiredTraitsHermes = "ModsNikkelMHadesBiomes_RunClear_ClearRequiredTraitsHermes",
	ClearRequiredTraitsChaos = "ModsNikkelMHadesBiomes_RunClear_ClearRequiredTraitsChaos",
	ClearSynergyTraits = "ModsNikkelMHadesBiomes_RunClear_ClearSynergyTraits",
	ClearLegendaryTraits = "ModsNikkelMHadesBiomes_RunClear_ClearLegendaryTraits",
	ClearChallengeSwitches = "ModsNikkelMHadesBiomes_RunClear_ClearChallengeSwitches",
	ClearDevotionEncounters = "ModsNikkelMHadesBiomes_RunClear_ClearDevotionEncounters",
	ClearShrineChallengeEncounters = "ModsNikkelMHadesBiomes_RunClear_ClearShrineChallengeEncounters",
	ClearMiniBossEncounters = "ModsNikkelMHadesBiomes_RunClear_ClearMiniBossEncounters",
	ClearConsecutiveHigh = "ModsNikkelMHadesBiomes_RunClear_ClearConsecutiveHigh",
	ClearHealItems = "ModsNikkelMHadesBiomes_RunClear_ClearHealItems",
	ClearStackUpgrades = "ModsNikkelMHadesBiomes_RunClear_ClearStackUpgrades",
	ClearConsolationPrizes = "ModsNikkelMHadesBiomes_RunClear_ClearConsolationPrizes",
	ClearManyLastStands = "ModsNikkelMHadesBiomes_RunClear_ClearManyLastStands",
	ClearShutDownThanatos = "ModsNikkelMHadesBiomes_RunClear_ClearShutDownThanatos",
	ClearManyTraitsSold = "ModsNikkelMHadesBiomes_RunClear_ClearManyTraitsSold",
	-- Not used/applicable
	-- ClearRequiredTraitsAthena = "ModsNikkelMHadesBiomes_RunClear_ClearRequiredTraitsAthena",
	-- ClearRequiredTraitsArtemis = "ModsNikkelMHadesBiomes_RunClear_ClearRequiredTraitsArtemis",
	-- ClearRequiredTraitsDionysus = "ModsNikkelMHadesBiomes_RunClear_ClearRequiredTraitsDionysus",
	-- ClearWeaponsFiredWrath = "ModsNikkelMHadesBiomes_RunClear_ClearWeaponsFiredWrath",
	-- ClearWeaponsFiredRanged = "ModsNikkelMHadesBiomes_RunClear_ClearWeaponsFiredRanged",
	-- ClearFishCaught = "ModsNikkelMHadesBiomes_RunClear_ClearFishCaught",
	-- ClearConsecutiveLow = "ModsNikkelMHadesBiomes_RunClear_ClearConsecutiveLow",
	-- ClearGiftDrops = "ModsNikkelMHadesBiomes_RunClear_ClearGiftDrops",
	-- ClearLockKeyDrops = "ModsNikkelMHadesBiomes_RunClear_ClearLockKeyDrops",
	-- #endregion
	-- #region QuestData/Minor Prophecies
	UnknownCondition_Meet = true,
	-- #endregion
	-- #region Misc
	PassiveItem = true,
	Assist = true,
	RageMeter = true,
	_PlayerUnit = true,
	AssistTraitsPermitted_Title = true,
	AssistTraitsPermitted_Subtitle = true,
	Codex_Summon_Locked = true,
	-- #endregion
	-- #region Credits
	InGameCredits_Craft_Amir = true,
	InGameCredits_Name_Amir = true,
	InGameCredits_Craft_Gavin = true,
	InGameCredits_Name_Gavin = true,
	InGameCredits_Craft_Greg = true,
	InGameCredits_Name_Greg = true,
	InGameCredits_Craft_Andrew = true,
	InGameCredits_Name_Andrew = true,
	InGameCredits_Craft_Darren = true,
	InGameCredits_Name_Darren = true,
	InGameCredits_Craft_Jen = true,
	InGameCredits_Name_Jen = true,
	InGameCredits_Craft_Logan = true,
	InGameCredits_Name_Logan = true,
	InGameCredits_Craft_Josh = true,
	InGameCredits_Name_Josh = true,
	InGameCredits_Craft_JP = true,
	InGameCredits_Name_JP = true,
	InGameCredits_Craft_Dexter = true,
	InGameCredits_Name_Dexter = true,
	InGameCredits_Craft_Ed = true,
	InGameCredits_Name_Ed = true,
	InGameCredits_Craft_Alice = true,
	InGameCredits_Name_Alice = true,
	InGameCredits_Craft_Joanne = true,
	InGameCredits_Name_Joanne = true,
	InGameCredits_Craft_Caitlin = true,
	InGameCredits_Name_Caitlin = true,
	InGameCredits_Craft_Paige = true,
	InGameCredits_Name_Paige = true,
	InGameCredits_Craft_Thinh = true,
	InGameCredits_Name_Thinh = true,
	InGameCredits_Craft_Will = true,
	InGameCredits_Name_Will = true,
	InGameCredits_Craft_Nikola = true,
	InGameCredits_Name_Nikola = true,
	InGameCredits_Craft_Jesse = true,
	InGameCredits_Name_Jesse = true,
	InGameCredits_Header_AdditionalCredits = true,
	InGameCredits_Craft_Michael = true,
	InGameCredits_Name_Michael = true,
	InGameCredits_Craft_Camilo = true,
	InGameCredits_Name_Camilo = true,
	InGameCredits_Craft_Morgan = true,
	InGameCredits_Name_Morgan = true,
	InGameCredits_Craft_Ashley = true,
	InGameCredits_Name_Ashley = true,
	InGameCredits_Craft_Andre = true,
	InGameCredits_Name_Andre = true,
	InGameCredits_Craft_Tyler = true,
	InGameCredits_Name_Tyler = true,
	InGameCredits_Craft_Brad = true,
	InGameCredits_Name_Brad = true,
	InGameCredits_Craft_James = true,
	InGameCredits_Name_James = true,
	InGameCredits_Craft_Allison = true,
	InGameCredits_Name_Allison = true,
	InGameCredits_Craft_Ellis = true,
	InGameCredits_Name_Ellis = true,
	InGameCredits_Craft_SDL = true,
	InGameCredits_Company_SDL = true,
	InGameCredits_Craft_84 = true,
	InGameCredits_Company_84 = true,
	InGameCredits_Name_84_1 = true,
	InGameCredits_Name_84_2 = true,
	InGameCredits_Name_84_3 = true,
	InGameCredits_Name_84_4 = true,
	InGameCredits_Name_84_4_1 = true,
	InGameCredits_Name_84_5 = true,
	InGameCredits_Name_84_6 = true,
	InGameCredits_Name_84_7 = true,
	InGameCredits_Name_84_8 = true,
	InGameCredits_Name_84_9 = true,
	InGameCredits_Craft_PlasticFern = true,
	InGameCredits_Company_PlasticFern = true,
	InGameCredits_Name_PlasticFern1 = true,
	InGameCredits_Name_PlasticFern2 = true,
	InGameCredits_Name_PlasticFern3 = true,
	InGameCredits_Craft_Hans = true,
	InGameCredits_Name_Hans = true,
	InGameCredits_Craft_Xing = true,
	InGameCredits_Name_Xing = true,
	InGameCredits_Craft_Shaun = true,
	InGameCredits_Name_Shaun = true,
	InGameCredits_Craft_DavidRosen = true,
	InGameCredits_Name_DavidRosen = true,
	InGameCredits_Craft_Confetti = true,
	InGameCredits_Company_Confetti = true,
	InGameCredits_Name_Mykhailo = true,
	InGameCredits_Name_Ajay = true,
	InGameCredits_Name_Devansh = true,
	InGameCredits_Name_Erfan = true,
	InGameCredits_Name_Konstantin = true,
	InGameCredits_Name_DavidErler = true,
	InGameCredits_Name_Manas = true,
	InGameCredits_Name_Antoine = true,
	InGameCredits_Name_Olaf = true,
	InGameCredits_Name_DavidSrour = true,
	InGameCredits_Name_Alex = true,
	InGameCredits_Name_Ethan = true,
	InGameCredits_Name_Wolfgang = true,
	InGameCredits_Header_Cast = true,
	InGameCredits_Cast_Logan = true,
	InGameCredits_Cast_Darren = true,
	InGameCredits_Cast_Avalon = true,
	InGameCredits_Name_Avalon = true,
	InGameCredits_Cast_Chris = true,
	InGameCredits_Name_Chris = true,
	InGameCredits_Cast_Marin = true,
	InGameCredits_Name_Marin = true,
	InGameCredits_Cast_Cyrus = true,
	InGameCredits_Name_Cyrus = true,
	InGameCredits_Cast_Courtney = true,
	InGameCredits_Name_Courtney = true,
	InGameCredits_Cast_Jamie = true,
	InGameCredits_Name_Jamie = true,
	InGameCredits_Cast_Peter = true,
	InGameCredits_Name_Peter = true,
	InGameCredits_Cast_Laila = true,
	InGameCredits_Name_Laila = true,
	InGameCredits_Cast_AndrewMarks = true,
	InGameCredits_Name_AndrewMarks = true,
	InGameCredits_Cast_Francesca = true,
	InGameCredits_Name_Francesca = true,
	InGameCredits_Cast_Ben = true,
	InGameCredits_Name_Ben = true,
	InGameCredits_Cast_Michael = true,
	InGameCredits_Cast_Greg = true,
	InGameCredits_Cast_Kelly = true,
	InGameCredits_Name_Kelly = true,
	InGameCredits_Cast_SoloHiggins = true,
	InGameCredits_Name_SoloHiggins = true,
	InGameCredits_Header_MusicProduction = true,
	InGameCredits_Music_MusicAndLyrics = true,
	InGameCredits_Music_Vocals = true,
	InGameCredits_Music_Mastering = true,
	InGameCredits_Music_AbbeyRoad = true,
	InGameCredits_Music_Craft_RecordingEngineer = true,
	InGameCredits_Music_Name_RecordingEngineer = true,
	InGameCredits_Music_Craft_AssistantEngineer = true,
	InGameCredits_Music_Name_AssistantEngineer1 = true,
	InGameCredits_Music_Name_AssistantEngineer2 = true,
	InGameCredits_Music_Craft_MusicPrep = true,
	InGameCredits_Music_Name_MusicPrep = true,
	InGameCredits_Music_Craft_ScoreEditor = true,
	InGameCredits_Music_Name_ScoreEditor = true,
	InGameCredits_Music_Craft_OrchestralMixing = true,
	InGameCredits_Music_Name_OrchestralMixing = true,
	InGameCredits_Music_Craft_Austin = true,
	InGameCredits_Music_Name_Austin = true,
	InGameCredits_Music_Craft_Flute = true,
	InGameCredits_Music_Name_Flute = true,
	InGameCredits_Music_Craft_Oboe = true,
	InGameCredits_Music_Name_Oboe = true,
	InGameCredits_Music_Craft_Clarinet = true,
	InGameCredits_Music_Name_Clarinet = true,
	InGameCredits_Music_Craft_Trombone = true,
	InGameCredits_Music_Name_Trombone1 = true,
	InGameCredits_Music_Name_Trombone2 = true,
	InGameCredits_Music_Name_Trombone3 = true,
	InGameCredits_Music_Craft_Harp = true,
	InGameCredits_Music_Name_Harp = true,
	InGameCredits_Music_Craft_Percussion = true,
	InGameCredits_Music_Name_Percussion1 = true,
	InGameCredits_Music_Name_Percussion2 = true,
	InGameCredits_Music_Craft_Violin1 = true,
	InGameCredits_Music_Name_Violin1 = true,
	InGameCredits_Music_Craft_Violin2 = true,
	InGameCredits_Music_Name_Violin2 = true,
	InGameCredits_Music_Craft_Viola = true,
	InGameCredits_Music_Name_Viola = true,
	InGameCredits_Music_Craft_Cello = true,
	InGameCredits_Music_Name_Cello = true,
	InGameCredits_Music_Craft_Bass = true,
	InGameCredits_Music_Name_Bass = true,
	InGameCredits_Music_Craft_Librarian = true,
	InGameCredits_Music_Name_Librarian = true,
	InGameCredits_Music_Craft_Reader = true,
	InGameCredits_Music_Name_Reader = true,
	InGameCredits_Music_Craft_GuitarSoloists = true,
	InGameCredits_Music_Name_GuitarSoloists1 = true,
	InGameCredits_Music_Name_GuitarSoloists2 = true,
	InGameCredits_Header_SpecialThanks = true,
	InGameCredits_Name_ST1 = true,
	InGameCredits_Name_ST2 = true,
	InGameCredits_Name_ST3 = true,
	InGameCredits_Name_ST4 = true,
	InGameCredits_Name_ST5 = true,
	InGameCredits_Name_ST6 = true,
	InGameCredits_Name_ST7 = true,
	InGameCredits_Name_ST8 = true,
	InGameCredits_Name_ST9 = true,
	InGameCredits_Name_ST10 = true,
	InGameCredits_Name_ST11 = true,
	InGameCredits_Name_ST12 = true,
	InGameCredits_Name_ST13 = true,
	InGameCredits_Name_ST14 = true,
	InGameCredits_Name_ST15 = true,
	InGameCredits_Name_ST16 = true,
	InGameCredits_Name_ST17 = true,
	InGameCredits_Name_ST18 = true,
	InGameCredits_Name_ST19 = true,
	InGameCredits_Name_ST20 = true,
	InGameCredits_Name_ST21 = true,
	InGameCredits_Name_ST22 = true,
	InGameCredits_Name_ST23 = true,
	InGameCredits_Name_ST24 = true,
	InGameCredits_Name_ST25 = true,
	InGameCredits_Name_ST26 = true,
	InGameCredits_Name_ST27 = true,
	InGameCredits_Name_ST28 = true,
	InGameCredits_Name_ST29 = true,
	InGameCredits_Name_ST30 = true,
	InGameCredits_Name_ST31 = true,
	InGameCredits_Name_ST32 = true,
	InGameCredits_Name_ST33 = true,
	InGameCredits_Name_ST34 = true,
	InGameCredits_Name_ST35 = true,
	InGameCredits_Name_ST36 = true,
	InGameCredits_Name_ST37 = true,
	InGameCredits_Name_ST38 = true,
	InGameCredits_Name_ST39 = true,
	InGameCredits_Name_ST40 = true,
	InGameCredits_Name_ST41 = true,
	InGameCredits_Name_ST42 = true,
	InGameCredits_Name_ST43 = true,
	InGameCredits_Name_ST44 = true,
	InGameCredits_Name_ST45 = true,
	InGameCredits_Name_ST46 = true,
	InGameCredits_Name_ST47 = true,
	InGameCredits_Name_ST48 = true,
	InGameCredits_Name_ST49 = true,
	InGameCredits_Name_ST50 = true,
	InGameCredits_Name_ST51 = true,
	InGameCredits_Name_ST52 = true,
	InGameCredits_Name_ST53 = true,
	InGameCredits_Name_ST54 = true,
	InGameCredits_Name_ST55 = true,
	InGameCredits_Name_ST56 = true,
	InGameCredits_Name_ST57 = true,
	InGameCredits_Name_ST58 = true,
	InGameCredits_Name_ST59 = true,
	InGameCredits_Name_ST60 = true,
	InGameCredits_Header_Community = true,
	InGameCredits_Craft_Moderators = true,
	InGameCredits_Name_Moderator1 = true,
	InGameCredits_Name_Moderator2 = true,
	InGameCredits_Name_Moderator3 = true,
	InGameCredits_Name_Moderator4 = true,
	InGameCredits_Name_Moderator5 = true,
	InGameCredits_Name_Moderator6 = true,
	InGameCredits_Name_Moderator7 = true,
	InGameCredits_Name_Moderator8 = true,
	InGameCredits_Name_Moderator9 = true,
	InGameCredits_Name_Moderator10 = true,
	InGameCredits_Name_Moderator11 = true,
	InGameCredits_Name_Moderator12 = true,
	InGameCredits_Name_Moderator13 = true,
	InGameCredits_Name_Moderator14 = true,
	InGameCredits_Craft_Translators = true,
	InGameCredits_Language_French = true,
	InGameCredits_Name_French1 = true,
	InGameCredits_Name_French2 = true,
	InGameCredits_Name_French3 = true,
	InGameCredits_Language_Italian = true,
	InGameCredits_Name_Italian1 = true,
	InGameCredits_Name_Italian2 = true,
	InGameCredits_Name_Italian3 = true,
	InGameCredits_Language_German = true,
	InGameCredits_Name_German1 = true,
	InGameCredits_Name_German2 = true,
	InGameCredits_Name_German3 = true,
	InGameCredits_Name_German4 = true,
	InGameCredits_Language_Spanish = true,
	InGameCredits_Name_Spanish1 = true,
	InGameCredits_Name_Spanish2 = true,
	InGameCredits_Name_Spanish3 = true,
	InGameCredits_Name_Spanish4 = true,
	InGameCredits_Language_Russian = true,
	InGameCredits_Name_Russian1 = true,
	InGameCredits_Name_Russian2 = true,
	InGameCredits_Name_Russian3 = true,
	InGameCredits_Name_Russian4 = true,
	InGameCredits_Language_Polish = true,
	InGameCredits_Name_Polish1 = true,
	InGameCredits_Name_Polish2 = true,
	InGameCredits_Name_Polish3 = true,
	InGameCredits_Name_Polish4 = true,
	InGameCredits_Language_Brazilian_Portuguese = true,
	InGameCredits_Name_PTBR1 = true,
	InGameCredits_Name_PTBR2 = true,
	InGameCredits_Name_PTBR3 = true,
	InGameCredits_Name_PTBR4 = true,
	InGameCredits_Language_Chinese = true,
	InGameCredits_Name_Chinese1 = true,
	InGameCredits_Name_Chinese2 = true,
	InGameCredits_Name_Chinese3 = true,
	InGameCredits_Name_Chinese8 = true,
	InGameCredits_Name_Chinese4 = true,
	InGameCredits_Name_Chinese5 = true,
	InGameCredits_Name_Chinese6 = true,
	InGameCredits_Name_Chinese7 = true,
	InGameCredits_Language_Korean = true,
	InGameCredits_Name_Korean1 = true,
	InGameCredits_Name_Korean2 = true,
	InGameCredits_Name_Korean3 = true,
	InGameCredits_Craft_BetaTesters = true,
	InGameCredits_Name_Tester1 = true,
	InGameCredits_Name_Tester2 = true,
	InGameCredits_Name_Tester3 = true,
	InGameCredits_Name_Tester4 = true,
	InGameCredits_Name_Tester5 = true,
	InGameCredits_Name_Tester6 = true,
	InGameCredits_Name_Tester7 = true,
	InGameCredits_Name_Tester8 = true,
	InGameCredits_Name_Tester9 = true,
	InGameCredits_Name_Tester10 = true,
	InGameCredits_Name_Tester11 = true,
	InGameCredits_Name_Tester12 = true,
	InGameCredits_Name_Tester13 = true,
	InGameCredits_Name_Tester14 = true,
	InGameCredits_Name_Tester15 = true,
	InGameCredits_Name_Tester16 = true,
	InGameCredits_Name_Tester17 = true,
	InGameCredits_Name_Tester18 = true,
	InGameCredits_Name_Tester19 = true,
	InGameCredits_Name_Tester20 = true,
	InGameCredits_Name_Tester21 = true,
	InGameCredits_Name_Tester22 = true,
	InGameCredits_Name_Tester23 = true,
	InGameCredits_Name_Tester24 = true,
	InGameCredits_Name_Tester25 = true,
	InGameCredits_Name_Tester26 = true,
	InGameCredits_Name_Tester27 = true,
	InGameCredits_Name_Tester28 = true,
	InGameCredits_Name_Tester29 = true,
	InGameCredits_Name_Tester30 = true,
	InGameCredits_Name_Tester31 = true,
	InGameCredits_Name_Tester32 = true,
	InGameCredits_Name_Tester33 = true,
	InGameCredits_Name_Tester34 = true,
	InGameCredits_Name_Tester35 = true,
	InGameCredits_Name_Tester36 = true,
	InGameCredits_Name_Tester37 = true,
	InGameCredits_Name_Tester38 = true,
	InGameCredits_Name_Tester39 = true,
	InGameCredits_Name_Tester40 = true,
	InGameCredits_Name_Tester41 = true,
	InGameCredits_Name_Tester42 = true,
	InGameCredits_Name_Tester43 = true,
	InGameCredits_Name_Tester44 = true,
	InGameCredits_Name_Tester45 = true,
	InGameCredits_Name_Tester46 = true,
	InGameCredits_Name_Tester47 = true,
	InGameCredits_Name_Tester48 = true,
	InGameCredits_Name_Tester49 = true,
	InGameCredits_Name_Tester50 = true,
	InGameCredits_Name_Tester51 = true,
	InGameCredits_Name_Tester52 = true,
	InGameCredits_Name_Tester53 = true,
	InGameCredits_Name_Tester54 = true,
	InGameCredits_Name_Tester55 = true,
	InGameCredits_Name_Tester56 = true,
	InGameCredits_Info_EarlyAccess = true,
	InGameCredits_Header_Acknowledgements = true,
	InGameCredits_Info_Acknowledgements_Open = true,
	InGameCredits_Name_Ack1 = true,
	InGameCredits_Name_Ack2 = true,
	InGameCredits_Name_Ack3 = true,
	InGameCredits_Name_Ack4 = true,
	InGameCredits_Name_Ack5 = true,
	InGameCredits_Name_Ack6 = true,
	InGameCredits_Name_Ack7 = true,
	InGameCredits_Name_Ack8 = true,
	InGameCredits_Name_Ack9 = true,
	InGameCredits_Name_Ack10 = true,
	InGameCredits_Name_Ack11 = true,
	InGameCredits_Name_Ack12 = true,
	InGameCredits_Name_Ack13 = true,
	InGameCredits_Name_Ack14 = true,
	InGameCredits_Name_Ack15 = true,
	InGameCredits_Name_Ack16 = true,
	InGameCredits_Name_Ack17 = true,
	InGameCredits_Name_Ack18 = true,
	InGameCredits_Name_Ack19 = true,
	InGameCredits_Name_Ack20 = true,
	InGameCredits_Name_Ack21 = true,
	InGameCredits_Name_Ack22 = true,
	InGameCredits_Name_Ack23 = true,
	InGameCredits_Name_Ack24 = true,
	InGameCredits_Name_Ack25 = true,
	InGameCredits_Name_Ack26 = true,
	InGameCredits_Name_Ack27 = true,
	InGameCredits_Name_Ack28 = true,
	InGameCredits_Name_Ack29 = true,
	InGameCredits_Name_Ack30 = true,
	InGameCredits_Name_Ack31 = true,
	InGameCredits_Info_Acknowledgements_Close = true,
	InGameCredits_Header_Legal = true,
	InGameCredits_Legal_Line1 = true,
	InGameCredits_Legal_Line2 = true,
	InGameCredits_Legal_Line3 = true,
	InGameCredits_Legal_Line4 = true,
	InGameCredits_Info_Signoff = true,
	-- #endregion
}
-- These are aliases that should be added to all HelpText files
-- The key is the Id, the value is the InheritFrom
mod.HadesHelpTextAliases = {
	Theseus2 = "Theseus",
	Minotaur2 = "Minotaur",
	Hades = "NPC_LordHades_01",
	NPC_Hades_Story_02 = "NPC_LordHades_01",
	NPC_Thanatos_Field_01 = "NPC_Thanatos_01",
	NPC_Orpheus_Story_01 = "NPC_Orpheus_01",
	NPC_Achilles_Story_01 = "NPC_Achilles_01",
	AchillesPatroclusReunion_B = "AchillesPatroclusReunion_A",
	AchillesPatroclusReunion_C = "AchillesPatroclusReunion_A",
	NPC_Patroclus_Standing_01 = "NPC_Patroclus_01",
	Charon = "NPC_Charon_01",
	ClearedCerberus_Alt1_Title = "ClearedCerberus_Title",
	ClearedCerberus_Alt2_Title = "ClearedCerberus_Title",
	CharProtag = "NPC_Zagreus_Past_01",
	HitAndRunUnitElite = "HitAndRunUnit",
	CharAchilles = "Achilles",
	CharOrpheus = "Orpheus",
	CharThanatos = "Thanatos",
	CharSisyphus = "Sisyphus",
	CharEurydice = "NPC_Eurydice_01",
	CharPatroclus = "NPC_Patroclus_01",
	CharBouldy = "ModsNikkelMHadesBiomes_NPC_Bouldy_01",
}

-- List of Speakers for which the entries in the _NPCData files should be copied
mod.HadesNPCTextSpeakers = {
	Sisyphus = true,
	Eurydice = true,
	Patroclus = true,
	Thanatos = true,
	Persephone = true, -- For now - we don't need all of her voicelines, as they are split between Surface and Home
	-- Cerberus Storyteller voicelines from mod.StorytellerVoicelines
	-- ZagreusField voicelines from mod.ZagreusFieldVoicelines
}

-- Keys to be removed from the CodexText files before hooking them into Hades II
-- These keys are either duplicates or simply not required
mod.HadesCodexTextKeyRemovals = {
	"CodexData_Chaos_01",
	"CodexData_Demeter_01",
	"CodexData_Skelly_01",
	"CodexData_Dusa_01",
}
-- Mappings for Codex entries that exist in both games, but need to be renamed to avoid conflicts
mod.HadesCodexTextNameMappings = {
	CodexData_BloodlessBerserker_01 = "ModsNikkelMHadesBiomes_CodexData_BloodlessBerserker_01",
	CodexData_Hades_01 = "ModsNikkelMHadesBiomes_CodexData_Hades_01",
	CodexData_Hades_02 = "ModsNikkelMHadesBiomes_CodexData_Hades_02",
	CodexData_Persephone_01 = "ModsNikkelMHadesBiomes_CodexData_Persephone_01",
	CodexData_Thanatos_01 = "ModsNikkelMHadesBiomes_CodexData_Thanatos_01",
	CodexData_Megaera_01 = "ModsNikkelMHadesBiomes_CodexData_Megaera_01",
}

-- Mappings for various game object modifications that need to be applied when the run is started/ended
--[[
	Format is, for example:
	EffectData = {
		DamageEchoEffect = {
			Vfx = {
				Default = "ZeusEchoDebuff",
				Modded = "ModsNikkelMHadesBiomesZeusEchoDebuff",
			},
		},
	},
]]
mod.ModdedGameObjectModifications = {}

-- Mappings for Effect VFX to be swapped out, used in EffectPresentation.lua
mod.EffectVfxMappings = {
	ZeusEchoDebuff = "ModsNikkelMHadesBiomesZeusEchoDebuff",
}
