-- Contains file names/patterns required for copying over files from the Hades installation, and for uninstalling the mod

AudioFileMappings = {
	["Enemies.bank"] = "EnemiesModsNikkelMHadesBiomes.bank",
	["Sounds.bank"] = "SoundsModsNikkelMHadesBiomes.bank",
	["Tartarus.bank"] = "TartarusModsNikkelMHadesBiomes.bank",
}

-- Voiceover .txt and .fsb file names
-- The file name must be the same as the event names within the file
VoiceoverFileNames = {
	"MegaeraField",
}

PackageFileMappings = {
	-- Tartarus map package
	["Tartarus.pkg"] = "1080p\\TartarusModsNikkelMHadesBiomes.pkg",
	["Tartarus.pkg_manifest"] = "1080p\\TartarusModsNikkelMHadesBiomes.pkg_manifest",
	["720p\\Tartarus.pkg"] = "720p\\TartarusModsNikkelMHadesBiomes.pkg",
	["720p\\Tartarus.pkg_manifest"] = "720p\\TartarusModsNikkelMHadesBiomes.pkg_manifest",
	-- Enemies
	["RoomManager.pkg"] = "1080p\\RoomManagerModsNikkelMHadesBiomes.pkg",
	["RoomManager.pkg_manifest"] = "1080p\\RoomManagerModsNikkelMHadesBiomes.pkg_manifest",
	["720p\\RoomManager.pkg"] = "720p\\RoomManagerModsNikkelMHadesBiomes.pkg",
	["720p\\RoomManager.pkg_manifest"] = "720p\\RoomManagerModsNikkelMHadesBiomes.pkg_manifest",
	-- Fx
	["Fx.pkg"] = "1080p\\FxModsNikkelMHadesBiomes.pkg",
	["Fx.pkg_manifest"] = "1080p\\FxModsNikkelMHadesBiomes.pkg_manifest",
	["720p\\Fx.pkg"] = "720p\\FxModsNikkelMHadesBiomes.pkg",
	["720p\\Fx.pkg_manifest"] = "720p\\FxModsNikkelMHadesBiomes.pkg_manifest",
}

BikFileMappings = {
	-- Enemy animations
	-- Wretch Glutton/PunchingBagUnit
	["EnemyWretchGluttonAttack_Bink.bik"] = "1080p\\EnemyWretchGluttonAttack_Bink.bik",
	["EnemyWretchGluttonAttack_Bink.bik_atlas"] = "1080p\\EnemyWretchGluttonAttack_Bink.bik_atlas",
	["720p\\EnemyWretchGluttonAttack_Bink.bik"] = "720p\\EnemyWretchGluttonAttack_Bink.bik",
	["720p\\EnemyWretchGluttonAttack_Bink.bik_atlas"] = "720p\\EnemyWretchGluttonAttack_Bink.bik_atlas",
	["EnemyWretchGluttonDeathVFX_Bink.bik"] = "1080p\\EnemyWretchGluttonDeathVFX_Bink.bik",
	["EnemyWretchGluttonDeathVFX_Bink.bik_atlas"] = "1080p\\EnemyWretchGluttonDeathVFX_Bink.bik_atlas",
	["720p\\EnemyWretchGluttonDeathVFX_Bink.bik"] = "720p\\EnemyWretchGluttonDeathVFX_Bink.bik",
	["720p\\EnemyWretchGluttonDeathVFX_Bink.bik_atlas"] = "720p\\EnemyWretchGluttonDeathVFX_Bink.bik_atlas",
	["EnemyWretchGluttonIdle_Bink.bik"] = "1080p\\EnemyWretchGluttonIdle_Bink.bik",
	["EnemyWretchGluttonIdle_Bink.bik_atlas"] = "1080p\\EnemyWretchGluttonIdle_Bink.bik_atlas",
	["720p\\EnemyWretchGluttonIdle_Bink.bik"] = "720p\\EnemyWretchGluttonIdle_Bink.bik",
	["720p\\EnemyWretchGluttonIdle_Bink.bik_atlas"] = "720p\\EnemyWretchGluttonIdle_Bink.bik_atlas",
	["EnemyWretchGluttonOnHit_Bink.bik"] = "1080p\\EnemyWretchGluttonOnHit_Bink.bik",
	["EnemyWretchGluttonOnHit_Bink.bik_atlas"] = "1080p\\EnemyWretchGluttonOnHit_Bink.bik_atlas",
	["720p\\EnemyWretchGluttonOnHit_Bink.bik"] = "720p\\EnemyWretchGluttonOnHit_Bink.bik",
	["720p\\EnemyWretchGluttonOnHit_Bink.bik_atlas"] = "720p\\EnemyWretchGluttonOnHit_Bink.bik_atlas",
	-- Wretch Thug/HeavyMelee
	["EnemyWretchThugAttack_Bink.bik"] = "1080p\\EnemyWretchThugAttack_Bink.bik",
	["EnemyWretchThugAttack_Bink.bik_atlas"] = "1080p\\EnemyWretchThugAttack_Bink.bik_atlas",
	["720p\\EnemyWretchThugAttack_Bink.bik"] = "720p\\EnemyWretchThugAttack_Bink.bik",
	["720p\\EnemyWretchThugAttack_Bink.bik_atlas"] = "720p\\EnemyWretchThugAttack_Bink.bik_atlas",
	["EnemyWretchThugDeathVFX_Bink.bik"] = "1080p\\EnemyWretchThugDeathVFX_Bink.bik",
	["EnemyWretchThugDeathVFX_Bink.bik_atlas"] = "1080p\\EnemyWretchThugDeathVFX_Bink.bik_atlas",
	["720p\\EnemyWretchThugDeathVFX_Bink.bik"] = "720p\\EnemyWretchThugDeathVFX_Bink.bik",
	["720p\\EnemyWretchThugDeathVFX_Bink.bik_atlas"] = "720p\\EnemyWretchThugDeathVFX_Bink.bik_atlas",
	["EnemyWretchThugIdle_Bink.bik"] = "1080p\\EnemyWretchThugIdle_Bink.bik",
	["EnemyWretchThugIdle_Bink.bik_atlas"] = "1080p\\EnemyWretchThugIdle_Bink.bik_atlas",
	["720p\\EnemyWretchThugIdle_Bink.bik"] = "720p\\EnemyWretchThugIdle_Bink.bik",
	["720p\\EnemyWretchThugIdle_Bink.bik_atlas"] = "720p\\EnemyWretchThugIdle_Bink.bik_atlas",
	["EnemyWretchThugOnHit_Bink.bik"] = "1080p\\EnemyWretchThugOnHit_Bink.bik",
	["EnemyWretchThugOnHit_Bink.bik_atlas"] = "1080p\\EnemyWretchThugOnHit_Bink.bik_atlas",
	["720p\\EnemyWretchThugOnHit_Bink.bik"] = "720p\\EnemyWretchThugOnHit_Bink.bik",
	["720p\\EnemyWretchThugOnHit_Bink.bik_atlas"] = "720p\\EnemyWretchThugOnHit_Bink.bik_atlas",
	["EnemyWretchThugStart_Bink.bik"] = "1080p\\EnemyWretchThugStart_Bink.bik",
	["EnemyWretchThugStart_Bink.bik_atlas"] = "1080p\\EnemyWretchThugStart_Bink.bik_atlas",
	["720p\\EnemyWretchThugStart_Bink.bik"] = "720p\\EnemyWretchThugStart_Bink.bik",
	["720p\\EnemyWretchThugStart_Bink.bik_atlas"] = "720p\\EnemyWretchThugStart_Bink.bik_atlas",
	["EnemyWretchThugWalk_Bink.bik"] = "1080p\\EnemyWretchThugWalk_Bink.bik",
	["EnemyWretchThugWalk_Bink.bik_atlas"] = "1080p\\EnemyWretchThugWalk_Bink.bik_atlas",
	["720p\\EnemyWretchThugWalk_Bink.bik"] = "720p\\EnemyWretchThugWalk_Bink.bik",
	["720p\\EnemyWretchThugWalk_Bink.bik_atlas"] = "720p\\EnemyWretchThugWalk_Bink.bik_atlas",
	-- Disembodied Hand/EnemyWringer
	["Enemy_Wringer_OnHit_Bink.bik"] = "1080p\\Enemy_Wringer_OnHit_Bink.bik",
	["Enemy_Wringer_OnHit_Bink.bik_atlas"] = "1080p\\Enemy_Wringer_OnHit_Bink.bik_atlas",
	["720p\\Enemy_Wringer_OnHit_Bink.bik"] = "720p\\Enemy_Wringer_OnHit_Bink.bik",
	["720p\\Enemy_Wringer_OnHit_Bink.bik_atlas"] = "720p\\Enemy_Wringer_OnHit_Bink.bik_atlas",
	["Enemy_WringerAttack_Bink.bik"] = "1080p\\Enemy_WringerAttack_Bink.bik",
	["Enemy_WringerAttack_Bink.bik_atlas"] = "1080p\\Enemy_WringerAttack_Bink.bik_atlas",
	["720p\\Enemy_WringerAttack_Bink.bik"] = "720p\\Enemy_WringerAttack_Bink.bik",
	["720p\\Enemy_WringerAttack_Bink.bik_atlas"] = "720p\\Enemy_WringerAttack_Bink.bik_atlas",
	["Enemy_WringerDeathVFX_Bink.bik"] = "1080p\\Enemy_WringerDeathVFX_Bink.bik",
	["Enemy_WringerDeathVFX_Bink.bik_atlas"] = "1080p\\Enemy_WringerDeathVFX_Bink.bik_atlas",
	["720p\\Enemy_WringerDeathVFX_Bink.bik"] = "720p\\Enemy_WringerDeathVFX_Bink.bik",
	["720p\\Enemy_WringerDeathVFX_Bink.bik_atlas"] = "720p\\Enemy_WringerDeathVFX_Bink.bik_atlas",
	["Enemy_WringerIdle_Bink.bik"] = "1080p\\Enemy_WringerIdle_Bink.bik",
	["Enemy_WringerIdle_Bink.bik_atlas"] = "1080p\\Enemy_WringerIdle_Bink.bik_atlas",
	["720p\\Enemy_WringerIdle_Bink.bik"] = "720p\\Enemy_WringerIdle_Bink.bik",
	["720p\\Enemy_WringerIdle_Bink.bik_atlas"] = "720p\\Enemy_WringerIdle_Bink.bik_atlas",
	["Enemy_WringerStart_Bink.bik"] = "1080p\\Enemy_WringerStart_Bink.bik",
	["Enemy_WringerStart_Bink.bik_atlas"] = "1080p\\Enemy_WringerStart_Bink.bik_atlas",
	["720p\\Enemy_WringerStart_Bink.bik"] = "720p\\Enemy_WringerStart_Bink.bik",
	["720p\\Enemy_WringerStart_Bink.bik_atlas"] = "720p\\Enemy_WringerStart_Bink.bik_atlas",
	["Enemy_WringerMove_Bink.bik"] = "1080p\\Enemy_WringerMove_Bink.bik",
	["Enemy_WringerMove_Bink.bik_atlas"] = "1080p\\Enemy_WringerMove_Bink.bik_atlas",
	["720p\\Enemy_WringerMove_Bink.bik"] = "720p\\Enemy_WringerMove_Bink.bik",
	["720p\\Enemy_WringerMove_Bink.bik_atlas"] = "720p\\Enemy_WringerMove_Bink.bik_atlas",
	-- Wretch Caster/LightRanged/HadesLightRanged
	["EnemyWretchCasterAttack_Bink.bik"] = "1080p\\EnemyWretchCasterAttack_Bink.bik",
	["EnemyWretchCasterAttack_Bink.bik_atlas"] = "1080p\\EnemyWretchCasterAttack_Bink.bik_atlas",
	["720p\\EnemyWretchCasterAttack_Bink.bik"] = "720p\\EnemyWretchCasterAttack_Bink.bik",
	["720p\\EnemyWretchCasterAttack_Bink.bik_atlas"] = "720p\\EnemyWretchCasterAttack_Bink.bik_atlas",
	["EnemyWretchCasterAttackAlt_Bink.bik"] = "1080p\\EnemyWretchCasterAttackAlt_Bink.bik",
	["EnemyWretchCasterAttackAlt_Bink.bik_atlas"] = "1080p\\EnemyWretchCasterAttackAlt_Bink.bik_atlas",
	["720p\\EnemyWretchCasterAttackAlt_Bink.bik"] = "720p\\EnemyWretchCasterAttackAlt_Bink.bik",
	["720p\\EnemyWretchCasterAttackAlt_Bink.bik_atlas"] = "720p\\EnemyWretchCasterAttackAlt_Bink.bik_atlas",
	["EnemyWretchCasterDeathVFX_Bink.bik"] = "1080p\\EnemyWretchCasterDeathVFX_Bink.bik",
	["EnemyWretchCasterDeathVFX_Bink.bik_atlas"] = "1080p\\EnemyWretchCasterDeathVFX_Bink.bik_atlas",
	["720p\\EnemyWretchCasterDeathVFX_Bink.bik"] = "720p\\EnemyWretchCasterDeathVFX_Bink.bik",
	["720p\\EnemyWretchCasterDeathVFX_Bink.bik_atlas"] = "720p\\EnemyWretchCasterDeathVFX_Bink.bik_atlas",
	["EnemyWretchCasterIdle_Bink.bik"] = "1080p\\EnemyWretchCasterIdle_Bink.bik",
	["EnemyWretchCasterIdle_Bink.bik_atlas"] = "1080p\\EnemyWretchCasterIdle_Bink.bik_atlas",
	["720p\\EnemyWretchCasterIdle_Bink.bik"] = "720p\\EnemyWretchCasterIdle_Bink.bik",
	["720p\\EnemyWretchCasterIdle_Bink.bik_atlas"] = "720p\\EnemyWretchCasterIdle_Bink.bik_atlas",
	["EnemyWretchCasterMove_Bink.bik"] = "1080p\\EnemyWretchCasterMove_Bink.bik",
	["EnemyWretchCasterMove_Bink.bik_atlas"] = "1080p\\EnemyWretchCasterMove_Bink.bik_atlas",
	["720p\\EnemyWretchCasterMove_Bink.bik"] = "720p\\EnemyWretchCasterMove_Bink.bik",
	["720p\\EnemyWretchCasterMove_Bink.bik_atlas"] = "720p\\EnemyWretchCasterMove_Bink.bik_atlas",
	["EnemyWretchCasterOnHit_Bink.bik"] = "1080p\\EnemyWretchCasterOnHit_Bink.bik",
	["EnemyWretchCasterOnHit_Bink.bik_atlas"] = "1080p\\EnemyWretchCasterOnHit_Bink.bik_atlas",
	["720p\\EnemyWretchCasterOnHit_Bink.bik"] = "720p\\EnemyWretchCasterOnHit_Bink.bik",
	["720p\\EnemyWretchCasterOnHit_Bink.bik_atlas"] = "720p\\EnemyWretchCasterOnHit_Bink.bik_atlas",
	["EnemyWretchCasterStart_Bink.bik"] = "1080p\\EnemyWretchCasterStart_Bink.bik",
	["EnemyWretchCasterStart_Bink.bik_atlas"] = "1080p\\EnemyWretchCasterStart_Bink.bik_atlas",
	["720p\\EnemyWretchCasterStart_Bink.bik"] = "720p\\EnemyWretchCasterStart_Bink.bik",
	["720p\\EnemyWretchCasterStart_Bink.bik_atlas"] = "720p\\EnemyWretchCasterStart_Bink.bik_atlas",
	["EnemyWretchCasterStop_Bink.bik"] = "1080p\\EnemyWretchCasterStop_Bink.bik",
	["EnemyWretchCasterStop_Bink.bik_atlas"] = "1080p\\EnemyWretchCasterStop_Bink.bik_atlas",
	["720p\\EnemyWretchCasterStop_Bink.bik"] = "720p\\EnemyWretchCasterStop_Bink.bik",
	["720p\\EnemyWretchCasterStop_Bink.bik_atlas"] = "720p\\EnemyWretchCasterStop_Bink.bik_atlas",
	-- Wretched Pest/ThiefMineLayer
	["EnemyStyxThiefIdle_Bink.bik"] = "1080p\\EnemyStyxThiefIdle_Bink.bik",
	["EnemyStyxThiefIdle_Bink.bik_atlas"] = "1080p\\EnemyStyxThiefIdle_Bink.bik_atlas",
	["720p\\EnemyStyxThiefIdle_Bink.bik"] = "720p\\EnemyStyxThiefIdle_Bink.bik",
	["720p\\EnemyStyxThiefIdle_Bink.bik_atlas"] = "720p\\EnemyStyxThiefIdle_Bink.bik_atlas",
	["EnemyWretchThiefFidget_Bink.bik"] = "1080p\\EnemyWretchThiefFidget_Bink.bik",
	["EnemyWretchThiefFidget_Bink.bik_atlas"] = "1080p\\EnemyWretchThiefFidget_Bink.bik_atlas",
	["720p\\EnemyWretchThiefFidget_Bink.bik"] = "720p\\EnemyWretchThiefFidget_Bink.bik",
	["720p\\EnemyWretchThiefFidget_Bink.bik_atlas"] = "720p\\EnemyWretchThiefFidget_Bink.bik_atlas",
	["EnemyWretchThiefOnHit_Bink.bik"] = "1080p\\EnemyWretchThiefOnHit_Bink.bik",
	["EnemyWretchThiefOnHit_Bink.bik_atlas"] = "1080p\\EnemyWretchThiefOnHit_Bink.bik_atlas",
	["720p\\EnemyWretchThiefOnHit_Bink.bik"] = "720p\\EnemyWretchThiefOnHit_Bink.bik",
	["720p\\EnemyWretchThiefOnHit_Bink.bik_atlas"] = "720p\\EnemyWretchThiefOnHit_Bink.bik_atlas",
	["EnemyWretchThiefThrow_Bink.bik"] = "1080p\\EnemyWretchThiefThrow_Bink.bik",
	["EnemyWretchThiefThrow_Bink.bik_atlas"] = "1080p\\EnemyWretchThiefThrow_Bink.bik_atlas",
	["720p\\EnemyWretchThiefThrow_Bink.bik"] = "720p\\EnemyWretchThiefThrow_Bink.bik",
	["720p\\EnemyWretchThiefThrow_Bink.bik_atlas"] = "720p\\EnemyWretchThiefThrow_Bink.bik_atlas",
	["EnemyWretchThiefWalk_Bink.bik"] = "1080p\\EnemyWretchThiefWalk_Bink.bik",
	["EnemyWretchThiefWalk_Bink.bik_atlas"] = "1080p\\EnemyWretchThiefWalk_Bink.bik_atlas",
	["720p\\EnemyWretchThiefWalk_Bink.bik"] = "720p\\EnemyWretchThiefWalk_Bink.bik",
	["720p\\EnemyWretchThiefWalk_Bink.bik_atlas"] = "720p\\EnemyWretchThiefWalk_Bink.bik_atlas",
	["EnemyStyxThiefFidget_Bink.bik"] = "1080p\\EnemyStyxThiefFidget_Bink.bik",
	["EnemyStyxThiefFidget_Bink.bik_atlas"] = "1080p\\EnemyStyxThiefFidget_Bink.bik_atlas",
	["720p\\EnemyStyxThiefFidget_Bink.bik"] = "720p\\EnemyStyxThiefFidget_Bink.bik",
	["720p\\EnemyStyxThiefFidget_Bink.bik_atlas"] = "720p\\EnemyStyxThiefFidget_Bink.bik_atlas",
	["EnemyStyxThiefOnHit_Bink.bik"] = "1080p\\EnemyStyxThiefOnHit_Bink.bik",
	["EnemyStyxThiefOnHit_Bink.bik_atlas"] = "1080p\\EnemyStyxThiefOnHit_Bink.bik_atlas",
	["720p\\EnemyStyxThiefOnHit_Bink.bik"] = "720p\\EnemyStyxThiefOnHit_Bink.bik",
	["720p\\EnemyStyxThiefOnHit_Bink.bik_atlas"] = "720p\\EnemyStyxThiefOnHit_Bink.bik_atlas",
	["EnemyStyxThiefWalk_Bink.bik"] = "1080p\\EnemyStyxThiefWalk_Bink.bik",
	["EnemyStyxThiefWalk_Bink.bik_atlas"] = "1080p\\EnemyStyxThiefWalk_Bink.bik_atlas",
	["720p\\EnemyStyxThiefWalk_Bink.bik"] = "720p\\EnemyStyxThiefWalk_Bink.bik",
	["720p\\EnemyStyxThiefWalk_Bink.bik_atlas"] = "720p\\EnemyStyxThiefWalk_Bink.bik_atlas",
	-- Wretch assassin
	["Enemy_WretchAssassin_Idle_Bink.bik"] = "1080p\\Enemy_WretchAssassin_Idle_Bink.bik",
	["Enemy_WretchAssassin_Idle_Bink.bik_atlas"] = "1080p\\Enemy_WretchAssassin_Idle_Bink.bik_atlas",
	["720p\\Enemy_WretchAssassin_Idle_Bink.bik"] = "720p\\Enemy_WretchAssassin_Idle_Bink.bik",
	["720p\\Enemy_WretchAssassin_Idle_Bink.bik_atlas"] = "720p\\Enemy_WretchAssassin_Idle_Bink.bik_atlas",
	["Enemy_WretchAssassin_Teleport_Bink.bik"] = "1080p\\Enemy_WretchAssassin_Teleport_Bink.bik",
	["Enemy_WretchAssassin_Teleport_Bink.bik_atlas"] = "1080p\\Enemy_WretchAssassin_Teleport_Bink.bik_atlas",
	["720p\\Enemy_WretchAssassin_Teleport_Bink.bik"] = "720p\\Enemy_WretchAssassin_Teleport_Bink.bik",
	["720p\\Enemy_WretchAssassin_Teleport_Bink.bik_atlas"] = "720p\\Enemy_WretchAssassin_Teleport_Bink.bik_atlas",
	["Enemy_WretchAssassin_OnHit_Bink.bik"] = "1080p\\Enemy_WretchAssassin_OnHit_Bink.bik",
	["Enemy_WretchAssassin_OnHit_Bink.bik_atlas"] = "1080p\\Enemy_WretchAssassin_OnHit_Bink.bik_atlas",
	["720p\\Enemy_WretchAssassin_OnHit_Bink.bik"] = "720p\\Enemy_WretchAssassin_OnHit_Bink.bik",
	["720p\\Enemy_WretchAssassin_OnHit_Bink.bik_atlas"] = "720p\\Enemy_WretchAssassin_OnHit_Bink.bik_atlas",
	["Enemy_WretchAssassinRange_Bink.bik"] = "1080p\\Enemy_WretchAssassinRange_Bink.bik",
	["Enemy_WretchAssassinRange_Bink.bik_atlas"] = "1080p\\Enemy_WretchAssassinRange_Bink.bik_atlas",
	["720p\\Enemy_WretchAssassinRange_Bink.bik"] = "720p\\Enemy_WretchAssassinRange_Bink.bik",
	["720p\\Enemy_WretchAssassinRange_Bink.bik_atlas"] = "720p\\Enemy_WretchAssassinRange_Bink.bik_atlas",
	["Enemy_WretchAssassinStab_Bink.bik"] = "1080p\\Enemy_WretchAssassinStab_Bink.bik",
	["Enemy_WretchAssassinStab_Bink.bik_atlas"] = "1080p\\Enemy_WretchAssassinStab_Bink.bik_atlas",
	["720p\\Enemy_WretchAssassinStab_Bink.bik"] = "720p\\Enemy_WretchAssassinStab_Bink.bik",
	["720p\\Enemy_WretchAssassinStab_Bink.bik_atlas"] = "720p\\Enemy_WretchAssassinStab_Bink.bik_atlas",
	["Enemy_WretchAssassin_DeathVFX_Bink.bik"] = "1080p\\Enemy_WretchAssassin_DeathVFX_Bink.bik",
	["Enemy_WretchAssassin_DeathVFX_Bink.bik_atlas"] = "1080p\\Enemy_WretchAssassin_DeathVFX_Bink.bik_atlas",
	["720p\\Enemy_WretchAssassin_DeathVFX_Bink.bik"] = "720p\\Enemy_WretchAssassin_DeathVFX_Bink.bik",
	["720p\\Enemy_WretchAssassin_DeathVFX_Bink.bik_atlas"] = "720p\\Enemy_WretchAssassin_DeathVFX_Bink.bik_atlas",
	-- Tartarus Boss - Furies/Harpies
	["Enemy_Fury_Idle_Bink.bik"] = "1080p\\Enemy_Fury_Idle_Bink.bik",
	["Enemy_Fury_Idle_Bink.bik_atlas"] = "1080p\\Enemy_Fury_Idle_Bink.bik_atlas",
	["720p\\Enemy_Fury_Idle_Bink.bik"] = "720p\\Enemy_Fury_Idle_Bink.bik",
	["720p\\Enemy_Fury_Idle_Bink.bik_atlas"] = "720p\\Enemy_Fury_Idle_Bink.bik_atlas",
	["Enemy_Fury_Run_Bink.bik"] = "1080p\\Enemy_Fury_Run_Bink.bik",
	["Enemy_Fury_Run_Bink.bik_atlas"] = "1080p\\Enemy_Fury_Run_Bink.bik_atlas",
	["720p\\Enemy_Fury_Run_Bink.bik"] = "720p\\Enemy_Fury_Run_Bink.bik",
	["720p\\Enemy_Fury_Run_Bink.bik_atlas"] = "720p\\Enemy_Fury_Run_Bink.bik_atlas",
	["Enemy_Fury_StartStop_Bink.bik"] = "1080p\\Enemy_Fury_StartStop_Bink.bik",
	["Enemy_Fury_StartStop_Bink.bik_atlas"] = "1080p\\Enemy_Fury_StartStop_Bink.bik_atlas",
	["720p\\Enemy_Fury_StartStop_Bink.bik"] = "720p\\Enemy_Fury_StartStop_Bink.bik",
	["720p\\Enemy_Fury_StartStop_Bink.bik_atlas"] = "720p\\Enemy_Fury_StartStop_Bink.bik_atlas",
	["Enemy_Fury_Lunge_Bink.bik"] = "1080p\\Enemy_Fury_Lunge_Bink.bik",
	["Enemy_Fury_Lunge_Bink.bik_atlas"] = "1080p\\Enemy_Fury_Lunge_Bink.bik_atlas",
	["720p\\Enemy_Fury_Lunge_Bink.bik"] = "720p\\Enemy_Fury_Lunge_Bink.bik",
	["720p\\Enemy_Fury_Lunge_Bink.bik_atlas"] = "720p\\Enemy_Fury_Lunge_Bink.bik_atlas",
	["Enemy_Fury_Beam_Bink.bik"] = "1080p\\Enemy_Fury_Beam_Bink.bik",
	["Enemy_Fury_Beam_Bink.bik_atlas"] = "1080p\\Enemy_Fury_Beam_Bink.bik_atlas",
	["720p\\Enemy_Fury_Beam_Bink.bik"] = "720p\\Enemy_Fury_Beam_Bink.bik",
	["720p\\Enemy_Fury_Beam_Bink.bik_atlas"] = "720p\\Enemy_Fury_Beam_Bink.bik_atlas",
	["Enemy_Fury_Lightning_Bink.bik"] = "1080p\\Enemy_Fury_Lightning_Bink.bik",
	["Enemy_Fury_Lightning_Bink.bik_atlas"] = "1080p\\Enemy_Fury_Lightning_Bink.bik_atlas",
	["720p\\Enemy_Fury_Lightning_Bink.bik"] = "720p\\Enemy_Fury_Lightning_Bink.bik",
	["720p\\Enemy_Fury_Lightning_Bink.bik_atlas"] = "720p\\Enemy_Fury_Lightning_Bink.bik_atlas",
	["Enemy_Fury_WhipWhirl_Bink.bik"] = "1080p\\Enemy_Fury_WhipWhirl_Bink.bik",
	["Enemy_Fury_WhipWhirl_Bink.bik_atlas"] = "1080p\\Enemy_Fury_WhipWhirl_Bink.bik_atlas",
	["720p\\Enemy_Fury_WhipWhirl_Bink.bik"] = "720p\\Enemy_Fury_WhipWhirl_Bink.bik",
	["720p\\Enemy_Fury_WhipWhirl_Bink.bik_atlas"] = "720p\\Enemy_Fury_WhipWhirl_Bink.bik_atlas",
	["Enemy_Fury_Shielded_Bink.bik"] = "1080p\\Enemy_Fury_Shielded_Bink.bik",
	["Enemy_Fury_Shielded_Bink.bik_atlas"] = "1080p\\Enemy_Fury_Shielded_Bink.bik_atlas",
	["720p\\Enemy_Fury_Shielded_Bink.bik"] = "720p\\Enemy_Fury_Shielded_Bink.bik",
	["720p\\Enemy_Fury_Shielded_Bink.bik_atlas"] = "720p\\Enemy_Fury_Shielded_Bink.bik_atlas",
	["Enemy_Fury_Dead_Bink.bik"] = "1080p\\Enemy_Fury_Dead_Bink.bik",
	["Enemy_Fury_Dead_Bink.bik_atlas"] = "1080p\\Enemy_Fury_Dead_Bink.bik_atlas",
	["720p\\Enemy_Fury_Dead_Bink.bik"] = "720p\\Enemy_Fury_Dead_Bink.bik",
	["720p\\Enemy_Fury_Dead_Bink.bik_atlas"] = "720p\\Enemy_Fury_Dead_Bink.bik_atlas",
	["Enemy_Fury_Taunt_Bink.bik"] = "1080p\\Enemy_Fury_Taunt_Bink.bik",
	["Enemy_Fury_Taunt_Bink.bik_atlas"] = "1080p\\Enemy_Fury_Taunt_Bink.bik_atlas",
	["720p\\Enemy_Fury_Taunt_Bink.bik"] = "720p\\Enemy_Fury_Taunt_Bink.bik",
	["720p\\Enemy_Fury_Taunt_Bink.bik_atlas"] = "720p\\Enemy_Fury_Taunt_Bink.bik_atlas",
	["Enemy_Alecto_Taunt_Bink.bik"] = "1080p\\Enemy_Alecto_Taunt_Bink.bik",
	["Enemy_Alecto_Taunt_Bink.bik_atlas"] = "1080p\\Enemy_Alecto_Taunt_Bink.bik_atlas",
	["720p\\Enemy_Alecto_Taunt_Bink.bik"] = "720p\\Enemy_Alecto_Taunt_Bink.bik",
	["720p\\Enemy_Alecto_Taunt_Bink.bik_atlas"] = "720p\\Enemy_Alecto_Taunt_Bink.bik_atlas",
	["Enemy_Tisiphone_Taunt_Bink.bik"] = "1080p\\Enemy_Tisiphone_Taunt_Bink.bik",
	["Enemy_Tisiphone_Taunt_Bink.bik_atlas"] = "1080p\\Enemy_Tisiphone_Taunt_Bink.bik_atlas",
	["720p\\Enemy_Tisiphone_Taunt_Bink.bik"] = "720p\\Enemy_Tisiphone_Taunt_Bink.bik",
	["720p\\Enemy_Tisiphone_Taunt_Bink.bik_atlas"] = "720p\\Enemy_Tisiphone_Taunt_Bink.bik_atlas",
	["Enemy_AlectoMultiFuryHover_Bink.bik"] = "1080p\\Enemy_AlectoMultiFuryHover_Bink.bik",
	["Enemy_AlectoMultiFuryHover_Bink.bik_atlas"] = "1080p\\Enemy_AlectoMultiFuryHover_Bink.bik_atlas",
	["720p\\Enemy_AlectoMultiFuryHover_Bink.bik"] = "720p\\Enemy_AlectoMultiFuryHover_Bink.bik",
	["720p\\Enemy_AlectoMultiFuryHover_Bink.bik_atlas"] = "720p\\Enemy_AlectoMultiFuryHover_Bink.bik_atlas",
	["Enemy_AlectoMultiFuryTakeOff_Bink.bik"] = "1080p\\Enemy_AlectoMultiFuryTakeOff_Bink.bik",
	["Enemy_AlectoMultiFuryTakeOff_Bink.bik_atlas"] = "1080p\\Enemy_AlectoMultiFuryTakeOff_Bink.bik_atlas",
	["720p\\Enemy_AlectoMultiFuryTakeOff_Bink.bik"] = "720p\\Enemy_AlectoMultiFuryTakeOff_Bink.bik",
	["720p\\Enemy_AlectoMultiFuryTakeOff_Bink.bik_atlas"] = "720p\\Enemy_AlectoMultiFuryTakeOff_Bink.bik_atlas",
	["Enemy_AlectoMultiFurySkyDive_Bink.bik"] = "1080p\\Enemy_AlectoMultiFurySkyDive_Bink.bik",
	["Enemy_AlectoMultiFurySkyDive_Bink.bik_atlas"] = "1080p\\Enemy_AlectoMultiFurySkyDive_Bink.bik_atlas",
	["720p\\Enemy_AlectoMultiFurySkyDive_Bink.bik"] = "720p\\Enemy_AlectoMultiFurySkyDive_Bink.bik",
	["720p\\Enemy_AlectoMultiFurySkyDive_Bink.bik_atlas"] = "720p\\Enemy_AlectoMultiFurySkyDive_Bink.bik_atlas",
	["Enemy_TisiphoneMultiFuryHover_Bink.bik"] = "1080p\\Enemy_TisiphoneMultiFuryHover_Bink.bik",
	["Enemy_TisiphoneMultiFuryHover_Bink.bik_atlas"] = "1080p\\Enemy_TisiphoneMultiFuryHover_Bink.bik_atlas",
	["720p\\Enemy_TisiphoneMultiFuryHover_Bink.bik"] = "720p\\Enemy_TisiphoneMultiFuryHover_Bink.bik",
	["720p\\Enemy_TisiphoneMultiFuryHover_Bink.bik_atlas"] = "720p\\Enemy_TisiphoneMultiFuryHover_Bink.bik_atlas",
	["Enemy_TisiphoneMultiFuryTakeOff_Bink.bik"] = "1080p\\Enemy_TisiphoneMultiFuryTakeOff_Bink.bik",
	["Enemy_TisiphoneMultiFuryTakeOff_Bink.bik_atlas"] = "1080p\\Enemy_TisiphoneMultiFuryTakeOff_Bink.bik_atlas",
	["720p\\Enemy_TisiphoneMultiFuryTakeOff_Bink.bik"] = "720p\\Enemy_TisiphoneMultiFuryTakeOff_Bink.bik",
	["720p\\Enemy_TisiphoneMultiFuryTakeOff_Bink.bik_atlas"] = "720p\\Enemy_TisiphoneMultiFuryTakeOff_Bink.bik_atlas",
	["Enemy_TisiphoneMultiFurySkyDive_Bink.bik"] = "1080p\\Enemy_TisiphoneMultiFurySkyDive_Bink.bik",
	["Enemy_TisiphoneMultiFurySkyDive_Bink.bik_atlas"] = "1080p\\Enemy_TisiphoneMultiFurySkyDive_Bink.bik_atlas",
	["720p\\Enemy_TisiphoneMultiFurySkyDive_Bink.bik"] = "720p\\Enemy_TisiphoneMultiFurySkyDive_Bink.bik",
	["720p\\Enemy_TisiphoneMultiFurySkyDive_Bink.bik_atlas"] = "720p\\Enemy_TisiphoneMultiFurySkyDive_Bink.bik_atlas",
}

SjsonFileMappings = {
	-- Character animations - should only contain unique animation data, so we can simply copy the file instead of hooking
	-- Note - it's possible this only works if the file name is the same?
	["Animations\\CharacterAnim_Enemies_BoneDracon.sjson"] = "Animations\\CharacterAnim_Enemies_BoneDracon.sjson",
	["Animations\\CharacterAnim_Enemies_Shades.sjson"] = "Animations\\CharacterAnim_Enemies_Shades.sjson",
	["Animations\\CharacterAnim_Enemies_WretchThug.sjson"] = "Animations\\CharacterAnim_Enemies_WretchThug.sjson",
	["Animations\\CharacterAnim_Enemies_Wringer.sjson"] = "Animations\\CharacterAnim_Enemies_Wringer.sjson",
	["Animations\\CharacterAnim_Enemies_WretchAssassin.sjson"] = "Animations\\CharacterAnim_Enemies_WretchAssassin.sjson",
	["Animations\\CharacterAnim_EnemiesBosses_Furies.sjson"] = "Animations\\CharacterAnim_EnemiesBosses_Furies.sjson",
}

-- map_text and thing_bin file names
-- thing_bin files are re-encoded from the original Hades files, and are stored in the plugin_data folder
-- map_text files are copied directly from the Hades installation, if not defined below in MapTextFileNames
MapFileNames = {
	-- Tartarus
	"RoomOpening",
	"A_PreBoss01",
	"A_Boss01",
	"A_Boss02",
	"A_Boss03",
	"A_PostBoss01",
	"A_MiniBoss01",
	"A_MiniBoss02",
	"A_MiniBoss03",
	"A_MiniBoss04",
	"A_Shop01",
	"A_Story01",
	"A_Reprieve01",
	"A_Combat01",
	"A_Combat02",
	"A_Combat03",
	"A_Combat04",
	"A_Combat05",
	"A_Combat06",
	"A_Combat07",
	"A_Combat08A",
	"A_Combat08B",
	"A_Combat09",
	"A_Combat10",
	"A_Combat11",
	"A_Combat12",
	"A_Combat13",
	"A_Combat14",
	"A_Combat15",
	"A_Combat16",
	"A_Combat17",
	"A_Combat18",
	"A_Combat19",
	"A_Combat20",
	"A_Combat21",
	-- These two rooms have no RoomData table attached, so we don't need to copy them over
	-- "A_Combat22",
	-- "A_Combat23",
	"A_Combat24",
	"A_Combat25",
}

-- .map_text files that should be copied from the plugin_data folder instead of the Hades installation
MapTextFileNames = {
	-- A new Terrain group was added to resolve flickering tiles next to where the player spawns
	RoomOpening = true,
}

-- Languages supported by Hades
HelpTextLanguages = {
	"de",
	"en",
	"es",
	"fr",
	"it",
	"ja",
	"ko",
	"pl",
	"pt-BR",
	"ru",
	"zh-CN"
}
